### ISSUE TITLE
"Maximum update depth exceeded" error when resizing in Chrome

### ISSUE THREAD

**Issue by SkeDoodle** [fullcalendar/fullcalendar#5935] opened 2020-10-29 14:23 UTC
Hi,
We bought 2 license keys and have been enjoying the Fullcalendar library so far.
Our project uses the React version v5.3.1 with the Resource Timeline and Timeline plugins.

However today, we noticed that resizing the window leads to an error `Maximum update depth exceeded`.
This reported bug https://github.com/fullcalendar/fullcalendar/issues/5606 mentioned something very similar and was already fixed in v5.2.0.

### Reduced Test Case

[Code Sandbox reduced test case](https://codesandbox.io/s/sleepy-monad-54y79).

### Bug Description

- using chrome
- increase/decrease the browser window width
- notice the app crashing with a `Uncaught Error: Maximum update depth exceeded`

### Screenshots

![calendar-crash-on-resize](https://user-images.githubusercontent.com/9872645/97586389-7deaf280-19fa-11eb-967e-537e6132af59.gif)

Thank you.

**Comment by acerix** [comment] 2020-11-02 20:49
Thanks, confirmed.  Your demo would not load in Chrome for me initially, but it works after "open in new window" and I get the same error.

**Comment by SkeDoodle** [comment] 2020-11-03 15:23
Thank you very much for taking care of this!

**Comment by arshaw** [comment] 2020-11-11 20:39
Thanks for this report @SkeDoodle. I'm able to reproduce this very sporadically. This is a very hard problem to debug for me. I strongly believe that in the next major version of FullCalendar, which will drop IE support and thus be able to do all sorts of more efficient sizing monitoring, it will all be fixed.

In the meantime, the workaround is to increase [windowResizeDelay](https://fullcalendar.io/docs/windowResizeDelay). When I set it to `200`, I was unable to reproduce your problem.

**Comment by SkeDoodle** [comment] 2020-11-13 11:01
Hi @arshaw ! Thanks for the workaround idea. I just updated my CodeSandbox example with latest 5.4.0 https://codesandbox.io/s/pedantic-architecture-o43ni?file=/src/App.js and I can still reproduce it on Chrome. Although I will agree, that the _windowResizeDelay_ prop does somehow mitigate the crash.

I can also understand why this is hard to debug and fix.

In our usage of the Fullcalendar library, we extend each rows with our own components using the [eventContent hook](https://fullcalendar.io/docs/event-render-hooks). We have ~100 rows, maybe more. I hope that even with lots of components to render on screen and your `windowResizeDelay` will do the trick.

If not, I'll probably come back in this thread with an updated reduced test case :)

Thanks a lot and happy hacking ⌨!

**Comment by pig800509** [comment] 2021-09-10 09:27
I think the problem is caused by `dayMaxEvents={true}` and `dayMaxEventRows={true}`

**Comment by cfator** [comment] 2021-10-07 18:37
We are running into this issue as well.  Only between viewport sizes between 848px and 1070px.  Have tried the windowResizeDelay but no luck there.  Any ETA on resolving this?

**Comment by alexandraseri** [comment] 2021-12-20 16:32
Same here, when zooming in chrome for 175% we get "Maximum depth" error as well. 
Any news on it?

**Comment by alexandraseri** [comment] 2021-12-21 13:56
Actually I think it is the "allDaySlot = false" i have :/

**Comment by pavsidhu** [comment] 2022-03-07 14:41
Can also confirm I'm getting this issue, removing `allDaySlot={false}` prevents this. It's also odd since removing my custom font fixes the issue as well.

I'm able to mitigate this for now by setting a windowResizeDelay of 800. Are there any better workarounds or updates on this issue?

**Comment by mate-hcp** [comment] 2022-05-13 14:40
@arshaw I can also confirm problem with this. I was able to debug the code and found this:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/master/scrollgrid/src/ClippedScroller.tsx#L93-L97
```
  componentDidUpdate(prevProps: ClippedScrollerProps) {
    if (!isPropsEqual(prevProps, this.props)) { // an external change?
      this.handleSizing()
    }
  }
```

This line is doing a lot of re-renders of `ClippedScroller` component, mostly because `isPropsEqual` is comparing really big props objects, and it's returning `false` even if objects probably should be equal
https://github.com/fullcalendar/fullcalendar/blob/master/packages/common/src/util/object.ts#L103-L105
```
  if (obj0 === obj1) {
    return true
  }
```


my proposition is to instead comparing whole `props` object, maybe we should compare only those values of objects which should trigger `this.handleSizing()`

For example:
```
componentDidUpdate(prevProps: ClippedScrollerProps) {
  const prevHeight = prevProps.children.props.clientHeight;
  const currentHeight = this.props.children.props.clientHeight;
  const prevWidth = prevProps.children.props.clientWidth;
  const currentWidth = this.props.children.props.clientWidth;

  const isSameHeight = prevHeight === currentHeight;
  const isSameWidth = prevWidth === currentWidth;
  if (!isSameHeight || !isSameWidth) {
    this.handleSizing();
  }
}
```
this will reduce a lot unnecessary re-renders of `ClippedScroller` component, and can fix problem with "Maximum update depth exceeded"

**Comment by grazielleanna** [comment] 2022-06-14 19:36
I got the same error but I noticed that it happens when using dateSet to update some state.

How can I solve this problem?

[image](https://user-images.githubusercontent.com/53841934/173672956-8aee3a77-08c2-4b02-9c73-096943747dce.png)

**Comment by arshaw** [comment] 2022-07-27 04:02
The most recent posts are likely reproductions of these two very similar bugs:
https://github.com/fullcalendar/fullcalendar-react/issues/131
https://github.com/fullcalendar/fullcalendar-react/issues/185

Can you please try [v5.11.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.11.2) and see if it's fixed?

**Closed by arshaw** 2022-07-27 04:02 UTC
Labels: Confirmed, Responsive

**Comment by alexandraseri** [comment] 2022-07-27 12:03
@moranza @chaim-wix fyi
