### ISSUE TITLE
Time slot selection jumps to a new position when scrolling the timeline view on iPad

### ISSUE THREAD

**Issue by nakamura-github** [fullcalendar/fullcalendar#4841] opened 2019-02-08 04:21 UTC
When schedule time is set to any time after 1600 hours (4:00 PM) on iPad, the cursor position moves backward or behind by 6 hours. I.e. the cursor stops on 10:00 AM.

The desired behavior is, to stop the cursor exactly on the desired time to either direction in units of 30 minutes.

To reproduce this behavior, open the demonstration screen by clicking below URL on iPad, press and long hold the schedule set to 2000 hours (8:00 PM), and change the time slot.
https://jsfiddle.net/syderwh6/10/

**Comment by arshaw** [comment] 2020-06-26 16:48
i'm closing this issue until we get a reproduction on the basic debug template, as well as an animated GIF or video demonstration of the bug that **includes the date-selecting**, which seems to be integral to this bug report.

**Closed by arshaw** 2020-06-26 16:48 UTC
Labels: Reproducing, Timeline View, Touch
