### ISSUE TITLE
Minimal height for events

### ISSUE THREAD

**Issue by psunix** [fullcalendar/fullcalendar#3391] opened 2016-10-24 14:39 UTC
if an event is shorter than 30min it's height is reduced and it's label is cut-off. 

![selection_003](https://cloud.githubusercontent.com/assets/655627/19649895/c86232c8-9a07-11e6-898f-337c695b5d34.png)

other calendar tools have a minimal height, so the labels are always readable. 

![selection_004](https://cloud.githubusercontent.com/assets/655627/19650032/25f741e4-9a08-11e6-9712-94ed0535b4df.png)

**Comment by caseyjhol** [comment] 2016-10-26 04:36
Duplicate of #961.

**Comment by arshaw** [comment] 2016-10-30 08:41
hi @psunix , dup of:
https://github.com/fullcalendar/fullcalendar/issues/961
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2016-10-30 08:41 UTC
