### ISSUE TITLE
Show all dates/days in month and week view of Fullcalendar even if there is no event for that specific date in list view?

### ISSUE THREAD

**Issue by lakhvir1994** [fullcalendar/fullcalendar#6295] opened 2021-05-06 06:35 UTC
I am working on the Angular-11 application and using Fullcaledar 5.5.0, I love Fullcalendar but I have a requirement to view events in list view (https://fullcalendar.io/docs/list-view), but when I integrate this it shows only those days which have events on it.

Let me explain to you with an example,

I have 2 events one is for Monday and another one is for Friday, so when I see the list view it shows only 2 rows (Monday and Friday). But I want that all days will appear and show events with days that have and the days which don't have events should show no event tag.

**Comment by acerix** [comment] 2021-05-10 20:38
Duplicate of #6295
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2021-05-10 20:38 UTC
