### ISSUE TITLE
minTime and maxTime bug

### ISSUE THREAD

**Issue by WilliamPeralta** [fullcalendar/fullcalendar#3074] opened 2016-03-02 17:49 UTC
I upgraded from  2.3.1 to the latest version, and  now I do not see more labels of the boxes with the schedules , when I put "minTime: 08: 20 and maxTime: 23: 20" works well, but when I put "minTime: 08 : 10 and maxTime: 23: 10 "does not work anymore, I put as the interval "00:50:00 ",

With the previous version works well.

**Comment by WilliamPeralta** [comment] 2016-03-02 18:40
`renderSlatRowHtml: function() {
		var view = this.view;
		var isRTL = this.isRTL;
		var html = '';
		console.log(this.minTime);
		var slotTime = moment.duration(+this.minTime); // wish there was .clone() for durations
		console.log(slotTime);
		var slotDate; // will be on the view's first day, but we only care about its time
		var isLabeled;
		var axisHtml;

		// Calculate the time for each slot
		while (slotTime < this.maxTime) {
			slotDate = this.start.clone().time(slotTime);
			isLabeled = isInt(divideDurationByDuration(slotTime, this.labelInterval));
			console.log(slotTime);
			console.log(this.labelInterval);
			console.log(divideDurationByDuration(slotTime, this.labelInterval));
			isLabeled = true;
			axisHtml =
				'<td class="fc-axis fc-time ' + view.widgetContentClass + '" ' + view.axisStyleAttr() + '>' +
					(isLabeled ?
						'<span>' + // for matchCellWidths
							htmlEscape(slotDate.format(this.labelFormat)) +
						'</span>' :
						''
						) +
				'</td>';

			html +=
				'<tr data-time="' + slotDate.format('HH:mm:ss') + '"' +
					(isLabeled ? '' : ' class="fc-minor"') +
					'>' +
					(!isRTL ? axisHtml : '') +
					'<td class="' + view.widgetContentClass + '"/>' +
					(isRTL ? axisHtml : '') +
				"</tr>";

			slotTime.add(this.slotDuration);
		}`

If I force it "is labeled" a true work, what is this flag?

**Comment by WilliamPeralta** [comment] 2016-03-02 20:36
check my pull request

https://github.com/fullcalendar/fullcalendar/pull/3075

**Comment by arshaw** [comment] 2016-03-06 23:55
could you please post a JSBin demonstrating the original problem?
http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by WilliamPeralta** [comment] 2016-03-10 09:21
the labels of slot times are not showed, sorry for my bad english ;)

https://jsbin.com/xuwaqe/3/edit?html,output

**Comment by arshaw** [comment] 2016-05-31 06:02
thanks for the reply!
what you describe is a duplicate of
#2786
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by arshaw** 2016-05-31 06:02 UTC
Labels: Status-Reproducing
