### ISSUE TITLE
drag events to the next month

### ISSUE THREAD

**Issue by Goddard** [fullcalendar/fullcalendar#3106] opened 2016-03-28 22:08 UTC
What if some one needs to drag an event to the next month on a calender?  It appears no default functionality exists for this.  Shouldn't dragging off the calender result in moving the calender pages left or right?  Any ideas?

Thanks

**Comment by arshaw** [comment] 2016-04-14 11:47
duplicate of https://github.com/fullcalendar/fullcalendar/issues/2542

**Closed by arshaw** 2016-04-14 11:47 UTC
