### ISSUE TITLE
Subsequent property declarations must have the same type. Property 'fullCalendar' must be of type 'Calendar', but here has type 'object'

### ISSUE THREAD

**Issue by osnersanchez** [fullcalendar/fullcalendar#4318] opened 2018-09-16 23:48 UTC
I have this problem using fullcalendar-scheduler in angular 
![image](https://user-images.githubusercontent.com/12916793/45599365-50789180-b9b8-11e8-92d2-80070e24b105.png)

this is my repository for the demonstration

https://github.com/osnersanchez/Error-fullcalendar-scheduler

**Comment by acerix** [comment] 2018-09-19 00:40
Closing since this is a duplicate of https://github.com/fullcalendar/fullcalendar-scheduler/issues/461

**Closed by acerix** 2018-09-19 00:40 UTC
