### ISSUE TITLE
More rows than set in dayMaxEventRows are displayed

### ISSUE THREAD

**Issue by yyamamotowb** [fullcalendar/fullcalendar#6001] opened 2020-12-01 12:09 UTC
### Reduced Test Case

https://codepen.io/yamamoto19730701/pen/xxEGJwd
2020/11/3

### Bug Description
See the URL above.
I set dayMaxEventRows=4.
I expect 4 row include 'more' event.
I expect 4 row at 2020/11/3.
However, 5 row  is displayed at 2020/11/3.

### More Information
Maybe it's the same problem as https://github.com/fullcalendar/fullcalendar/issues/5883.
if change to dayMaxEventRows=3 ,it is correct result.(https://codepen.io/yamamoto19730701/pen/gOwpjJY)

**Comment by acerix** [comment] 2020-12-01 20:07
It does seem like a duplicate of that issue because it also works when `eventOrder` is not used.
https://github.com/fullcalendar/fullcalendar/issues/5883
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2020-12-01 20:07 UTC
