### ISSUE TITLE
removeEvents/addEventSource without rerendering

### ISSUE THREAD

**Issue by ueler** [fullcalendar/fullcalendar#4084] opened 2018-02-28 15:13 UTC
Our setup:
---
We use FullCalendar together with the scheduler plugin.
We are currently doing performance enhancements as our current code is quiet slow with lots of events.
Our current Setup: 5 resources with total 1605 events

Our issue:
---
We sometimes need to reload a single resource only. We do this by 
1. loading the events for the specific resource from our backend
2. remove the existing events belonging to the resource by calling removeEvents (https://fullcalendar.io/docs/removeEvents) with a filter
3. adding the newly loaded events by calling addEventSource

We noticed that fullcalendar re-renders ALL (also events from other resources) events on
1. removeEvents 
2. addEventSource
As our rendering step is quite expensive this leads to an almost unusable app.

Is it possible to turn off re-rendering of the other events in the two mentioned functions or is there a faster approach for our use case?

Thanks for your help!

**Comment by acerix** [comment] 2018-03-02 14:07
Thanks for the report.  There is a similar issue to improve performance of rendering of events:

https://github.com/fullcalendar/fullcalendar/issues/3003
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Would you be able to post a [runnable, stripped-down demonstration of the issue](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

You would get better performance by keeping track of event array yourself, so there is only 1 re-render per reload, instead of 1 for removeEvents and 1 for addEventSource, since both currently re-render all events:

https://codepen.io/acerix/pen/WMmLKw?&editors=001

**Comment by acerix** [comment] 2018-03-02 15:01
Yes, currently there is no way to change events without re-rendering all of them, but as mentioned in https://github.com/fullcalendar/fullcalendar/issues/3003, that might fixed by rendering sub-components instead.  With multiple resources, it might be possible to only re-render resources that had changes to it's events.

**Comment by justanotheranonymoususer** [comment] 2018-03-04 22:03
I had a similar issue. I add custom CSS as suggested in the example here:
https://fullcalendar.io/docs/eventClick

If I call `removeEvents`, even with a predicate which is always false, my custom CSS resets, which is not convenient and not performant at all.

**Comment by arshaw** [comment] 2018-05-07 19:27
we'll use #3003 for further discussion

**Closed by arshaw** 2018-05-07 19:27 UTC
