### ISSUE TITLE
Navigation buttons cause form to be submitted if calendar is within a form element

### ISSUE THREAD

**Issue by Karl-Parris** [fullcalendar/fullcalendar#5336] opened 2020-04-06 09:20 UTC
After updating to v5 beta, if the calendar is within a form element, the form is submitted when switching months due to the buttons missing type="button".

Example: https://codepen.io/ParadoxKarl/pen/LYVKvdP

**Comment by acerix** [comment] 2020-04-06 14:38
Thanks, confirmed

**Comment by melloware** [comment] 2020-06-23 20:15
Is this a duplicate of: https://github.com/fullcalendar/fullcalendar/issues/5336 ???

**Comment by arshaw** [comment] 2020-06-23 20:59
duplicate of https://github.com/fullcalendar/fullcalendar/issues/5529 , which was just fixed and released

**Closed by arshaw** 2020-06-23 20:59 UTC
Labels: Confirmed, Toolbar
