### ISSUE TITLE
refetchEvents when calendar Is hidden results in events disappearing.

### ISSUE THREAD

**Issue by kylethielk** [fullcalendar/fullcalendar#2936] opened 2015-11-11 23:14 UTC
JSBin: http://jsbin.com/mosuqujawa/edit?html,js,output

Using JSBin click the "Run Test" button. This will:

1. Hide the Calendar.
2. fullCalendar('refetchEvents')
3. Show the Calendar.
4. fullCalendar('render')

The calendar will be empty of events. If you navigate between views or forward/backward in time events appear again.

I was previously on 2.0.2 and this was not present, upgrading to 2.4 shows this behavior.

**Comment by kylethielk** [comment] 2015-11-12 15:12
Walking through the code it looks like in `renderView()` the following check is made:

    if (!currentView.displaying ||
        !date.isWithin(currentView.intervalStart, currentView.intervalEnd)) 

The following will result in the events not ever being re-rendered after calendar is shown:

1. Hide Calendar
2. `refetchEvents()` calls `destoryEvents()`
3. Once events are eventually retrieved from datasource `renderEvents()` is eventually called.
4. `renderEvents()` checks to see if calendar is visible, since it is not nothing is rendered, calendar is currently empty.
5. Show Calendar.
6. Call `fullCalendar('render')` which eventually calls `renderView()`, since `currentView.displaying == true && date.isWithin(currentView.intervalStart, currentView.intervalEnd) == true` the code to render the events is never called.

I have worked around this by changing the check from:

    if (!currentView.displaying ||
        !date.isWithin(currentView.intervalStart, currentView.intervalEnd)) 

to 

        if (
        !currentView.isEventsRendered ||
        !currentView.displaying ||
        !date.isWithin(currentView.intervalStart, currentView.intervalEnd)) 

and it is working fine.

**Comment by dhawkKD** [comment] 2016-03-17 11:33
I am trying to filter out events on some conditions by default it is coming as per expectation but after clicking on controls to filter out events it doesn't show any event. and If I move to next month and then comes back the current month it shows event. Tried the solution given above but didn't get any success.
This issue is actually coming in IE-11 only.

**Comment by arshaw** [comment] 2016-05-29 01:41
thanks for this report. this is a duplicate of
#179
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by arshaw** [comment] 2016-05-29 01:57
i take that back, sry

**Comment by arshaw** [comment] 2016-06-06 00:29
i confirmed @kylethielk's original case, thanks. i have not yet dug into the code or proposed solutions

**Comment by caseyjhol** [comment] 2016-07-11 19:51
This appears to have been resolved in v2.8.0 (most likely due to the removal of destroyEvents).

JSBin: http://jsbin.com/buvebesayi/edit?html,js,output

**Comment by arshaw** [comment] 2016-07-12 06:26
thanks for checking that @caseyjhol. closing this issue

**Closed by arshaw** 2016-07-12 06:26 UTC
Labels: Confirmed, Event Rendering, Event Source
