### ISSUE TITLE
Duplicate event

### ISSUE THREAD

**Issue by sofrerisio** [fullcalendar/fullcalendar#4775] opened 2019-07-15 09:19 UTC
Hey, i've problem with duplicated events on calendar. I show u how it's works.
**1.** I add event to calendar with addEvent() method:
![Zrzut ekranu 2019-07-15 o 10 47 06](https://user-images.githubusercontent.com/52911064/61205097-6dbce000-a6ef-11e9-842f-93e665bf8a35.jpeg)
![Zrzut ekranu 2019-07-15 o 10 50 15](https://user-images.githubusercontent.com/52911064/61205189-af4d8b00-a6ef-11e9-881b-e232b029be91.jpeg)
**2.** I refresh our calendar
![Zrzut ekranu 2019-07-15 o 10 50 41](https://user-images.githubusercontent.com/52911064/61205361-1bc88a00-a6f0-11e9-97de-476d5cf8a4cc.jpeg)
Calendar create duplicated event (this same ID) 
![Zrzut ekranu 2019-07-15 o 10 47 20](https://user-images.githubusercontent.com/52911064/61205431-529ea000-a6f0-11e9-8beb-2a0c65bc70ed.jpeg)

**3.** I refresh again with refetchEvents() method
![Zrzut ekranu 2019-07-15 o 10 50 41](https://user-images.githubusercontent.com/52911064/61205486-77931300-a6f0-11e9-9313-9f74050bf70a.jpeg) and on calendar are still two same events 
![Zrzut ekranu 2019-07-15 o 10 47 20](https://user-images.githubusercontent.com/52911064/61205540-998c9580-a6f0-11e9-93f5-e97f21be5b56.jpeg)
**4.** After refresh page is ok and after refresh using refetchEvents method is one item
I using timelineResource view, I think it's problem with refetchEvents(), because method doesnt pay attention on events added by addEvents() and dont remove it. Events received from source (AJAX, eventSources) are correct, but issue is with events created with addEvent().

**Comment by acerix** [comment] 2019-07-15 17:17
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by sofrerisio** [comment] 2019-07-17 09:50
Hey, it's hard to show, but i made some screenshots, so i can tell u what's wrong. I prepared a clean, free of backend things version of my calendar.
**1. ** Fresh opened calendar looks like it: 
<img width="1280" alt="Zrzut ekranu 2019-07-17 o 11 35 12" src="https://user-images.githubusercontent.com/52911064/61365356-dfc82d00-a887-11e9-978f-a25606ce2cd4.png">
**2. ** I dragged the event to another time, so i made a free space for new
<img width="1280" alt="Zrzut ekranu 2019-07-17 o 11 35 22" src="https://user-images.githubusercontent.com/52911064/61365496-24ec5f00-a888-11e9-9fa4-564a0bc7de04.png">
**3. **Meanwhile, i create a new event using addEvent() in dateClick. Blue color on screen
<img width="1280" alt="Zrzut ekranu 2019-07-17 o 11 35 32" src="https://user-images.githubusercontent.com/52911064/61365754-87455f80-a888-11e9-8fd8-564d866fde35.png">
**4. **I clicked Refresh button who has refetchEvents() method and our events are doubled.
I have eventOverlap: false property. In my opinion calendar can't duplicate the events in this same time
<img width="1280" alt="Zrzut ekranu 2019-07-17 o 11 35 46" src="https://user-images.githubusercontent.com/52911064/61366004-020e7a80-a889-11e9-942b-171a8cd3708d.png">

**Comment by jagonzalez11** [comment] 2019-07-17 19:08
I'm having this addEvent duplication issue happen with the back and forward buttons as well. The duplicate event spreads across all views.

**Comment by jagonzalez11** [comment] 2019-07-17 20:41
Maybe this will help. 

Lets say I start with:
`var events = [{eventA},{eventC}];`

When I do:
`getEvents();`
`//outputs: [{eventA},{eventC}]`

Then do addEvent() and check the events
`addEvent(eventB);`
`getEvents();`
`//outputs: [{eventA},{eventC},{eventB}]`

I then click the forward button to go forward to a month with no events, click back to go back to the month with the created event, and do getEvents() again:
`getEvents();`
`//output: [{eventB},{eventA},{eventB},{eventC}]`

the duplicate then gets rendered in

**Comment by solsticesurfer** [comment] 2019-07-24 22:10
We are also experiencing this issue and have found the same behavior that @jagonzalez11 listed above

**Comment by arshaw** [comment] 2019-07-25 21:07
Could you all please read through issue #4614 and tell me if the solution proposed there is acceptable (TL;DR: after adding an event with `addEvent`, mark it as "temporary" so that it goes away the next refetch)

**Comment by wuzhenda** [comment] 2019-08-05 09:41
that's really a poor solution.

**Comment by lovkiymusic** [comment] 2019-08-18 01:31
hello all, i have this issue too, i fix this temporary with reloading page after addEvent (), i trust in @arshaw skillz and eagerly waiting for fixes, with best regards! {:

**Comment by nicholaszuccarelli** [comment] 2019-10-09 23:41
I'm having a similar problem (but slightly different problem) - my issue from what I can tell arises with external event dragging.

All my events (from a JSON API source) are added to event source with ID "events".

If I drag an event into the calendar from an external list, it sets the source to null, I believe that setting the event source of externally dragged events as the same source as the JSON API source should solve the problem (given that the JSON and dragged events will be in the same source list which will stop this duplicate problem).

**Comment by michalfordonski** [comment] 2019-12-10 09:11
Hi, I work with sofrerisio, I noticed one more problem related to the same - when I drag an event to another place, and during this time the interval refreshes the calendar, the event is duplicated - one is in its initial place, and the other can be put away anywhere they will both be until the calendar is reloaded again.

**Comment by arshaw** [comment] 2020-06-29 16:01
Would you be able to post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? Would really appreciate it because the time saved reproducing will be time spent fixing. I'm closing this issue until then.

**Closed by arshaw** 2020-06-29 16:01 UTC
Labels: Discussing, Event Model

**Comment by ar8** [comment] 2020-09-25 23:39
I was having the same issue, in my case i was using this: calendar.addEventSource(values); where values is an json from an ajax call,  I tried everything from the doc, render, refetch, refetchEvents but nothing worked, so 
I had to apply an ugly solution but it worked, I created a function initCalendar in here I initialized the calendar, and the on my  function that executes the ajax call just before executing the ajax call I call to this initCalendar function and create a new instance of the calendar. 

it would be great if you can add more example about how to use methods for example in the render one, there is just this .render(), but it is not specify if I need to do a calendar.render() or for eventSource.refetch() it just says that I need to getEventSources and this one returns an array and when I tried calendar.calendar.getEventSources().refetch I got an error, also after used remove() I was not able to add events anymore.

**Comment by MaiconGilton** [comment] 2020-12-01 01:09
I was facing the same problem using React, I tried everything you guys suggested but nothing worked. I end up fixing this with a callback called **_eventsSet_**,  called after events are initialized/added/changed/removed. So every time date or views change I get the list of my events, then I remove all duplicates:

```
const handleEvents = (events: EventApi[]) => {

        const lookup = events.reduce((a, e) => {
            a[e.id] = ++a[e.id] || 0;
            return a;
        }, {});

        const duplicatedEvents = events.filter(e => lookup[e.id])

        if (duplicatedEvents.length) {
            duplicatedEvents.splice(-1, 1) // keep the last one
            duplicatedEvents.map(evt => evt.remove()) // remove the others, may be more than one
        }

    } 

<FullCalendar 
    eventsSet={handleEvents}
    ...other props
/>
```

**Comment by PeterKarpinski** [comment] 2021-01-27 08:53
Hello, @MaiconGilton solution works for me in React. However, I need to confirm that at least **two** **properties** are the same (not only the 'id')
Is there a way to modify this code to work as I mentioned above?

**Comment by bino98** [comment] 2021-06-10 12:57
@MaiconGilton thank you your solution. It works fine.

**Comment by acsar** [comment] 2021-08-21 19:11
`        events: function (fetchInfo, successCallback, failureCallback) {
          self.$http
            .get(
              `schedule/event/${
                self.currentOfficeId
              }/${fetchInfo.start.toISOString()}/${fetchInfo.end.toISOString()}`
            )
            .then(
              (response_events) => {

                let events = (response_events.data || []).map((v) => {
                  let event = self.calendarApi.getEventById(v.id);
                  if (event) event.remove();
                  return v;
                });

                return successCallback(events);
              },
              function (err) {
                failureCallback(err);
              }
            );
        },`

**Comment by michalfordonski** [comment] 2022-08-08 06:19
I have a similar problem.
1. I download events from the server
2. I change the event (I delete and generate it again under the same ID - unfortunately, setProp is not enough for my needs) 
`calendar.getEventById (dataIn.item.id) .remove ();
                 calendar.addEvent (dataIn.item);`
3. I quickly switch to the next and the previous day
4. A duplicate event (2x new) appears on the calendar and is there to be reloaded

**Comment by JoseAle2610** [comment] 2024-06-05 16:03
@MaiconGilton works for me with vanilla js, thanks!
