### ISSUE TITLE
In TimeGrid calendar, more-link is placed on top

### ISSUE THREAD

**Issue by diegocarrsan** [fullcalendar/fullcalendar#7134] opened 2023-01-10 09:20 UTC
### Reduced Test Case

https://stackblitz.com/edit/github-vdcyss?file=src/DemoApp.vue

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Vue

### Bug Description

In FullCalendar Vue3, using both timeGridWeek and timeGridDay, more-link appears at the top of the event day. It seems that the problem comes from the <a>  fc-timegrid-more-link fc-more-link not being given a manual position.

![image](https://user-images.githubusercontent.com/43759756/211510348-c07e25d8-5ba7-4ac1-8834-c3ae54bcc9e3.png)

**Comment by arshaw** [comment] 2023-01-11 00:38
Duplicate of https://github.com/fullcalendar/fullcalendar/issues/7115, which is queued for release

I wrote a test specifically for this case:
https://github.com/fullcalendar/fullcalendar/commit/a000d65334ca18e462d88b1092f63566db793bda

**Closed by arshaw** 2023-01-11 00:38 UTC

**Comment by arshaw** [comment] 2023-01-11 22:32
Released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

Updated repro:
https://stackblitz.com/edit/github-vdcyss-ltdwod?file=package.json
