### ISSUE TITLE
Recurring events are not displayed after calendar component is reinitialized via useState

### ISSUE THREAD

**Issue by ovelilla** [fullcalendar/fullcalendar#7230] opened 2023-02-28 16:11 UTC
### Reduced Test Case

https://codesandbox.io/s/affectionate-mendeleev-hbrfoi

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

I am using Fullcalendar in React and RRule for recurring events. The problem occurs in any view, but for this case, I will focus on the dayGridMonth view. The issue occurs with any type of repetition, but for this case, the repetition is set to every week. When I resize or drag the event while in the month it was originally created in, everything works fine. However, when I change to a different month and resize or drag the event, all events that were not visible in the original month disappear. I have attached an explanatory image.

![2023-02-28 17-08-00](https://user-images.githubusercontent.com/60881582/221911148-fea0b688-91b3-4e9b-8094-d488486ba0e9.gif)

**Comment by jianhao2010303** [comment] 2023-03-08 03:25
My problem should also be caused by this problem。#7232

**Comment by scriptify** [comment] 2023-03-08 06:32
Related: #7235

**Comment by DaveDoqpal** [comment] 2023-03-17 16:58
Hey Guys,
this happens in Angular as well.
Should I provide a minimal example
or is the underlying issue the same?

**Comment by arshaw** [comment] 2023-03-21 20:35
Fixed in [v6.1.5](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.5)

I converted the original buggy repro to stackblitz because codesandbox never works for me anymore:
https://stackblitz.com/edit/github-8qn74d-pjedon?file=package.json

Here's an updated WORKING repro that uses 6.1.5:
https://stackblitz.com/edit/github-8qn74d?file=package.json

**Closed** 2023-03-21 21:39 UTC
Labels: Confirmed, Event Recurring, React Only
