### ISSUE TITLE
Truncate long event title with ellipsis

### ISSUE THREAD

**Issue by AdrianMrn** [fullcalendar/fullcalendar#6754] opened 2022-03-09 14:22 UTC
PR: https://github.com/fullcalendar/fullcalendar/pull/6750

### Checklist

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

In `dayGridMonth` view if the event's title is too long, the time gets cut off. It's also not clear that the event title is actually longer than what is currently displayed, and is overflowing:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/12762044/157206318-b1bae9f9-e08d-45e3-ae08-af78154f6bfc.png">

This change stops the time from being cut off, and shows an ellipsis if the text is about to overflow (the latter is not as important in my opinion).
<img width="528" alt="image" src="https://user-images.githubusercontent.com/12762044/157206730-5f3c5195-17ec-441b-941c-91c8ddba8d3d.png">

PR: https://github.com/fullcalendar/fullcalendar/pull/6750

**Comment by acerix** [comment] 2022-03-10 22:24
Thanks for the PR, I'll link it again so it shows up here:

https://github.com/fullcalendar/fullcalendar/pull/6750

The issue with the time being cut-off is captured here:

https://github.com/fullcalendar/fullcalendar/issues/6457
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by vhscom** [comment] 2022-03-20 04:03
If this is fixed I believe this pull from 2020 and any related issues may be closed as well: https://github.com/fullcalendar/fullcalendar/pull/5747

**Comment by vhscom** [comment] 2022-03-20 04:04
If this is fixed, I believe this pull from 2020 and any related issues may be closed as well: https://github.com/fullcalendar/fullcalendar/pull/5747.

**Comment by arshaw** [comment] 2024-10-22 02:17
Duplicate of https://github.com/fullcalendar/fullcalendar/issues/6457#issuecomment-2387228928

I already have a fix in v7-beta

**Closed by arshaw** 2024-10-22 02:17 UTC
Labels: Discussing, Event Rendering, DayGrid View
