### ISSUE TITLE
[beta4] Part of calendar not selectable with slotDuration

### ISSUE THREAD

**Issue by seb-jean** [fullcalendar/fullcalendar#4505] opened 2019-02-09 17:56 UTC
Hi,
I am encountering a problem :
When I put `slotDuration: '00:15:00'` with `selectable: true`, there is a part of the calendar that we can not select anymore after 15:00. 

My code:

```javascript
    let calendar = new Calendar(document.getElementById('calendar'), {
            plugins: [ rrulePlugin, interactionPlugin, timeGridPlugin ],
            timeZone: 'Europe/London',
            selectable: true,
            selectConstraint: {
                startTime: '00:00',
                endTime: '24:00'
            },
            defaultView: 'timeGridWeek',
            locale: frLocale,
            columnHeaderFormat: {
                weekday: 'long',
                month: 'short',
                day: 'numeric',
                omitCommas: true
            },
            slotLabelFormat: {
                hour: 'numeric',
                minute: '2-digit'
            },
            allDaySlot: false,
            selectMirror: true,
            slotDuration: '00:15:00',
            scrollTime: '08:00:00',
            eventTextColor: '#ffffff',
        });
```

And When I put `slotDuration: '00:20:00'` with `selectable: true`, there is a part of the calendar that we can not select anymore after 20:00.

**Comment by seb-jean** [comment] 2019-02-09 18:33
And When I put `slotDuration: '00:20:00'` with `selectable: true`, there is a part of the calendar that we can not select anymore after 20:00.

**Comment by acerix** [comment] 2019-02-11 19:46
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by seb-jean** [comment] 2019-02-14 12:05
Hi @acerix ,

Here is a demo: https://codepen.io/guice11/pen/bzxvEa

After 8pm, the selection is impossible.

**Comment by chrisribal** [comment] 2019-02-14 12:27
Same here. I can confirm this issue in resource view with slotDuration set
in beta.4

Am Do., 14. Feb. 2019, 13:05 hat Sébastien JEAN <notifications@github.com>
geschrieben:

**Comment by acerix** [comment] 2019-02-14 20:05
Thanks for the demo, might be related to https://github.com/fullcalendar/fullcalendar/issues/4503

**Comment by AlanCrevon** [comment] 2019-02-27 08:38
I paste the comment i just added to #4534 : 

> I confirm it's is the same as #4505.
> 
> Changing the calendar's width as explained in #4503 modifies the hours after wich you can't drop. Actually : you can't drop an event under a line whose distance from calendar's top is equal to the calendar's width (not sure how to express this...).

**Comment by arshaw** [comment] 2019-03-07 21:46
fixed with https://github.com/fullcalendar/fullcalendar/commit/90a978e8dce5f4add8e2322652525a462febac9a. comment again when released

**Closed by arshaw** 2019-03-07 21:46 UTC
Labels: Confirmed, Selection

**Comment by arshaw** [comment] 2019-03-20 21:30
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by cyrep** [comment] 2019-03-22 13:37
i was having the same issue using angular 7. 
updating to 4.0.1 solved the issue. 
BUT only in development mode. once running ng build --prod, i'm having this issue once again in my production build.
