### ISSUE TITLE
Adding an event with `renderEvent` in `eventDragStart` causes "Uncaught TypeError: Cannot read property 'component' of null"

### ISSUE THREAD

**Issue by smatuonto** [fullcalendar/fullcalendar#4347] opened 2018-10-18 07:00 UTC
I'm upgrading from fc 2.2.7 to 3.9.0.
Everything works correctly except one thing: inside the function eventDragStart I have done a script usefull for cloing event when dragging an event pressing the ALT key. If the ALT key is pressed the script create e temporary event in the start position so that the user understand that it's a clone not a simple drag of the event. On versione 2.2.7 it works great but on 3.9.0 it doesn't work.

The script is:
```
eventDragStart: function(event, revertFunc) {
							
	//clone event -> create a temp event at starting position
	if (altPressed==true) { 				
		
		var eventClone = {
			id:'clone',
			title:event.title,
			start: event.start,
			end: event.end
		};
		$('#calendar').fullCalendar('renderEvent', eventClone);
		
	}
},
```
```
The javascript error is
Uncaught TypeError: Cannot read property 'component' of null
    at HitDragListener.hitOver (fullcalendar.js:11052)
    at HitDragListener.DragListener.trigger (fullcalendar.js:5864)
    at HitDragListener.handleHitOver (fullcalendar.js:2422)
    at HitDragListener.handleDragStart (fullcalendar.js:2396)
    at HitDragListener.DragListener.startDrag (fullcalendar.js:5771)
    at HitDragListener.DragListener.handleDistanceSurpassed (fullcalendar.js:5830)
    at HitDragListener.DragListener.handleMove (fullcalendar.js:5785)
    at HitDragListener.DragListener.handleMouseMove (fullcalendar.js:5843)
    at GlobalEmitter.f (jquery-2.1.3.min.js:2)
    at GlobalEmitter.intercept (fullcalendar.js:1535)
```
Is there a way to make this work on 3.9.0 version?

![fc_error](https://user-images.githubusercontent.com/44255046/47136464-03882380-d2b4-11e8-9192-ffe62b85f538.PNG)

**Comment by acerix** [comment] 2018-10-19 22:52
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by smatuonto** [comment] 2018-10-22 07:18
Hi @acerix I have published two very simple runnable example at the following links:
1) With fc version 2.2.7 work perfectly 
[https://www.arvea.it/fullcalendar_demo/?version=2.2.7] 
2) With fc versione 3.9 it gives me a js error
https://www.arvea.it/fullcalendar_demo/?version=3.9

In this exampe I just want to clone an event at the start position when dragging, to make the user understand that this is not a simple move of the event but a copy.
I hope this would help you to support me.
Thanks!!

Stefano

**Comment by smatuonto** [comment] 2018-11-12 14:43
Hi @arshaw, can you tell me if you or someone else is working on this issue? 
Do you think this problem can be solved? Thanks!!

**Comment by Julen10** [comment] 2019-02-11 15:26
Any news here? @acerix @smatuonto @arshaw

**Comment by arshaw** [comment] 2020-06-26 15:01
this was fixed in the last v4 release and will also be fixed if you upgrade to v5

**Closed by arshaw** 2020-06-26 15:01 UTC
Labels: Confirmed, Event Model, TypeScript
