### ISSUE TITLE
rendering hooks for day/slot headings

### ISSUE THREAD

**Issue by smc395** [fullcalendar/fullcalendar#3331] opened 2016-09-06 18:44 UTC
Was wondering if it is possible to add images/icons and change the CSS to calendar headings where (i.e. Sun 9/4) would be and in an event. Also if it was possible to tie actions to the heading like causing a panel to drop down.

Another question is when switching between month, week, and day views if animations would persist. So for example on the week view when I click on a day it brings a panel to drop down and then I click on the month view. If I click on the week view again will the panel still be dropped down? Thank you!

**Comment by arshaw** [comment] 2016-09-08 09:16
Would be cool to provide a rendering callback function as well as let the slot heading format text accept an HTML string somehow.

**Comment by Rouche** [comment] 2016-09-26 17:16
After reading the idea i changed the code of my temporary fix to this.
Works well for now, but ill wait for the real fix instead of PR.

```
	renderHeadDateCellHtml: function(date, colspan, otherAttrs) {
		var view = this.view;

		var headerText = typeof this.colHeadFormat === 'function' ? this.colHeadFormat(date, colspan) : htmlEscape(date.format(this.colHeadFormat));

		return '' +
			'<th class="fc-day-header ' + view.widgetHeaderClass + ' fc-' + dayIDs[date.day()] + '"' +
				(this.rowCnt === 1 ?
					' data-date="' + date.format('YYYY-MM-DD') + '"' :
					'') +
				(colspan > 1 ?
					' colspan="' + colspan + '"' :
					'') +
				(otherAttrs ?
					' ' + otherAttrs :
					'') +
				'>' +
				// don't make a link if the heading could represent multiple days, or if there's only one day (forceOff)
				view.buildGotoAnchorHtml(
					{ date: date, forceOff: this.rowCnt > 1 || this.colCnt === 1 },
					headerText // inner HTML
				) +
			'</th>';
	},

**Comment by Rouche** [comment] 2016-10-12 15:28
Would this solution be enough? Allow the ```columnFormat``` to be function? Or maybe theres a bigger picture i dont see?

Then in ```renderHeadDateCellHtml``` :
```var headerHtml = typeof this.colHeadFormat === 'function' ? this.colHeadFormat(date, colspan) : htmlEscape(date.format(this.colHeadFormat));```

Will PR if ok.

**Comment by arshaw** [comment] 2016-12-06 07:51
same issue: https://github.com/fullcalendar/fullcalendar/issues/3078

**Comment by arshaw** [comment] 2017-07-14 21:35
closing because this ticket if a duplicate of:
#3078
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2017-07-14 21:35 UTC
Labels: Accepted, Text/HTML, View Rendering
