### ISSUE TITLE
Now indicator showing at the start of the day on timeline view

### ISSUE THREAD

**Issue by adri95cadiz** [fullcalendar/fullcalendar#7586] opened 2024-01-30 13:14 UTC
### Reduced Test Case

https://stackblitz.com/edit/github-w6hh2x?file=src%2Fapp%2Fapp.component.ts

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

Angular

### Bug Description

In the timeline view the now indicator is showing at the start of the day, until around one minute passes and then it is correctly positioned to the exact time of the day it is now.

The expected behaviour would be for the now indicator to show correctly positioned on the first render of the component.

![image](https://github.com/fullcalendar/fullcalendar/assets/10522017/d606f0c4-fa08-437f-9677-de4c7d1e92e8)

**Comment by adri95cadiz** [comment] 2024-01-30 13:17
I just realised this is a duplicate of #7132

**Comment by acerix** [comment] 2024-02-02 22:10
Duplicate of #7132

**Closed by acerix** 2024-02-02 22:10 UTC
