### ISSUE TITLE
dragging recurring event JS error

### ISSUE THREAD

**Issue by YunCongChen** [fullcalendar/fullcalendar#4127] opened 2018-03-29 23:45 UTC
### Bug Reports

From the webpage, when using the new version of fullcalendar, like 3.9.0, I dragged the recurring event. It showed the error:
Link as: <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>

Error:
Uncaught TypeError: Cannot read property 'def' of undefined
    at constructor.getEventDef (fullcalendar.js:13410)
    at constructor.Calendar.isEventInstanceGroupAllowed (fullcalendar.js:10939)
    at members.constructor.isEventInstanceGroupAllowed (fullcalendar.js:7495)
    at constructor.hitOver (fullcalendar.js:4858)
    at constructor.trigger (fullcalendar.js:3432)
    at constructor.handleHitOver (fullcalendar.js:3752)
    at constructor.handleDragStart (fullcalendar.js:3715)
    at constructor.startDrag (fullcalendar.js:3302)
    at constructor.handleDistanceSurpassed (fullcalendar.js:3386)
    at constructor.handleMove (fullcalendar.js:3321)

But if used the version of fullcalendar 3.4.0. It had no such problem.
Link as: <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>

**Comment by acerix** [comment] 2018-04-02 16:56
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The example on the homepage (https://fullcalendar.io/) has a repeating event and I don't get any error when dragging it.

**Comment by YunCongChen** [comment] 2018-04-02 17:47
First, Thank you so much for your help, I appreciate it .

From the  example on the homepage (https://fullcalendar.io/)
The method for repeating Event, It creates two Events with the same ID value for binding these events when dragging.  Bellow is the two events for repeating Event in  (https://fullcalendar.io/)
     {
        id: 999,
        title: 'Repeating Event',
        start: YM + '-09T16:00:00'
      },
      {
        id: 999,
        title: 'Repeating Event',
        start: YM + '-16T16:00:00'
      }, 

I want to make one event and let them recurring through a period, since I don't wants write a lot record in the Database if people create one year period repeating events. The code as bellow(code from HTML page, can't past the whole page into this comment). it used a fullcalendar/3.4.0 version, but no error when dragging it. but if change to a newer version than 3.4.0. It shows the Error as the Bug Report in first comment above.

<body>
<div id='calendar'></div>
</body>

<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css' />
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>

<script>
$(document).ready(function() {
  var date = new Date();
  var d = date.getDate();
  var m = date.getMonth();
  var y = date.getFullYear();

  $('#calendar').fullCalendar({
    defaultView: 'month',
    fixedWeekCount: false,
    editable: true,
    droppable: true,
    eventLimit: true,
    selectable: true,
    slotDuration: "00:41:00",
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay'
    },
    eventRender: function(event) {
      if (event.ranges) {
        return (event.ranges.filter(function(range) { // test event against all the ranges

          return (event.start.isBefore(range.end) &&
            event.end.isAfter(range.start));

        }).length) > 0; //if it isn't in one of the ranges, don't render it (by returning false)
      } else {
        return true;
      }
    },
    events: [{
      id: 1,
      title: "recurring event",
      start: "10:00",
      end: "12:00",
      dow: [1,3, 4],
      ranges: [{
        start: new Date(y, m, d-5, 09, 30),
        end: new Date(y, m, d + 3, 15, 30)
      }, {
        start: new Date(y, m, d + 5, 10, 00),
        end: new Date(y, m, d + 5, 12, 00)
      }]
    }]
  });
});
</script>

**Comment by acerix** [comment] 2018-04-02 18:00
Thanks for the example.  I can see that dragging an event with only a `start` time (no date) in month view gives these errors:

    TypeError: this.eventInstances[0] is undefined[Learn More]
fullcalendar.min.js:6:24197
    TypeError: t is undefined[Learn More]
fullcalendar.min.js:8:6813

https://codepen.io/acerix/pen/GxGmXO?editors=0010

**Comment by jperezdavinchi** [comment] 2018-04-19 17:42
Hello @acerix,
have you been able to make some progress?
I have a project that requires recurring events and would be helpful to use dow instead of creating multiple events objects, but if the fix is not near, I will go for that.
Thanks

**Comment by davechurchill** [comment] 2018-04-30 06:49
This also happens to me in weekly view for a repeated event with the following data

`{ title: 'Drag Me', start: '13:00:00', end: '14:00:00', dow: '[1]' }`

It will happen no matter how many days I put in the dow array

When I try and drag I get:

`fullcalendar.min.js:6 Uncaught TypeError: Cannot read property 'def' of undefined
    at t.getEventDef (fullcalendar.min.js:6)
    at t.isEventInstanceGroupAllowed (fullcalendar.min.js:9)
    at e.isEventInstanceGroupAllowed (fullcalendar.min.js:7)
    at e.hitOver (fullcalendar.min.js:10)
    at e.t.trigger (fullcalendar.min.js:8)
    at e.handleHitOver (fullcalendar.min.js:6)
    at e.handleDragStart (fullcalendar.min.js:6)
    at e.t.startDrag (fullcalendar.min.js:8)
    at e.t.handleDistanceSurpassed (fullcalendar.min.js:8)
    at e.t.handleMove (fullcalendar.min.js:8)`

**Comment by Turpoint** [comment] 2019-06-02 19:26
Any updates on this issue?

**Comment by arshaw** [comment] 2019-07-30 03:58
would someone please be able to post a repro for v4? we'll only fix this in v4

**Comment by acerix** [comment] 2019-08-08 18:11
This is fixed in v4, updated demo:

https://codepen.io/acerix/pen/dxepmr

**Closed by acerix** 2019-08-08 18:11 UTC
Labels: Event DnD/Resize, Event Recurring, Reproducing
