### ISSUE TITLE
Event popover limited to screen height

### ISSUE THREAD

**Issue by ehamrin** [fullcalendar/fullcalendar#6157] opened 2021-02-10 07:54 UTC
### Reduced Test Case

[Reduced test case on codepen](https://codesandbox.io/s/brave-hoover-nzr5s?file=/src/DemoApp.vue)

### Bug Description

Set a limit on number of events to display in a day
Create a lot of events (100+)
Click the "+{n} more" link in the calendar
If there are more events than possibly visible on the screen, they are impossible to see.
The popover should be scrollbable with a max height

**Comment by acerix** [comment] 2021-02-10 20:34
Thanks, I can see the same issue without Vue: 

https://codepen.io/acerix/pen/QWGKPNj?editors=001

**Comment by arshaw** [comment] 2021-03-24 15:18
duplicate of: https://github.com/fullcalendar/fullcalendar/issues/5532

still a problem though.

see this workaround: https://github.com/fullcalendar/fullcalendar/issues/5532#issuecomment-650888359

**Closed by arshaw** 2021-03-24 15:18 UTC
Labels: Confirmed, Event More/Popover
