### ISSUE TITLE
wrong import for moment

### ISSUE THREAD

**Issue by svonnidmeg** [fullcalendar/fullcalendar#4583] opened 2019-03-27 07:39 UTC
I'm working with fullcalendar in Angular 7

Currently the moment module (@fullcalendar/moment) is declared with a deprecated method and cause errors when compile project.

The correct way for moment module is:

```javascript
declare module "@fullcalendar/moment" {
    import * as moment from "moment";
    import { Calendar, Duration } from "@fullcalendar/core";
    export function toMoment(date: Date, calendar: Calendar): moment.Moment;
    export function toDuration(fcDuration: Duration): moment.Duration;
    const _default_10: import("@fullcalendar/core/plugin-system").PluginDef;
    export default _default_10;
}
```

The 1st line needs the '* as' in import moment.

Good job otherwise!
Marc

**Comment by ganySA** [comment] 2019-03-27 09:52
I can confirm this is an issue.

**Comment by Nols1000** [comment] 2019-03-27 10:50
Same as #4580

**Comment by acerix** [comment] 2019-03-27 19:51
Yes, this is a duplicate of:
https://github.com/fullcalendar/fullcalendar/issues/4580
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by acerix** 2019-03-27 19:51 UTC
