### ISSUE TITLE
Evenly expand timeGrid slots to fit height

### ISSUE THREAD

**Issue by M0nter0** [fullcalendar/fullcalendar#265] opened 2015-08-12 10:15 UTC
This comes from [Fit calendar to container stackoverflow question](http://stackoverflow.com/questions/31962155/fit-calendar-to-container)

<hr>

I'm trying to make the fullcalendar fitting on the container without success. I've been modifying `contentHeight`, `height` and `aspectRatio` without results.

`contentHeight:'auto'` is working fine if container is not bigger than the content, displaying scrollbars.

Best calendar configuration I got looks like:

```
$('#calendar').fullCalendar({
   header: {
            left: '',
            center: '',
            right: ''
        },
    defaultView:'agendaWeek',
    contentHeight:'auto',       //auto
    slotDuration: '00:60:00',        
});
```

If I get dynamically the size and I set it:

```
$('#calendar').fullCalendar({
       header: {
                left: '',
                center: '',
                right: ''
            },
        defaultView:'agendaWeek',
        contentHeight:766,     //specific height instead of auto
        slotDuration: '00:60:00',        
    });
```

The calendar expands, but only the last row, displaying an ugly last row like instead of increasing each row to fit the content. It looks like the following:

[![Last row with fixed contentHeight](http://i.stack.imgur.com/1j8QY.png)](http://i.stack.imgur.com/1j8QY.png)

Is it possible to 'maximize' the calendar to fit the container?

I did a [plnkr where you can reproduce/fork it](http://plnkr.co/edit/TAJm5n?p=preview).

_Note: I can't resize the container and the container height is dynamic._

**Comment by M0nter0** [comment] 2015-08-12 13:34
It's neccessary to add to `.fc-slats > table` the height of the difference at bottom, so we need to avoid the size of headers, toolbars, custom elements etc, that can vary based on your customize settings or styles. Setting content table height to container height will overflow the container.

[![enter image description here][1]][1]

The difference at bottom can be obtained like:  



    var bottomContainerPos = $('#container')[0].getBoundingClientRect().bottom;
    var bottomTablePos = $('.fc-slats')[0].getBoundingClientRect().bottom;
    var bottomDifference = bottomContainerPos - bottomTablePos ;

And now we can add the difference to the actual height:

     var newHeight = parseInt(currentHeight) + bottomDifference;
     $( ".fc-slats > table" ).css( "height", newHeight );

Still some pixels could appear below due to table borders.

You can check it [in this plnkr](http://plnkr.co/edit/9nNnr2?p=preview)

  [1]: http://i.stack.imgur.com/T4Cfk.png

**Comment by M0nter0** [comment] 2015-08-12 13:54
Reopen
------

When modifying the table style, the slots are still created based on the default row size, so adding events will not be aligned to its hours as you can check adding any event to this proposal. [Plnkr to reproduce it with events](http://plnkr.co/edit/E5FMwV?p=preview)

**Comment by kylethielk** [comment] 2015-11-11 20:36
I realize this is a new feature request but upgrading from 2.0.2 to 2.4 it was quite the shock to see this 'gutter' appear at the bottom of the calendar when it was not previously there. 

I think in the meantime it at least makes sense to be consistent. In 2.0.2 if aspectRatio was set to a value (height is left unset as is contentHeight) that resulted in the calendar being taller than the height of the slats, the calendar height would simply be truncated. 

I am currently forcing this behavior by adding the following code immediately after initializing the calendar:

    var slatHeight = $("#calendar").find('.fc-slats').height();
    var height = $('#calendar').find('.fc-time-grid-container').height();
    if(slatHeight < height)
    {
        $('#calendar').find('.fc-time-grid-container').css('max-height',slatHeight+'px');
    }

**Comment by Moxide** [comment] 2017-04-11 08:11
Hello,
Sorry to revive this discussion, but is there a way (hack ?) to both make the slots height adapt to calendar height, AND make the events align to those slots ?
Thanks !

**Comment by DonovanCharpin** [comment] 2017-04-28 19:27
Hi guys!

I ran into the same issue. I found another way to manage it. I'm using React but you could find where you can add this piece of code (on my side `componentDidUpdate` because I get the events asynchronously and the component re-render): 

```
    window.dispatchEvent(new Event('resize'));
```

Fullcalendar is listening for this `resize` event so when it's called, fullcalendar seems to rerender the calendar and the events are moved to the right position. It works perfectly on my side and it's not too heavy.

**Comment by Anton-V-K** [comment] 2017-12-24 18:30
Adding `contentHeight: 'auto'` effectively removes bottom empty row in week agenda view (in 3.8.0).

**Comment by hectorvent** [comment] 2018-01-16 16:07
@Anton-V-K Thanks man.

**Comment by EoghanH** [comment] 2018-03-26 18:19
@Anton-V-K indeed it does, but the problem is that if you switch back to say, agendaWeek or month view, it then relies on contentHeight being auto - and it creates a gigantic table.

Docs on https://fullcalendar.io/docs/contentHeight are pretty useless in giving details on what contentHeight defaults to (only stating it uses aspectratio to 'calculate' the contentHeight) - is there any function we can call to set back to the default contentHeight after defaulting to "auto"?

**Comment by soimudaniel** [comment] 2018-09-30 23:36
Hello to everyone. My solution was to just increase the `.fc-time-grid .fc-slats td` height in css from `1.5em` to `2.2em`. It worked like a charm. Also added `contentHeight: 'auto'` like @Anton-V-K said. 

![screen shot 2018-10-01 at 2 32 26 am](https://user-images.githubusercontent.com/23560022/46264215-ae61b900-c522-11e8-9dd6-a64a5b6e0376.png)

**Comment by AlexShafir** [comment] 2019-04-24 13:20
Current status?

**Comment by arshaw** [comment] 2020-02-05 05:46
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by arshaw** [comment] 2020-04-14 05:34
This has been released in v5-beta. Please read the [latest blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

You set [expandRows](https://fullcalendar.io/docs/v5/expandRows) to `true`. That docs article also contains demos.

**Comment by arshaw** [comment] 2020-06-22 21:53
this has been [released in v5](https://fullcalendar.io/blog/2020/06/v5-official). see the demos on the [expandRows](https://fullcalendar.io/docs/expandRows) article.

**Closed by arshaw** 2020-06-22 21:53 UTC
Labels: Accepted, Date/Time Rendering, TimeGrid View, View Sizing

**Comment by away0419** [comment] 2021-07-10 03:47
> 추가 `contentHeight: 'auto'`하면 주 의제 보기에서 맨 아래 빈 행이 효과적으로 제거됩니다(3.8.0에서).
감사합니다.

**Comment by Mihai-github** [comment] 2022-02-11 21:37
Hi, is there a way to set for timeDayGrid event maxWidth and maxHeight? I'm trying to stack avatars one near other like github commit contribution and my problem is with the event boxes not having any option for making them not that big...

I've tried several ways to make this happen but with only css is not possible and with js is not the best solution I think (made it work but does not seems to be the best solution)


Anyone had an issue like mine and can help, please?
