### ISSUE TITLE
Calendar not rendering after switching view while there is an outstanding event callback

### ISSUE THREAD

**Issue by kaljak** [fullcalendar/fullcalendar#4436] opened 2019-01-03 15:02 UTC
Go to http://jsfiddle.net/kaljak/x8v5tcjk/

1. Navigate with arrow to February and to March
2. Wait until events are loaded (timeout simulates server request)
3. Click on "week"
4. Click on "month"
--> Calendar is not showing:
![image](https://user-images.githubusercontent.com/3268945/50644322-ca855400-0f70-11e9-9d6b-7c0e5ddc9a03.png)

There are no errors in the browser console.
I think there is a timing issue. The problem is not always occuring but mostly

**Comment by acerix** [comment] 2019-01-03 18:07
Thanks for the report. I was able to reproduce the issue, it seems to happen if the view is changed while there is a pending timeout, then the view is changed again after the previous `callback()` gets called.  I tried clearing the previous timeout but still get the display error.

http://jsfiddle.net/oh0Lfrb4/

**Comment by arshaw** [comment] 2020-06-26 15:53
hmm, i can't even reproduce the error in v3: https://codepen.io/arshaw/pen/wvMqzXa?editable=true&editors=001

however, i believe i fixed this bug since this ticket was filed. closing, but please comment if the bug persists and ill reopen

**Closed by arshaw** 2020-06-26 15:53 UTC
Labels: Confirmed, Event Fetching, View Date Range
