### ISSUE TITLE
timelineDay with maxTime after 24:00, drag-n-drop behavior

### ISSUE THREAD

**Issue by ravid007** [fullcalendar/fullcalendar#3900] opened 2017-10-28 22:39 UTC
https://codepen.io/ravid007/pen/NwWMea

**My senario:**
When 'drag-n-drop' event in _'agendaDay'_ view from time earlier than 24:00 to time later than 24:00, dragging experience changed to smooth and not gradual like it was before 24:00 and the event duration reduced by half when dropped.
Also while dragging event that start before 24:00 to time later than 24:00 , **before it dropped**, the event object is cut at 24:00 while dragging it to different hours before 24:00.
Something similar happens when dragging event that begins after 24:00 to a time that earlier than 24:00.

Any solution for that ?
Thanks ! 
Ravid

**Comment by arshaw** [comment] 2017-10-30 19:58
confirmed, thanks

**Comment by ravid007** [comment] 2017-11-10 22:07
There is also problem with the nowIndicator.
It disappears after midnight.

Thanks a lot !

**Comment by ravid007** [comment] 2017-11-10 22:11
In checked again, it's not disappeared after midnight.
It appears and stuck on 'minTime'. (In this case 20:00)

**Comment by arshaw** [comment] 2019-03-21 20:54
can someone post a repro with the latest version? i could have sworn I fixed this

**Comment by acerix** [comment] 2019-03-21 21:42
Confirmed that it's fixed in v4 timeGridDay:

https://codepen.io/acerix/pen/EMOejX?editors=0010

But still happens in resourceTimelineDay:

https://codepen.io/acerix/pen/RdqYoE?editors=0010

**Comment by LrntL** [comment] 2020-03-17 19:33
Still no fix since 29 Oct 2017... :-(

**Comment by ravid007** [comment] 2020-03-17 19:42
Still no fix for drag-n-drop. and also for **nowIndicator** that's not working properly when **maxTime** set to after 24:00 and **now** time as well. 
Hopefully it will fixed on version 5...

**Comment by LrntL** [comment] 2020-03-17 19:45
On V3 even if during drag and drop, it's hidden afater midnight on drop my events are correctly moved. But as I said and as you said, it's hidden "under midnight" slot when dragging/resizing.

**Comment by LrntL** [comment] 2020-03-17 19:59
> Hopefully it will fixed on version 5...

I hope so even if I am not familiar on how to set up V4...

**Comment by LrntL** [comment] 2020-04-07 15:19
Still happens in resourceTimelineDay (Scheduler) of Beta V5...

**Comment by acerix** [comment] 2020-08-06 21:25
Reproduction in v5: https://codepen.io/acerix/pen/jOqEVYr?editors=001

**Comment by LrntL** [comment] 2020-08-06 23:56
> Reproduction in v5: https://codepen.io/acerix/pen/jOqEVYr?editors=001

Yep. This will never be fixed... I think. :(

**Closed** 2020-08-12 21:55 UTC
Labels: Confirmed, Event DnD/Resize, Timeline View

**Comment by LrntL** [comment] 2020-08-12 21:57
Does "closes" means it is solved?

**Comment by arshaw** [comment] 2020-08-12 23:20
this has just been fixed/released in [5.3.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.0)

just make sure you have the latest package releases.

demo: https://codepen.io/arshaw/pen/KKzVzZj?editors=001

@acerix could you please notify all paying customers about this bugfix?
