### ISSUE TITLE
Negative margin-right in month view header 

### ISSUE THREAD

**Issue by frlinw** [fullcalendar/fullcalendar#3453] opened 2016-12-11 21:23 UTC
Hi,

.fc-head-container .fc-widget-header element has an auto-calculated margin-right.
This margin-right can be negative and result in horizontal scrollbar... And the horizontal scrollbar result in a vertical scrollbar.

![image](https://cloud.githubusercontent.com/assets/11896237/21083378/536fd0a2-bfef-11e6-8155-02a1de6c925c.png)

Is it possible to set margin-right to 0 if it's negative ? or negative margin is necessary in some cases ?

Thanks for your help

**Comment by arshaw** [comment] 2016-12-12 06:56
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

also, what browser/OS are you using?

**Comment by frlinw** [comment] 2016-12-12 19:39
Windows 10 (with 125% default zoom) + Chrome 55

I tried to reproduce the case in jsbin but no success. 
It happens on zoom or on resize on monthView, scrollbarWidths.right is < 1
And there is an overflow-y set to "scroll" but no scrollbar

![image](https://cloud.githubusercontent.com/assets/11896237/21113631/9a549262-c0aa-11e6-95fc-20cd2bee02b5.png)

**Comment by chanchilun** [comment] 2017-01-05 13:47
I got the same problem

**Comment by arshaw** [comment] 2017-01-05 17:00
Thanks @frlinw I'm able to reproduce very easily by going to [this demo](https://fullcalendar.io/js/fullcalendar-3.1.0/demos/agenda-views.html) in Chrome on my Mac and increasing zoom to 125% (though I sometimes need to resize the browser window until it happens, like you said).

**Comment by arshaw** [comment] 2017-02-14 22:51
Fixed in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

**Closed by arshaw** 2017-02-14 22:51 UTC
Labels: Confirmed, Merged, Scrolling
