### ISSUE TITLE
I finally solved the problem on my own.

### ISSUE THREAD

**Issue by MDB73** [fullcalendar/fullcalendar#5733] opened 2020-08-19 09:30 UTC
### Reduced Test Case

https://github.com/fullcalendar/fullcalendar/issues/5691

### Bug Description

Look at issue: https://github.com/fullcalendar/fullcalendar/issues/5691

I finally solved the problem on my own. 
Whenever a finger is placed on an event, the "handleTouchStart" method is triggered. So if we use two fingers at the same time this creates a problem.

The solution is simple just add "if (this.isTouchDragging === true) return" to the "PointerDragging.ts" file before line number 139.

Once this is done the code should become like this:

handleTouchStart = (ev: TouchEvent) => {
    if (this.isTouchDragging === true) return
    if (this.tryStart(ev)) {
      this.isTouchDragging = true

_Originally posted by @MDB73 in https://github.com/fullcalendar/fullcalendar/issues/5691#issuecomment-674829085_

**Comment by acerix** [comment] 2020-08-24 21:48
@MDB73 Thanks for the solution, I will reopen your existing issue and close this one since the problem is described better there.

**Closed by acerix** 2020-08-24 21:48 UTC
