### ISSUE TITLE
Events of different heights in the same resource can be positioned incorrectly

### ISSUE THREAD

**Issue by ningzhang422** [fullcalendar/fullcalendar#5413] opened 2020-05-12 19:59 UTC
Version : Fullcalendar-schedualer v5 beta2

I found that under the view "resouceTimeline", when multiple events are continuous and there are many texts in events, a display error occurs : two events overlap.

Attention：My setting is that regardless of the start time or end time of each event, they are the same length, that is, the length of a whole day

[https://codepen.io/rubytech/pen/oNjMXZa](url)
![Capture d’écran du 2020-05-12 21-43-23](https://user-images.githubusercontent.com/1186049/81739545-d570c280-949b-11ea-87d5-4119d936bc60.jpg)

**Comment by acerix** [comment] 2020-05-12 21:23
Thanks, confirmed. I removed some things from your demo to make a reduced case and it looks like it's assuming the same height for events in the same resource though they are different heights based on content.

https://codepen.io/acerix/pen/ZEbjbVZ?editors=0010

**Comment by arshaw** [comment] 2020-05-20 09:36
fixed in beta3. more info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

proof: https://codepen.io/arshaw/pen/jObXZWv?editors=0010

**Closed by arshaw** 2020-05-20 09:36 UTC
Labels: Event Rendering, Timeline View
