### ISSUE TITLE
Conflicting times with multiday events for the listWeek and listDay

### ISSUE THREAD

**Issue by dw13** [fullcalendar/fullcalendar#4296] opened 2018-08-23 16:25 UTC
**Bug:**
When creating a multi-day event range with start and end times, there is conflicting information in the listWeek and listDay views.

**Example:**
Take the event value here:
{id: 1, title: 'Test Event', start: '2018-07-29T15:30:00', end: '2018-08-07T12:30:00'}
Have the listWeek and listDay accessible in the definition.
If you access the listWeek view:
-- July 29, 2018 will say 3:30pm - 12:00am
-- July 30, 2018 thru August 6, 2018 will say all-day
-- August 7, 2018 will say 12:00am - 12:30pm
If you access the listDay view:
-- July 29, 2018 thru August 7, 2018 will say 3:30pm - 12:30pm

**Expected Result:**
The individual days for the listDay should be consistent with the listWeek day breakdowns.
Preferred result would be that the listDay will show all-day for July 30, 2018 thru August 6, 2018

**Additional Information:**
I used the event {id: 1, title: 'Test Event', start: '2018-07-28T15:30:00', end: '2018-08-07T12:30:00'} instead and noticed a behavior that might be related. On July 28, 2018, the listWeek view (for Jul 22 – 28, 2018) surprisingly said 3:30pm - 12:30pm as well. Since 2018-07-28 is a Saturday, the listWeek view will only display the one day for the week, so this could suggest the problem happens only when a single event is displayed on a view (which is every case for the listDay view). The same behavior happens if I end it on 2018-08-05 (a Sunday).

**Comment by acerix** [comment] 2018-08-28 22:01
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by dw13** [comment] 2018-08-29 14:33
[CalendarTest.zip](https://github.com/fullcalendar/fullcalendar/files/2332523/CalendarTest.zip)
I included examples:
- The case I listed
- Starting at the end of a week (Saturday)
- Ending at the start of a week (Sunday)
- Starting at the end of a week and then ending at the start of another week

**Comment by acerix** [comment] 2018-08-31 21:38
Thanks for the demo, I can see the inconsistency between listDay and listWeek.  I put the code on codepen for easier testing: https://codepen.io/anon/pen/PdWvRP?editors=0010

**Comment by arshaw** [comment] 2020-06-26 14:28
this is fixed in v5:
https://codepen.io/arshaw/pen/KKVvMzb?editable=true&editors=001

**Closed by arshaw** 2020-06-26 14:28 UTC
Labels: Confirmed, List View
