### ISSUE TITLE
implementation of bootstrap 5

### ISSUE THREAD

**Issue by InSomniaMoon** [fullcalendar/fullcalendar#6533] opened 2021-09-02 10:00 UTC
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

basically update the bootstrap theming to bootstrap 5

**Comment by AgentSmith0** [comment] 2021-09-03 05:27
Duplicate of https://github.com/fullcalendar/fullcalendar/issues/6299.

**Comment by acerix** [comment] 2021-09-03 21:21
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6299
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2021-09-03 21:21 UTC
