### ISSUE TITLE
Calling 'setOption' when there is a date selection causes a typeerror

### ISSUE THREAD

**Issue by qbuache** [fullcalendar/fullcalendar#5266] opened 2020-02-20 15:59 UTC
Hello,

An error occurs when changing an option value with `setOption` in (or just after in my case) the `select` handler.

It does not occur when switching date or view first.

**How to reproduce**
Select any timeslot.

https://codepen.io/crocteamgg/pen/MWwjXRB?editors=0010

Stacktrace on my server (nothing is shown in Codepen):
```
main.js?v=2.1.2:8525 Uncaught TypeError: Cannot read property 'calendar' of undefined
    at t.Slicer._sliceDateSpan (main.js?v=2.1.2:8525)
    at t.sliceDateSelection (main.js?v=2.1.2:1558)
    at t.Slicer.sliceProps (main.js?v=2.1.2:8452)
    at t.render (main.min.js?v=2.1.2:6)
    at t.Component.receiveProps (main.js?v=2.1.2:3957)
    at r.render (main.min.js?v=2.1.2:6)
    at r.Component.receiveProps (main.js?v=2.1.2:3957)
    at CalendarComponent.renderView (main.js?v=2.1.2:6304)
    at CalendarComponent.render (main.js?v=2.1.2:6168)
    at CalendarComponent.Component.receiveProps (main.js?v=2.1.2:3957)
```

**Info**
Using version 4.4.0 without Scheduler
Does not happen in version 4.3.0

Have a nice day

**Comment by acerix** [comment] 2020-02-20 19:56
Thanks, confirmed.  Your codepen is missing the calendar plugins, but I can see the error after adding them.

https://codepen.io/acerix/pen/KKpgbJz?editable=true&editors=001

**Comment by acerix** [comment] 2020-02-20 20:13
As a workaround, you could call `calendar.unselect` before `setOption`.  

https://codepen.io/acerix/pen/ExjgGBo?editors=0010

**Comment by qbuache** [comment] 2020-02-21 07:27
I'm confirming that this is functional with the fix.

Sorry for the Codepen dependencies, I don't know how to find them on unpkg.com

Thank you for your help

**Comment by acerix** [comment] 2020-02-21 18:54
I'll reopen the issue because this should be working without the workaround.

FYI, you can find unpkg links here: https://fullcalendar.io/docs/plugin-index

**Comment by qbuache** [comment] 2020-02-24 07:25
OK.
Also linked to a `.calendar` object, I also had to change a call in another handler :
```
datesRender: function (info) {
    var date = moment(info.view.calendar.getDate());
    ...
```
to this: 
```
datesRender: function () {
   var date = moment(this.getDate());
   ...
```
Error was : 
```
calendar.js?v=2.1.2:1777 Uncaught (in promise) TypeError: Cannot read property 'getDate' of undefined
    at Calendar.datesRender (calendar.js?v=2.1.2:1777)
    at Calendar.publiclyTrigger (main.js?v=2.1.2:6981)
    at Calendar.renderComponent (main.js?v=2.1.2:6843)
    at Calendar.executeRender (main.js?v=2.1.2:6805)
    at Calendar.render (main.js?v=2.1.2:6631)
    at initializeFullcalendar (calendar.js?v=2.1.2:1839)
    at startCalendar (calendar.js?v=2.1.2:84)
```

Thanks for the link.

**Comment by Justinohallo** [comment] 2020-03-02 20:12
I rolled back to 4.3 and the error is still present. 

#5270 does not solve the problem either.

**Comment by georgehrke** [comment] 2020-03-13 10:38
I did a quick `git bisect` to figure out what caused this.
This bug was introduced by https://github.com/fullcalendar/fullcalendar/commit/7299ea333c0b9216f4784d8ff7d197c38deeb5a9

**Comment by georgehrke** [comment] 2020-03-13 10:46
If you actually check out 7299ea333c0b9216f4784d8ff7d197c38deeb5a9 directly, it's completely broken. It doesn't render the grid at all
```js
main.js:8455 Uncaught TypeError: Cannot read property 'calendar' of undefined
    at DayGridSlicer.Slicer._sliceBusinessHours (main.js:8455)
    at DayGridSlicer.sliceBusinessHours (main.js:1558)
    at DayGridSlicer.Slicer.sliceProps (main.js:8429)
    at SimpleDayGrid.render (main.js:1545)
    at SimpleDayGrid.Component.receiveProps (main.js:3954)
    at DayGridView.render (main.js:1600)
    at DayGridView.Component.receiveProps (main.js:3954)
    at CalendarComponent.renderView (main.js:6266)
    at CalendarComponent.render (main.js:6152)
    at CalendarComponent.Component.receiveProps (main.js:3954)
```

That particular error was fixed by @arshaw in 972524a33e5bd0d1ed59f3afecafade8a4948feb, but this bug report is still reproducible on 972524a33e5bd0d1ed59f3afecafade8a4948feb, so it seems that fix is missing some (edge-)cases.
```js
main.js:8507 Uncaught TypeError: Cannot read property 'calendar' of undefined
    at DayGridSlicer.Slicer._sliceDateSpan (main.js:8507)
    at DayGridSlicer.sliceDateSelection (main.js:1558)
    at DayGridSlicer.Slicer.sliceProps (main.js:8434)
    at SimpleDayGrid.render (main.js:1546)
    at SimpleDayGrid.Component.receiveProps (main.js:3954)
    at DayGridView.render (main.js:1601)
    at DayGridView.Component.receiveProps (main.js:3954)
    at CalendarComponent.renderView (main.js:6269)
    at CalendarComponent.render (main.js:6155)
    at CalendarComponent.Component.receiveProps (main.js:3954)
```

**Comment by georgehrke** [comment] 2020-03-13 12:50
@arshaw I can see that you modified `_sliceBusinessHours` and added calendar as a parameter, but you didn't modify `_sliceDateSpan`.
Do we need a similar fix for `_sliceDateSpan` to resolve this error? :)

**Comment by FlopieUtd** [comment] 2020-04-15 09:47
I get the same error on 4.4.0 when I'm not using the rerenderDelay prop in React.

**Comment by kasaiee** [comment] 2020-04-23 06:52
I have this error in 4.3.0 and 4.4.0 when I use `this.setState`

**Comment by stclairdaniel** [comment] 2020-04-24 23:22
I'm getting the same error on 4.4.0

**Comment by chrisjenx** [comment] 2020-04-25 16:58
I down graded to 4.3.0 and still get the error :/

**Comment by chrisjenx** [comment] 2020-04-25 17:07
Ahh sorry, yes downgrade did work (damn npm), 4.3.0 is functional for me.

**Comment by StarpTech** [comment] 2020-05-05 09:08
I have the same issue. When I change the state in an `handleDateClick` handler the error appears.

```jsx
 <FullCalendar
      {...props}
      weekends
      defaultView="timeGridWeek"
      businessHours={{
        daysOfWeek: [1, 2, 3, 4, 5, 6], // Monday - Saturday
        startTime: '08:00',
        endTime: '20:00'
      }}
      selectable
      selectMirror
      selectOverlap={false}
      eventOverlap={false}
      nowIndicator
      editable
      eventConstraint={{
        daysOfWeek: [1, 2, 3, 4, 5, 6], // Monday - Saturday
        startTime: '08:00',
        endTime: '20:00'
      }}
      selectConstraint={{
        daysOfWeek: [1, 2, 3, 4, 5, 6], // Monday - Saturday
        startTime: '08:00',
        endTime: '20:00'
      }}
      header={{
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridWeek,timeGridDay,listWeek'
      }}
      allDaySlot={false}
      plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin]}
      locale={deLocale}
    />
```

**Comment by StarpTech** [comment] 2020-05-05 09:35
4.3.0 works for me too.

**Comment by xeroxstar** [comment] 2020-05-06 06:58
Where can i get the 4.3.0 version?

**Comment by arshaw** [comment] 2020-05-28 03:00
v4.4.1 has just been released and contains a fix. please upgrade all installed fullcalendar packages. if you need a list of the packages that are upgradeable:

```
  4.4.1 @fullcalendar/resource-common
  4.4.1 @fullcalendar/resource-daygrid
  4.4.1 @fullcalendar/resource-timegrid
  4.4.1 @fullcalendar/core
  4.4.1 @fullcalendar/daygrid
  4.4.1 @fullcalendar/timegrid
```

**Closed by arshaw** 2020-05-28 03:00 UTC
Labels: Confirmed, Date Point/Select

**Comment by DonikaV** [comment] 2022-01-27 15:12
How i can call setOption in react on componentDidMount() and use props???
