### ISSUE TITLE
Prevent default "table" styles from affecting inner tables

### ISSUE THREAD

**Issue by efcoyote** [fullcalendar/fullcalendar#4441] opened 2019-01-04 16:13 UTC
When using Bootstrap with Sass for example you can change the variable for the table background color (_$table-bg_). This will effect all tables (also Fullcalendar) so they have a background color instead of transparency. Unfortunately the calendar will overlay other background events in one week in this case.

**Codepen**
https://codepen.io/anon/pen/KbQOjq

The first date at 2018-12-04 will be hide by the second date.

**Comment by acerix** [comment] 2019-01-07 19:48
If you want to set a background color of the calendar, you should set that on the specific table instead of every table:

https://codepen.io/anon/pen/ZVRGGK

**Comment by efcoyote** [comment] 2019-01-07 21:31
I know, but thats not the point. I think fullcalendar should ensure that the tables for background events (_.fc-row .fc-bgevent-skeleton table_) are transparent. Otherwise the overlay system will fail.

**Comment by acerix** [comment] 2019-01-07 22:55
I'm not sure what you mean about the overlay system failing, what are you trying to do?  Aren't the tables  transparent before setting a background color?

**Comment by efcoyote** [comment] 2019-01-08 07:46
I mean the table overlay for single background events in same week.

![table-overlay](https://user-images.githubusercontent.com/12809257/50816340-8c958080-1320-11e9-9b89-160a723bc7a9.jpg)

You see the table of the 5th (blue) will overlay the table of 4th (red). Therefore I think the transparency should be declared explicitly instead of implicilty.

In my special case we have a corporate design as npm-package I don't want to modify. These design based on Bootstrap which allows to specify the background-color for all tables in an easy way.

**Comment by acerix** [comment] 2019-01-08 21:41
So you are requesting that the inner tables explicitly remove any background color?

Bootstrap itself avoids changing the style of all tables; to style your tables with Bootstrap you need to add the `table` class, so presumably the design based on Bootstrap should do the same.

**Comment by efcoyote** [comment] 2019-01-08 22:21
> 
> 
> So you are requesting that the inner tables explicitly remove any background color?
> 
Yes, because your layout depends on that.
>
> Bootstrap itself avoids changing the style of all tables; to style your tables with Bootstrap you need to add the `table` class, so presumably the design based on Bootstrap should do the same.
>
You're right. In version 4 you have to set the `table` class. In our application the corporate design depends on Bootstrap 3, which have an [important difference](https://github.com/twbs/bootstrap-sass/blob/bb7dbf8af72b455b51936bc07e51efcaf6220bcc/assets/stylesheets/bootstrap/_tables.scss#L7). I don't know that before. Perhaps it's better to put the fix in the bootstrap3-theme.

**Comment by acerix** [comment] 2019-01-08 22:56
Bootstrap 3 [also needs the table class](https://getbootstrap.com/docs/3.3/css/#tables), so I believe the issue is only with bootstrap-sass, and therefore not something the calendar should try to fix.

**Comment by arshaw** [comment] 2019-07-25 13:59
i agree with acerix on his last comment. closing

**Closed by arshaw** 2019-07-25 13:59 UTC
Labels: Discussing, View Rendering
