### ISSUE TITLE
[v4-alpha.2] setProp("id", x)

### ISSUE THREAD

**Issue by jonasgroendahl** [fullcalendar/fullcalendar#4344] opened 2018-10-16 13:19 UTC
setProp("id", x) doesn't update id on the Event object but rather ID in the nested def object of the Event. I assume this is bugged?

**Comment by acerix** [comment] 2018-10-16 17:39
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by arshaw** [comment] 2018-12-25 06:42
the `id` accessor knows to query the internal event object. the Event API is essentially just a mask around this internal object.

if there's a bug, please provide a recreation. until then i'm closing this issue

**Closed by arshaw** 2018-12-25 06:42 UTC
Labels: Event Model, Reproducing

**Comment by jaredkinger** [comment] 2019-06-06 18:55
I'm having a similar issue. If you add a new event without an id and try to use setProp('id', value) to set the id later the id remains blank. Trying to get an event by the id that was set using setProp() will return null.

https://codepen.io/anon/pen/vwqGLG
