### ISSUE TITLE
validRange input type does not allow callback functions

### ISSUE THREAD

**Issue by gongAll** [fullcalendar/fullcalendar#5287] opened 2020-03-02 15:25 UTC
On the file input-types.ts ([link](https://github.com/fullcalendar/fullcalendar/blob/f5470c2cb63579b737172eca046196e232474f2e/packages/core/src/types/input-types.ts#L135)) seems to me that the type of validRange is not correct, it should be as visibleRange, per documentation ([link](https://fullcalendar.io/docs/validRange)).

**Comment by acerix** [comment] 2020-03-03 19:53
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or explain what is not working? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by gongAll** [comment] 2020-03-03 20:13
Why was it closed? Don't understand what demonstration is needed...

**Comment by acerix** [comment] 2020-03-03 20:15
I'm not sure why the definition is not correct, does it cause an error?

**Comment by gongAll** [comment] 2020-03-03 20:43
@acerix if you define a callback function as the argument, it will give you an IDE error (not that much of a big deal, I know, it was just a small change), but according to the documentation we are supposed to be able to use a callback function, and sure enough, if I do use, it will work, but all the method will be highlighted as red because it doesn't respect the definition of validRange. It's just a small bug, I believe.

I believe the change would be change this:
`
  validRange?: DateRangeInput
`

to this:

`
  validRange?: ((currentDate: Date) => DateRangeInput) | DateRangeInput
`
as per documentation.

**Comment by acerix** [comment] 2020-03-04 20:04
Thank you for explaining, that makes sense

**Comment by arshaw** [comment] 2020-06-29 23:07
this has been fixed in v5

**Closed by arshaw** 2020-06-29 23:07 UTC
Labels: Confirmed, TypeScript
