### ISSUE TITLE
The last timeslot is wider than the slotWidth if the slotWidth is small enough that the slots do not fill the width of the calendar

### ISSUE THREAD

**Issue by Jalliuz** [fullcalendar/fullcalendar#4999] opened 2019-08-23 07:01 UTC
I am using the "resource timeline" and a very low slotWidth setting of 6 or 8. (with tiny font-size) but the right column behaves wrong on most responsive points.

View it here:
![Screenshot 2019-08-23 at 08 45 41](https://user-images.githubusercontent.com/14107298/63572767-f7c85600-c583-11e9-98c1-c256ba6fb31d.png)

On responsive points it jumps to the correct size but on places more of the responsive points the column gets bigger. I guess it is a bug?

I'm going to define my own exact widths for fullCalendar as a solution on the outer wrapper to solve this. So the wrapper always jumps to the points that it looks good.

Edit: Here is the codepen
https://codepen.io/Julesezaar/pen/oNvZrjy?&editable=true&editors=001

**Comment by Jalliuz** [comment] 2019-08-23 07:49
I was able to do an ugly fix for this view with following Scss

for settings:
`
slotWidth: '8',
views: {
    resourceTimelineFourDays: {
        type: 'resourceTimeline',
        duration: { days: 4 }
    },
},
resourceAreaWidth: '175px',
`

Following scss temporarily fixed my problem

`
@media (min-width: 1757px) {
  .fc-resourceTimelineFourDays-view {
    .fc-content,
    .fc-slats {
      col[style*="width: "] {
        width: auto !important;
      }
    }
  }
}
`

**Comment by acerix** [comment] 2019-08-23 17:45
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by Jalliuz** [comment] 2019-08-26 20:44
https://codepen.io/Julesezaar/pen/oNvZrjy?&editable=true&editors=001

**Comment by acerix** [comment] 2019-08-28 21:43
Thanks for the demo, confirmed.

**Comment by arshaw** [comment] 2020-06-29 16:29
this issue is fixed in v5. there was another ticket somewhere that is almost identical to this, in which i posted a corrected repro demonstrating the fix, but can't find it:(

**Closed by arshaw** 2020-06-29 16:29 UTC
Labels: Confirmed, Date/Time Rendering, Timeline View
