### ISSUE TITLE
In v3.5.0+, if an allDay event includes the end value with a time, the event doesn't show up

### ISSUE THREAD

**Issue by caseyjhol** [fullcalendar/fullcalendar#3986] opened 2017-12-21 01:43 UTC
v3.4.0
https://codepen.io/caseyjhol/pen/QaEreG

v3.5.0
https://codepen.io/caseyjhol/pen/XVKqvZ

v3.8.0
https://codepen.io/caseyjhol/pen/mpEKyb

Removing the time, or the end attribute altogether causes the event to be displayed.

**Comment by acerix** [comment] 2017-12-22 02:43
Thanks for the report.  In the latest version, an event with `allDay: true` does not show on the date if the `end` time of the event is before the end of the date (eg. 11:59:59 is before the end of the day), but the documentation is not clear if that's how it should be working:

https://fullcalendar.io/docs/event_data/Event_Object/

**Comment by githubertus** [comment] 2018-01-09 16:15
Running 3.8.0, I just became aware of that issue. My idea was supplying a form with some reasonable start/end dates to my users plus an option to select an allDay event like:
![create](https://user-images.githubusercontent.com/9904364/34729051-edeb9f92-f55b-11e7-8e9d-0d32339a8341.png)
As caseyjhol already said, with dates like that the event doesn't show up in the calendar (at once).

Currently I'm still storing the data 'as is' in my database like:
`{"title":"yo","start":"2018-01-09T08:00:00+01:00","end":"2018-01-09T09:00:00+01:00","allDay":"true"}`

The surprising part is that after refetching the record from my db the event is displayed correctly. And clicking the event gives:
![refetch](https://user-images.githubusercontent.com/9904364/34729813-f8870656-f55d-11e7-87a3-36ab0c9783cb.png)

As we can see, fullcalendar has automatically adjusted the starting date to 12AM and the end date to null (that's why 'invalid date' is shown in my interface)

Perhaps a more convenient way would be to do that automatic adjustment already on rendering - setting the start date to 12AM of the starting day and 12AM of the following day. This way the event would show up immeditately AND the user still had meaningful end date he could handle.

**Comment by marcenuc** [comment] 2018-04-24 09:58
I think this is duplicate of #3854

**Comment by KarlBaumann** [comment] 2018-05-07 02:41
I am having this issue as well. Should I rewrite my code or is there  going to be a fix for this?

**Comment by arshaw** [comment] 2018-05-07 19:16
yes, closing this because it's a duplicate of:
#3854
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2018-05-07 19:16 UTC
Labels: Discussing, Docs, Event Rendering
