### ISSUE TITLE
Infinitely recursive view rerender, crash

### ISSUE THREAD

**Issue by Prabhakar-Poudel** [fullcalendar/fullcalendar#3519] opened 2017-02-10 06:47 UTC
I was trying to prevent editing in month view and allow it only in agendaDay view.

I tried this:

``` javascript
viewRender(view) {
      if (view.type === 'month') {
        $('.full-calendar').fullCalendar('option', 'editable', false);
      }
}
```

I thought we could do that, but that definitely caused crash. Unfortunately I don't have time to reproduce to show an example. Just wanted to report it.

A hacky solution that I had to do to get desired behaviour was to: 

``` javascript
viewRender(view) {
      if (view.type === 'month') {
          view.options.editable = false;
      }
}
```
just in case someone needs

**Comment by arshaw** [comment] 2017-02-10 19:50
thanks. there have been other reports that are somewhat related. the crux of the problem is that a view rerender is being called from within a viewRender callback, causing infinite recursion. there should be a safeguard against this.

**Comment by arshaw** [comment] 2017-02-12 20:51
Here's the root of the problem: a dynamic options change almost always results in a full view rerender, which calls the `viewRender` callback, which results in infinite recursion.

One potential solution: if the option being changed is already set to the given value, do nothing. This approach would prevent infinite rerenders. It would only result in 2 renders.

I've made a ticket for that here:
[Optimization: dynamic option change, when no change, should not rerender](https://github.com/fullcalendar/fullcalendar/issues/3522)

Another solution is to ignore rerenders that are initiated in the `viewRender` callback. **Though I fear some people would *want* the ability to initiate a rerender, and this would constrain them.**

FYI, the rerender *does* queue up until after the `viewRender` is executed, but still a type of recursion nonetheless.

Another solution: introduce a new callback that only gets called when the date range changes:
[Callback when a view's type or dates change (viewChange?)](https://github.com/fullcalendar/fullcalendar/issues/3521)

That would result in only 2 renders in your situation.

### best solution for your case @Prabhakar-Poudel 

Simply use [view-specific options](https://fullcalendar.io/docs/views/View-Specific-Options/) to specify editable:false for month view:

```js
$('#cal').fullCalendar({
    editable: true,
    views: {
        month: {
            editable: false
        }
    }
});
```

Closing. Wontfix

**Closed by arshaw** 2017-02-12 20:51 UTC
Labels: Confirmed, View Rendering
