### ISSUE TITLE
add event dynamically on eventDragStart

### ISSUE THREAD

**Issue by Gingol** [fullcalendar/fullcalendar#3978] opened 2017-12-13 16:03 UTC
Hi,
I would like to add some events on the calendar when the user starts dragging an event in order to highlight on which resources the user can't drop it.
I made this example:
https://codepen.io/gingol/pen/YYPppa

If the user drag the external events, it works fine and the first 3 resource are "covered" with a colored background event.
Instead if the user starts dragging an event already placed in the calendar it doesn't work because the call to the function 'renderEvent' stops the drag action.

Is there a way to have the same behaviour in both cases?

Best regards

--
Mauro

**Comment by acerix** [comment] 2017-12-13 23:31
The issue is a JavaScript error when dragging an event on the calendar with `renderEvent` called inside `eventDragStart`, eg:
> Uncaught TypeError: Cannot read property '2' of null
Likely related to issue https://github.com/fullcalendar/fullcalendar/issues/3971.

Instead of a background event, could you just color the rows with CSS to show they are covered?

**Comment by Gingol** [comment] 2017-12-14 08:53
I considered this solution, but I'm using the agenda view, so the resources are on columns and it's not so simple to color the background of the resources with CSS.
Furthermore with the background event I am able to forbid drop thanks to `overlap: false` while in the other case I am not, but I think that  can simply resolve this problem with the `resourceIds` in `constraint`.

--
Mauro

**Comment by gantaa** [comment] 2018-06-19 20:12
I would think its a common use case to want to render events to your calendar during a drag start and still have an event be droppable.  This is blocking us from an ideal calendar user experience.  I'm not using the Scheduler plugin, just a simple fullcalendar with droppable: true.  We manage our own resources until we switch to Scheduler, so I must render availability on the calendar with background events while new events are being dragged to the calendar.

@Gingol, can you elaborate on what you mean by "resolving the problem with the resourceIds in the constraint"?

Did you find a workaround to being able to drop onto a calendar that rendered events during dragStart?

**Comment by Gingol** [comment] 2018-06-25 11:21
Hi @gantaa,
I resolve the problem via CSS rules. On the drag start I calculate wich resources and wich time slots I need to render and then I add a css class to colour them.
If you also want to forbid the drop of the event, you need to set the event constraint. See the documentation at: https://fullcalendar.io/docs/eventConstraint

```
let activity = JSON.parse(ev.target.dataset.event)
// Adds css class to every forbidden resources
this.resources.map(r => r.id).filter(id => activity.constraint.resourceIds.indexOf(id) === -1).forEach(resourceId => {
  $(`.fc-bg .fc-day.fc-widget-content[data-resource-id="${resourceId}"]`).addClass('cover-resources')
})
```
```
// Adds css class to forbidden time slots
let timeSlotsElements = []
let startIndex = this._getIndexOfTimeConstraintElement(moment(start), false)
let endIndex = this._getIndexOfTimeConstraintElement(moment(end), true)
if (inverse === true) {
  if (startIndex >= 0) {
    timeSlotsElements = $(`.fc-slats tr`).slice(0, startIndex).children('td:last-of-type')
  }
  if (endIndex >= 0) {
    if (timeSlotsElements.length === 0) {
      timeSlotsElements = $(`.fc-slats tr`).slice(endIndex).children('td:last-of-type')
    } else {
      timeSlotsElements = timeSlotsElements.add($(`.fc-slats tr`).slice(endIndex).children('td:last-of-type'))
    }
  }
  if (startIndex < 0 && endIndex < 0) {
      timeSlotsElements = $(`.fc-slats tr td:last-of-type`)
  }
} else {
  if (startIndex > 0 && endIndex > 0) {
    timeSlotsElements = $(`.fc-slats tr`).slice(startIndex, endIndex).children('td:last-of-type')
  } else if (startIndex > 0 && endIndex <= 0) {
    timeSlotsElements = $(`.fc-slats tr`).slice(startIndex).children('td:last-of-type')
  } else if (startIndex <= 0 && endIndex > 0) {
    timeSlotsElements = $(`.fc-slats tr`).slice(0, endIndex).children('td:last-of-type')
  } else {
    timeSlotsElements = $(`.fc-slats tr td:last-of-type`)
  }
}
timeSlotsElements.addClass(cssClassName)
```

```
_getIndexOfTimeConstraintElement (constraint, roundUp) {
  //Calculates the index in the calendar html table of an certain hour
  let roundedMinutes = 0
  let constraintMinutes = parseInt(constraint.hours()) * 60 + parseInt(constraint.minutes())
  if (roundUp) {
    roundedMinutes = Math.ceil(constraintMinutes / this.slotDurationMinutes) * this.slotDurationMinutes
  } else {
    roundedMinutes = Math.floor(constraintMinutes / this.slotDurationMinutes) * this.slotDurationMinutes
  }
  let roudedConstraint = (constraint.minutes(roundedMinutes % 60).seconds(0)).format('HH:mm:ss')
  return $(`.fc-slats tr[data-time="${roudedConstraint}"]`).index()
}
```
I hope this is clear. If you need more information just ask me.

Regards

**Comment by gantaa** [comment] 2018-06-26 19:04
Thanks.  For now, Ive made my UX such that the forbidden background calendar slots are rendered before the drag start operation begins.  I will explore a solution using css on drag start, but probably after we migrate to using the Scheduler with resources.

I appreciate the example.  We will refer to this soon.  Thank you for putting the time in for us.

**Comment by arshaw** [comment] 2020-06-25 18:08
this is almost definitely fixed in v5

**Closed by arshaw** 2020-06-25 18:08 UTC
Labels: Confirmed, Event DnD/Resize, Event Model
