### ISSUE TITLE
Some events disappears when using Prev/Next quickly

### ISSUE THREAD

**Issue by vklaus** [fullcalendar/fullcalendar#3920] opened 2017-11-08 15:43 UTC
Hello,

I use calendar about 2 years without this problem, but starting version 3.5.0 something has changed. And it is still there as well as in 3.6.2.

When I quickly click on Prev/Next, I can see all events but sometimes some of them (whole week(s)) immediately disapper. See attachment please. The same behavior in Edge/Chrome. I'm using SQL Server and getting JSON data via ASP.NET callback. Sorry, no running example. Maybe similar problem to #3892?

I had to return to 3.4.0 and everything is OK again.

Vladimír

![calendareventsdisappearing](https://user-images.githubusercontent.com/21105807/32557407-5aa0623e-c4a2-11e7-9137-467ffe925d92.png)

**Comment by arshaw** [comment] 2017-11-08 23:18
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by vklaus** [comment] 2017-11-09 05:32
Unfortunatelly no, it's really big project and with private medical data...

But I have new notes:
- events disappear everytime after "triple click" on Prev/Next, not after "double click"
- I use 2 eventSources and seems to me, when I use only one, problem is gone.

Looks like load/clear events are crossing in this fast situation.

**Comment by acerix** [comment] 2019-08-06 18:34
It sounds like this might be the same issue as https://github.com/fullcalendar/fullcalendar/issues/4009 which is fixed now. Would need a way to reproduce this it's still happening.

**Closed by acerix** 2019-08-06 18:34 UTC
Labels: Reproducing
