### ISSUE TITLE
horizontal scrolling in timeGrid views

### ISSUE THREAD

**Issue by babeuloula** [fullcalendar/fullcalendar#3022] opened 2016-01-29 16:00 UTC
Hello, 
Is-it possible to scroll horizontally ?
Thanks

**Comment by dcryan** [comment] 2016-01-29 18:45
@babeuloula, the [views](http://fullcalendar.io/docs/views/Available_Views/), not including the timeline views, do not scroll horizontally. What are you trying to achieve by scrolling horizontally?

**Comment by babeuloula** [comment] 2016-02-01 13:24
Hello,

I use your plugin like this: 
![capture](https://cloud.githubusercontent.com/assets/4849233/12718487/2cf34dd4-c8ef-11e5-93bf-c4678a27fcdf.PNG)

And if I have to add a new column, it will be very small. And I would like to scroll horizontally to get a better view.

Thank you.

**Comment by arshaw** [comment] 2016-02-03 05:00
Timeline view would probably be better suited for this. But I understand why someone might want this.

**Comment by r4j4h** [comment] 2016-02-03 05:21
While not ideal, in the meantime perhaps one approach to getting what you desire is having your table wider than its container, and giving the container `overflow-x: scroll`?

For example, assuming you keep your calendar in some sort of container with the class `.calendar-container`:

```css
.calendar-container {
    width: 300px;
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 500px;
}
```

For the table you want to make sure that you specify WHICH table element. For example, the headers are sometimes nested tables, and you *likely* don't want to affect them. Here, I tried to be specific and grab the closest table from the view, which in this case was a direct descendant from the view element. Please be sure to double check and alter as needed to suit your situation, but I checked the demos for both agenda week view and simple week view and both worked alright and were horizontally scrollable with those rules.

**Comment by babeuloula** [comment] 2016-02-03 10:49
Thanks @r4j4h but with your code I don't see the times and the buttons.

Is it  possible to scroll only on this zone ?
![capture-d ecran-2016-02-03-11 46](https://cloud.githubusercontent.com/assets/4849233/12780071/12d357b8-ca6c-11e5-9def-10e63f87afad.png)

**Comment by r4j4h** [comment] 2016-02-04 05:41
@babeuloula Sure!

```css
.calendar-container {
    width: 300px;
}

.calendar-container .fc-view {
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 600px;
}
```

The container needs to have some sort of fixed width if you want to specify px/em in the inner table that will be scrollable.

If you use %s you could possibly get away with just

```css

.calendar-container .fc-view {
    overflow-x: scroll;
}

.calendar-container .fc-view > table {
    width: 200%;
}
```

At least it works in Chrome.

This allows me:
![1](https://cloud.githubusercontent.com/assets/703007/12806876/2853c202-cac7-11e5-8b3e-af1e976faed2.PNG)
![2](https://cloud.githubusercontent.com/assets/703007/12806877/2b39f93c-cac7-11e5-8b94-30a90be9fe27.PNG)

Is that more like what you are going for?

**Comment by babeuloula** [comment] 2016-02-04 06:14
Hello @r4j4h, thanks you, it's very great. And how I can have always the time on the left when I scroll to the right ?

**Comment by r4j4h** [comment] 2016-02-04 07:58
Hmmm, unfortunately that's harder to do right! Check out [this answer on stackoverflow](http://stackoverflow.com/a/17557830/1347604), I think it will be your best bet, but is a little more complex. It needs a duplicate table and some sync'ing between them to keep scrolling together. I suggest playing with the [demo page](http://jsfiddle.net/xG5QH/6/) from that stackoverflow answer to get used to the technique. Also check out the [FixedColumns DataTable extension](https://datatables.net/extensions/fixedcolumns/) - it uses this technique and you can probably borrow some of its code for syncing vertical scroll amounts.

Also check out the other answers to that stackoverflow question because depending on your situation they may be easier alternatives. For example you might be able to get away with running a [jQuery plugin](http://www.fixedheadertable.com/) over the table to freeze the first column (which is inside the `.fc-time-grid` and can be selected at `td.fc-axis.fc-time.fc-widget-content`).

**Comment by babeuloula** [comment] 2016-02-04 17:49
Ok I will test your fiddle. Thanks

**Comment by gansky-alexander** [comment] 2016-05-13 15:49
Hello, all.
I have problem with horizontal scrolling. I have added recommendation of @r4j4h but i got problem with time axis.
Could someone help me to find solution?

**Comment by flaracca** [comment] 2016-05-23 18:46
I have managed to implement @r4j4h code. As she said, I ha dto check id' names and I have added these lines to fullcalendar.css:
`.fc-view-container {
    width: 1000px;
}

.fc-view-container .fc-view {
    overflow-x: scroll;
}

.fc-view-container .fc-view > table {
    width: 2500px;
}` on line 765.

I am struggling to have the time column fixed. I had implemented the FixedHeaderTable jQuery plugin and had modified fullcalendar.min.js to have a table id set but it isn't working.

Looking to set this straight through CSS, If anyone else comes up wtih a solution...

**Comment by srthakkar** [comment] 2017-05-31 12:23
Any update on this issue? 
@arshaw, when can we expect this feature?

**Comment by espen** [comment] 2017-05-31 12:50
@srthakkar this is an open source project, feel free to make a pull request
> Comments such as +1 or “when will this be ready” will not only receive a penalty in the ranking system, they will spam other watchers of the thread
https://fullcalendar.io/blog/2016/07/renovated-issue-tracker/

**Comment by Jorace** [comment] 2018-01-29 11:32
Just want to add to the discussion, I was searching about how to keep the horizontal scrolling value. Was there any discussion about how to keep the horizontal scroll value?

**Comment by vishaldudhatra** [comment] 2018-02-15 05:40
Hello

I have same issue related horizontal scroll in agenda views. 
[#110](https://github.com/fullcalendar/fullcalendar-scheduler/issues/110#issuecomment-365829019)
Any update related this issue?

Thank you

**Comment by McQuinTrix** [comment] 2018-02-28 21:49
+1

**Comment by laddhadhiraj** [comment] 2018-03-17 09:27
As I look this issue open on 29 Jan 2016, so just thinking if it gets fixed?  we have bought scheduler license but still required this 'horizontal scrolling in Agenda views'  fix... Please let me know if anyone know it's fix.

**Comment by acerix** [comment] 2018-04-10 18:08
Came across this demo using CSS for this that seems to work OK:

https://jsfiddle.net/3gpjjba1/98/

**Comment by jimmylogic** [comment] 2018-06-04 10:04
+1

**Comment by mtuzinskiy** [comment] 2018-08-31 11:34
Any updates on this?

**Comment by mchirlin** [comment] 2018-09-27 04:04
We also have this same requirement.

**Comment by michelerota** [comment] 2018-11-22 16:53
+1

**Comment by richlandhosting** [comment] 2019-05-22 18:46
$(".fc-time-grid > .fc-slats").css('z-index','99999');

I added this to my $().ready(function() or anytime after the calendar is generated.

**Comment by David-Ho** [comment] 2019-10-07 19:32
Hello,
Does anyone know if this feature will be addressed soon or in future release?  

The suggestion or workaround above from previous post does not really work because the time slots does not stay as the horizontal scroll bar moves to the right and the vertical scroll bar is not shown until the container is scrolled horizontally to the end.

Is there any way to have both vertical and horizontal scroll bars shown within the FullCalendar that can handle many resources in resourceTimeGridDay view?  This is a scrolling usability issue for us.

**Comment by JWOverschot** [comment] 2019-10-21 14:59
In what time window can we expect this feature?
@arshaw said in #4819 that it's planed for next major release. When is that expected?
And does anybody know a better workaround than the suggested above?

**Comment by davidGPA** [comment] 2019-10-29 10:31
Hi @arshaw, some news about this feature?
We are really interested in purchasing fullcalendar scheduler license but we have a large number of resources to show in vertical mode which makes horizintal scroll required.
Thanks.

**Comment by di1606** [comment] 2019-11-12 14:35
Someone succeed to fix the first column (time column) in FullCalendar

**Comment by arshaw** [comment] 2020-02-05 05:46
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by prinzdezibel** [comment] 2020-02-05 10:05
Until this feature is implemented properly, you may find the following solution suitable to fix the time column. Note that this solution is imperfect and probably will most likely not work in all browsers:

http://plnkr.co/edit/ozSX424nDT3NmhzB13e4?p=preview

The gist of it is the following CSS:
```
 .fc-view {
    overflow-x: auto;
 }

.fc-view > table {
    min-width: 100%;
    width: 2000px;
 }
      
.fc-time-grid .fc-slats {
    z-index: 4;
    pointer-events: none;
 }
      
.fc-scroller.fc-time-grid-container {
    overflow: initial !important;
 }
      
.fc-axis {
    position: sticky;
    left: 0;
    background: white;
 }
```

**Comment by tsyrya** [comment] 2020-03-10 02:32
@prinzdezibel Your solution is great, thanks. There is a side effect though - the headers stops being "sticky" and disappears when you scroll down. Is there any idea how to fix that? Thanks :)

**Comment by arshaw** [comment] 2020-04-14 05:32
this feature is available in the latest v5 beta. [please see the blog post](https://fullcalendar.io/blog/2020/04/new-ui-features-beta).

You activate it by setting [dayMinWidth](https://fullcalendar.io/docs/v5/dayMinWidth) to a numeric value. You'll also need to have the `@fullcalendar/scrollgrid` premium plugin loaded.

[view a demo](https://fullcalendar.io/docs/v5/dayMinWidth-demo)

**Comment by 13996477276** [comment] 2020-04-14 09:13
@arshaw dear sir,when I use the v5 beta.2, There is a problem with my project. I found the source of the problem is these codes：“import { h, Fragment, BaseComponent, isArraysEqual, RenderHook, buildHookClassNameGenerator, MountHook, ContentHook, createRef, RefMap, findElements, elementClosest, setRef, PositionCache, memoize, greatestDurationDenominator, NowTimer, NowIndicatorRoot, DateComponent, getStickyHeaderDates, getStickyFooterScrollbar, renderScrollShim, ViewRoot, parseFieldSpecs, createPlugin } from '@fullcalendar/core';”
， and this problem is "Uncaught SyntaxError: Unexpected token {";
![image](https://user-images.githubusercontent.com/45160833/79207276-16f95800-7e73-11ea-8723-4ea0203d2249.png).
Could you help me this question?

**Comment by arshaw** [comment] 2020-04-14 15:21
@13996477276 could you please open a new ticket for that? i have a feeling i know what the problem is but i'll answer on a new ticket

**Comment by 13996477276** [comment] 2020-04-15 01:00
@arshaw   dear sir，I submit a new issue,please help me.https://github.com/fullcalendar/fullcalendar/issues/5358

**Comment by kunalahirrao** [comment] 2020-04-26 04:10
How to add a button to fc-axis header

**Comment by arshaw** [comment] 2020-06-22 22:16
released in the [official v5](https://fullcalendar.io/blog/2020/06/v5-official). please see the demo I posted in my previous comment

**Closed by arshaw** 2020-06-22 22:16 UTC
Labels: Accepted, Scrolling, TimeGrid View

**Comment by michalfordonski** [comment] 2022-12-20 08:40
@arshaw Is it possible to set different values for dayMinWidth for different views in version 6? E.g
day: 300, week: 200, month: 200

If so, how?

Currently we have views written like this:

`views: {
            resourceDayGrid: {
                type: 'resourceDayGrid',
                visibleRange: function(currentDate) {
                    let startDate = new Date(currentDate.valueOf());
                    return { start: startDate, end: startDate };
                }
            },
            resourceTimeGridWeek: {
                type: 'resourceTimeGrid',
                duration: { days: 7 },
            },
            resourceDayGridWeek: {
                type: 'resourceDayGrid',
                duration: { week: 1 },
                buttonText: showWeekRD
            },
            resourceTimeGridWeekHour: {
                type: 'resourceTimeGrid',
                duration: { week: 1 },
                buttonText: showWeekRDH
            }
        },`

When I try to add an option in the view declaration (under the lines defining the type) it doesn't work.
