### ISSUE TITLE
Vertical scrollbar is shown if the container has a floating point number as width (IE11)

### ISSUE THREAD

**Issue by kaljak** [fullcalendar/fullcalendar#3444] opened 2016-12-07 09:06 UTC
Since jQuery 3.0.0 a vertical scrollbar is shown if the container of the fullcalender has a floating point number as width.
--> Open http://jsfiddle.net/kaljak/jRFYE/737/ with Internet Explorer 11.

I think the problem is in `function getScrollbarWidths(el)`:
`el.innerWidth()	` did return an integer in earlier jQuery versions. Now it returns a float.

![image](https://cloud.githubusercontent.com/assets/3268945/20961276/94808782-bc64-11e6-9e26-f5961f2cf4f9.png)

Is there any workaround or will this be fixed soon?
Thanks in advance!

**Comment by arshaw** [comment] 2016-12-12 06:25
I've reproduced. Thanks!

**Comment by josephbales** [comment] 2017-01-12 17:53
I came across this same symptom, but for me it seems to be related to whether the calendar has a fixed width or not.  If you set a fixed width the problem goes away:

http://jsfiddle.net/jRFYE/821/

**Comment by arshaw** [comment] 2017-02-14 22:51
Fixed in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

**Closed by arshaw** 2017-02-14 22:51 UTC
Labels: Confirmed, Merged, Scrolling, View Rendering
