### ISSUE TITLE
eventClick on V5 is refreshing the calendar when doing SetState

### ISSUE THREAD

**Issue by phpbits** [fullcalendar/fullcalendar#5519] opened 2020-06-20 17:30 UTC
### Bug Reports
I'm using React and trying to add custom event info popover on `EventClick`. The problem is the calendar is refreshing when setting state. Is there any way to prevent this from happening? Thanks!

**Comment by arshaw** [comment] 2020-06-22 02:59
Though it's hard to know for sure because you didn't post a reduced test case, I believe I came across this bug and fixed it for the [official v5 release](https://fullcalendar.io/blog/2020/06/v5-official).

Could you please get the latest code and verify?

**Comment by phpbits** [comment] 2020-06-22 12:21
@arshaw I'm just setting custom state on `eventClick`

```
eventClick={ ( info ) => {
						this.setState( {
							isDatePickerOpen: false,
						} );
					} }
```

**Comment by phpbits** [comment] 2020-06-22 12:58
Forgot to mention that this isn't happening on version 4. Thanks!

**Comment by Mick89** [comment] 2020-06-22 14:23
I have a similar problem with inserting into a form (php).
```
<form method="post" action="?">
  <div id='calendar'></div>
</form>
```
A click on the buttons in headerToolbar (prevYear,prev,next,nextYear today) will send the form. 
I don't have this problem with version 4.

Thanks!

**Comment by arshaw** [comment] 2020-06-22 19:38
@Mick89 and @phpbits , I think you are describing two different problems. I can't help either of you unless you post a runnable demo:

[runnable demo instructions](https://fullcalendar.io/reduced-test-cases)

Would really appreciate it because the time saved reproducing will be time spent fixing. I'm closing this issue until then.

**Closed by arshaw** 2020-06-22 19:38 UTC
Labels: Reproducing

**Comment by Mick89** [comment] 2020-06-23 04:47
Excuse me.

A click on the buttons in headerToolbar (prevYear,prev,next,nextYear today) will send the form.
I don't have this problem with version 4.

https://codepen.io/Mick89/pen/jOWmMMB

Thanks again!

**Comment by phpbits** [comment] 2020-06-23 11:05
@arshaw Managed to fixed my issue by using `initialEvents` instead of `events` when fetching data.

**Comment by Ben-CA** [comment] 2022-08-24 21:09
> @arshaw Managed to fixed my issue by using `initialEvents` instead of `events` when fetching data.

Thanks so much for posting this solution!
