### ISSUE TITLE
Table selection is not prevented when long pressing to drag events in Safari

### ISSUE THREAD

**Issue by Wolfram-Zell** [fullcalendar/fullcalendar#7441] opened 2023-08-29 10:45 UTC
### Reduced Test Case

https://fullcalendar.io/demos

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

If the calendar is touched/clicked body gets "user-select: none", this does not work on Safari and Safari for iOS.
One solution is to add
```js
el.style.webkitUserSelect = 'none'
```
to `function preventSelection(el: HTMLElement) ` in `/packages/core/src/util/misc.ts`

**Comment by acerix** [comment] 2023-09-04 19:23
I'm not sure what the issue is,  what is the expected/actual behaviour when selecting an event (as visible to the user)?

**Comment by Wolfram-Zell** [comment] 2023-09-05 04:54
On iOS the table will be selected on longer tap, on any Android/LInux/Windows device this is not the case, because while a mouse button is pressed, or the screen is touched `body` gets `user-select: none`. Safari on iOS and MacOS does not support `user-select` and needs the prefix. See Can I use: https://caniuse.com/?search=user-select

**Comment by SlavaGeorgiev** [comment] 2023-09-18 12:38
@acerix please see #7442 as PR which fixes the issue.

**Comment by arshaw** [comment] 2023-09-21 21:42
Merged and fixed in [v6.1.9](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.9). Thanks for the PR! Can you please verify?

**Closed** 2023-09-21 21:42 UTC
Labels: Confirmed, Touch

**Comment by SlavaGeorgiev** [comment] 2023-09-22 08:03
Sure will do, planing a task for next sprint.
