### ISSUE TITLE
Next button won't pass October 17, 2015

### ISSUE THREAD

**Issue by pakerwreah** [fullcalendar/fullcalendar#2900] opened 2015-10-15 15:40 UTC
In the week or day view you cannot go after Oct 17, 2015. It changes the title to "October 17 — 16, 2015" even in the day view and won't show "Saturday", it just goes blank.
If you change to month view you can go to future dates. In the week or day view you can only go to past dates.
I can reproduce this on the official fullcalendar website.

**Comment by espen** [comment] 2015-10-15 15:43
I can't reproduce this. Which browser are you using and which timezone is your computer set to?

**Comment by pakerwreah** [comment] 2015-10-15 15:48
![screen shot 2015-10-15 at 12 46 10](https://cloud.githubusercontent.com/assets/803954/10519110/be59ff94-733a-11e5-93e7-3397aa357207.png)

I can reproduce this on Firefox 40.0.3, Safari 9.0. In Chrome it works (I just figured out)!

**Comment by espen** [comment] 2015-10-15 15:52
Timezone? Can you check if the date and time is correct on your computer?

**Comment by pakerwreah** [comment] 2015-10-15 15:54
Time Zone: America/Sao_Paulo
The date is correct. I tested in every computer here.

**Comment by pakerwreah** [comment] 2015-10-15 16:00
I changed to Time Zone: Arizona UTC-7:00 to make a teste and it worked!
There is some problem with my time zone and fullcalendar.

**Comment by arshaw** [comment] 2015-10-15 20:40
probably the same bug as this: #2711
ill try to come up with a workaround.

**Comment by arshaw** [comment] 2015-10-15 20:41
and maybe related to #2396

in short, it's a native JS `Date` bug that we'll try to workaround somehow

**Comment by arshaw** [comment] 2015-11-21 19:44
I was personally unable to reproduce, but maybe that's because I'm on Safari 8. Will try harder.

<img width="604" alt="screen shot 2015-11-21 at 5 42 58 pm" src="https://cloud.githubusercontent.com/assets/56520/11320185/4b4d7f7c-90e4-11e5-862a-f3f697eb27ce.png">

**Comment by arshaw** [comment] 2015-11-23 10:30
this has likely been fixed in a beta release. please try it out!
https://github.com/fullcalendar/fullcalendar/releases/tag/v2.5.0-beta2

**Comment by arshaw** [comment] 2015-11-30 09:46
fixed in [v2.5.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.5.0)

**Closed by arshaw** 2015-11-30 09:46 UTC
Labels: Status-Reproducing
