### ISSUE TITLE
eventTimeFormat is not applied to print view

### ISSUE THREAD

**Issue by laoneo** [fullcalendar/fullcalendar#5138] opened 2019-11-19 08:30 UTC
Printing the agenda view adds AM/PM to the times, even when a different format is used. It can be reproduce, when you print your [demo example](https://fullcalendar.io/#demos) with the week view selected, the times will be displayed with AM/PM, but the web page is not using it.
Had a quick look on the code, but couldn't identify the cause, so I'm reporting just the issue without a pr.

Here a screenshot of the page in the browser:
![image](https://user-images.githubusercontent.com/251072/69129278-541d1200-0aae-11ea-8e6f-dd85008dc5db.png)

And here one of the print as file:
![image](https://user-images.githubusercontent.com/251072/69129353-73b43a80-0aae-11ea-9a80-bd20e3460e3a.png)

**Comment by acerix** [comment] 2019-11-19 21:09
It seems the issue is that `eventTimeFormat` does not affect the print view:

https://codepen.io/acerix/pen/yLLZEmZ?editors=001

As a workaround, you could turn off `displayEventTime` and add the time manually from eventRender.

**Comment by laoneo** [comment] 2019-11-20 07:14
Thanks for the workaround.

**Comment by arshaw** [comment] 2020-06-29 20:36
this should be fixed in v5

**Closed by arshaw** 2020-06-29 20:36 UTC
Labels: Confirmed, Date/Time Rendering, Print-View
