### ISSUE TITLE
BUG - renderEvent (method) doesn't update the Calendar UI when Calendar view mode is in agendaWeek or agendaDay

### ISSUE THREAD

**Issue by tonykchan** [fullcalendar/fullcalendar#3251] opened 2016-06-27 18:11 UTC
BUG - renderEvent (method) doesn't update the Calendar UI when Calendar view mode is in agendaWeek or agendaDay. Adding new events using renderEvent (method) when in Month view, seems to behave properly.

If you check out the JSBin below, you'll notice that when in month view mode, I can click on each day on the month and an event with "test" title is rendered immediately on the 1st click.

If you try the same thing in agendaWeek or agendaDay view mode and start clicking on timeslots, the "test" title doesn't get rendered on the 1st click. It only seems to refresh/update on the 2nd click.

JSBin: http://jsbin.com/jahahowogo/edit?js,output

#3241

**Comment by arshaw** [comment] 2016-06-28 07:07
this root cause of this issue is one-in-the-same with #3241, so I'm going to close this one.

**Closed by arshaw** 2016-06-28 07:07 UTC
