### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by ebiton-eig** [fullcalendar/fullcalendar#6869] opened 2022-05-31 09:15 UTC
### Checklist

Please mark these items with an [x]

  - [x] I've already searched through [existing tickets](https://fullcalendar.io/issues)
  - [x] Other people will find this feature useful

### Feature Description

Support Angular 14

Build fail with Angular 14 RC2 :

```node
./node_modules/@fullcalendar/common/main.css:4:0 - Error: Module parse failed: Unexpected token (4:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* classes attached to <body> */
| /* TODO: make fc-event selector work when calender in shadow DOM */
> .fc-not-allowed,
| .fc-not-allowed .fc-event { /* override events' custom cursors */
|   cursor: not-allowed;

./node_modules/@fullcalendar/daygrid/main.css:2:0 - Error: Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
> :root {
|   --fc-daygrid-event-dot-width: 8px;
| }

./node_modules/@fullcalendar/list/main.css:2:0 - Error: Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
> :root {
|   --fc-list-event-dot-width: 10px;
|   --fc-list-event-hover-bg-color: #f5f5f5;

./node_modules/@fullcalendar/timegrid/main.css:6:0 - Error: Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| */
| 
> .fc-v-event { /* allowed to be top-level */
|   display: block;
|   border: 1px solid #3788d8;
```

**Comment by mbx2015** [comment] 2022-06-03 10:06
I have the same issue as @ebiton-eig after updating from angular 13 to 14.

**Comment by drony** [comment] 2022-06-04 12:53
same on me

**Comment by itcozum** [comment] 2022-06-04 21:10
ditto

**Comment by KapilSachdev** [comment] 2022-06-06 09:27
@acerix  Any thoughts on this?
It would also be helpful if there is some workaround until we have a fix available with us.

**Comment by Tenvan** [comment] 2022-06-08 06:12
is there an switch in Angular 14, to reactivate CSS-Imports ? 
as temp workaround...

**Comment by sha-N** [comment] 2022-06-09 10:03
for those who come here like me,

one workaround is to add following to angular.json's styles array

"styles" : [
...
"./node_modules/@fullcalendar/common/main.css",
"./node_modules/@fullcalendar/daygrid/main.css",
"./node_modules/@fullcalendar/timegrid/main.css",
"./node_modules/@fullcalendar/list/main.css",
...
],

**Comment by Tenvan** [comment] 2022-06-09 14:05
that works, thx :+1:

**Comment by KapilSachdev** [comment] 2022-06-09 14:30
@sha-N Thank you.
The solution provided works.

It is interesting to note that the application I am using has CSS already added in `angular.json` under `styles` array except the `node_modules/@fullcalendar/common/main.css`.
So for the issue to resolve, it looks like all these above mentioned CSS must be present.

**Comment by stewieoO** [comment] 2022-06-28 17:23
Does anyone have a workround for ssr builds?
You can't add the styles array to the configuration when the builder type is `@angular-devkit/build-angular:server`
I guess i have to wait for a fix in this package?

**Comment by acerix** [comment] 2022-06-30 20:03
Sorry I missed this issue earlier.  This has also been reported in the Angular repo so I'll close this as a duplicate since the issue is specific to Angular.  

https://github.com/fullcalendar/fullcalendar-angular/issues/403
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2022-06-30 20:03 UTC
