### ISSUE TITLE
getEventSources (equiv getResources)

### ISSUE THREAD

**Issue by rupertbg** [fullcalendar/fullcalendar#3068] opened 2016-02-27 11:36 UTC
I am optimising code i've written against FullCalendar and have found that having a feature equivalent to getResources for Event Sources would be extremely useful.

I have numerous Event Sources and would like to compare the length of the array in memory against the array used to populate the calendar at init. This would allow faster dynamic changes to event sources.. I have a different number of resources to sources therefore cannot use getResources in this scenario.

**Comment by arshaw** [comment] 2016-03-06 23:48
duplicate of #2433

**Closed by arshaw** 2016-03-06 23:48 UTC
