### ISSUE TITLE
Performance - Page Not Responding for huge number of events

### ISSUE THREAD

**Issue by psudheendra** [fullcalendar/fullcalendar#4395] opened 2018-11-30 07:32 UTC
We are trying to create recurring events 
Use Case:
Create 1 minute duration event for every minute = Total 1440 events per day
The same need to be copied to duration for 3 years

Issues:
Both creating those many events and Rendering the same on full calendra are taking huge time and page becomes non responsive

Kindly help us how to handle this scenario

**Comment by acerix** [comment] 2018-11-30 21:51
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Possible duplicate of https://github.com/fullcalendar/fullcalendar/issues/2524

**Comment by ImSirDieALot** [comment] 2018-12-04 20:55
Following the thread. I have similar issue as well. We are using the full calendar for scheduling stuff of our employees. Calendar works fine for 7-12 days of recurring schedules. But anything longer, page goes into non-responsive. I am currently trying to re-create the issue to a stripped down demonstration.

**Comment by psudheendra** [comment] 2018-12-05 01:36
> Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
> 
> Possible duplicate of #2524

I am creating a working sample. Will be posting sample in couple of days.

**Comment by psudheendra** [comment] 2018-12-10 11:43
Please check the below stripped down version.

https://jsfiddle.net/shreyams9107/cpwk2vag/209/

Inputs:
Start Date: 2018/12/10
End Date: 2020/12/10
Repeat Interval: 1
Duration: 1

Click on Add Events and browser hangs.
![pagenotresponding](https://user-images.githubusercontent.com/18395678/49730617-e7df3f00-fc9e-11e8-8e0c-82739ee61215.jpg)

**Comment by acerix** [comment] 2018-12-10 22:33
Thanks for the demo, it also freezes for me, but the example is adding over a million events so it makes sense that would take lots of time and memory so I'm not sure it's an issue with the calendar.  It would help if you can reduce the test case to a minimal example.

You could load events from a JSON feed instead, that way the calendar only loads the events it needs to display instead of all the events at once.  

https://fullcalendar.io/docs/resources-json-feed

**Comment by psudheendra** [comment] 2018-12-12 03:07
Even if we do for 7 days, in Timetable view, it takes minutes.
Browser freezes.
Cant we reduce 7 days events to less than 1 minute?

**Comment by acerix** [comment] 2018-12-12 22:33
Sounds like the same issue in https://github.com/fullcalendar/fullcalendar/issues/2524 , takes several seconds to render 1500 events

**Comment by acerix** [comment] 2019-08-08 19:38
I made an updated demo for v4:

https://codepen.io/acerix/pen/dxezGq

The performance seems fine with 1000 events now.  It gets slow around 5000 events but I think that is expected and it's not useful to display that many events at once.

**Closed by acerix** 2019-08-08 19:38 UTC
Labels: Event Rendering, Reproducing

**Comment by mutasemAHmad** [comment] 2020-09-16 15:12
@acerix Thank you bro <3
