### ISSUE TITLE
EventResize not working after upgrade to v4.0.0-alpha

### ISSUE THREAD

**Issue by korengal** [fullcalendar/fullcalendar#4159] opened 2018-04-24 13:51 UTC
Hi,
The eventResize  (https://fullcalendar.io/docs/eventResize) stopped working after the update.

I'm using editable: true in the calendar options.

Do I need to change something in the code to support it on the new version?

thanks.

**Comment by arshaw** [comment] 2018-04-25 16:17
thanks for the report. i'll look into it

**Comment by korengal** [comment] 2018-04-25 21:59
I'm glad this help, please check the drop function too. (https://fullcalendar.io/docs/droppable)


thanks.

**Comment by arshaw** [comment] 2018-12-26 05:32
Hi @korengal. I can't recreate this. I have lots of tests for `eventResize` and they are passing in the latest alpha version of v4.

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Please recreate with the latest version of v4.

Closing this ticket in the meantime.

**Closed by arshaw** 2018-12-26 05:32 UTC
Labels: Reproducing
