### ISSUE TITLE
localized format tokens, in combo with basic ones, wrong title

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar#3898] opened 2017-10-26 19:31 UTC
When a localized format string like `ddd` is combined in the same string with a normal one like `ddd`, the range formatting double-displays the date.

```
  $('#calendar').fullCalendar({
    titleFormat: 'ddd, ll'
   });
```

Will incorrectly display "Thu, Oct 26, 2017 – Oct 26, 2017"

Recreation: https://codepen.io/arshaw/pen/EbYNQg?editors=0010

**Comment by acerix** [comment] 2019-09-19 19:21
Duplicate of #3645

**Closed by acerix** 2019-09-19 19:21 UTC
Labels: Confirmed, i18n
