### ISSUE TITLE
Horizontal Time Selection 

### ISSUE THREAD

**Issue by riula** [fullcalendar/fullcalendar#4208] opened 2018-06-06 22:55 UTC
I apologize if something like this has been posted, but I scoured the request list and didn't find anything quite like this.

I'm looking to streamline event creation in hopes of having the events represent free / busy time. Ultimately what I am looking for is something like this: https://deepskyr.github.io/

Currently you can select time across a week, but it includes ALL time in between, where i'd prefer it be bound to the area covered by a selection. 

Thanks!

**Comment by acerix** [comment] 2018-06-07 17:48
Since that example is what you need, are you looking to have it added as a new feature?

**Comment by riula** [comment] 2018-06-07 19:28
Yeah. I am not the author of that particular example, I just found it while doing a search. My hope is that its something that can become part of fullcalendar / scheduler. I am currently using a very old forked version and would like to move to the newer paid version of scheduler.

**Comment by lwhken** [comment] 2018-11-06 23:12
Possible duplicate for issue #4119 ?

**Comment by acerix** [comment] 2018-11-06 23:34
Yes, thanks for pointing that out
Duplicate of #4119

https://github.com/fullcalendar/fullcalendar/issues/4119
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by acerix** 2018-11-06 23:34 UTC
Labels: Discussing, Event Interaction, Selection
