### ISSUE TITLE
extentedProps coming from Google Calendar not accessible in eventRender

### ISSUE THREAD

**Issue by rougeth** [fullcalendar/fullcalendar#5081] opened 2019-10-15 12:58 UTC
Hi everyone! :)

First of all, thanks for the awesome project. I was able to quickly create a full calendar page integrated with Google Calendar even though I know just a little bit of Javascript.

I created a calendar for Python Brasil conference that you can see here: https://2019.pythonbrasil.org.br/grade/

The only issue I couldn't find out a solution is that I have some properties coming through `extendedProps` from Google Calendar API:

![Screenshot 2019-10-15 at 13 52 28](https://user-images.githubusercontent.com/431892/66833092-18dd6f80-ef53-11e9-8ba8-fa6b974b9d69.png)

I'd like to access this data in the `eventRender` callback, but when I log the content of it, the information is not there:

![Screenshot 2019-10-15 at 13 56 55](https://user-images.githubusercontent.com/431892/66833401-ae78ff00-ef53-11e9-956b-ffeaf5a36911.png)

```js
eventRender: function(info) {
    console.log(info);
},
```

Apperantly, FullCalendar consider `location` and `description` as extendedProps, but no other property. Am I doing something too wrong here? Thanks!

**Comment by rougeth** [comment] 2019-10-15 13:24
I think this is what I was looking for: https://github.com/fullcalendar/fullcalendar/pull/4123/files. But aparently this PR is not valid anymore.

**Comment by acerix** [comment] 2019-10-15 22:56
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

The PR you mentioned was merged, so it should be working.

**Closed by acerix** 2019-10-15 22:56 UTC

**Comment by rougeth** [comment] 2019-10-15 22:59
@acerix opened a PR with the fix. The PR merged was refactored and removed (couldn't find why). https://github.com/fullcalendar/fullcalendar/pull/5083
