### ISSUE TITLE
Select function on touch devices v.2.7.beta

### ISSUE THREAD

**Issue by sparh** [fullcalendar/fullcalendar#3110] opened 2016-04-01 16:16 UTC
Hello and thanks for this beta.

I have tested your demo and the Select function is not fired on touch devices. http://jsbin.com/zigawafoya/edit?output

When selecting a date range you should have an alert box but it does not work on touch devices.

Hope this helps

**Comment by arshaw** [comment] 2016-04-20 04:11
http://output.jsbin.com/pozeginowa

**Comment by arshaw** [comment] 2016-04-20 04:32
I tested on the following:

```
iPad (4th generation, late 2012)
iOS 8.2
Mobile Safari 8

Galaxy Tab A
Android version 5.0.2
Chrome version 49.0.2623.105
```

and was unable to reproduce the problem. I was able to get the select callback to fire every time.

Could you please post detailed information on your device/os/browser like I did? Any other preconditions to recreating the bug that we should know about? Closing until a response is given.

**Closed by arshaw** 2016-04-20 04:32 UTC
Labels: Status-Reproducing

**Comment by sparh** [comment] 2016-04-20 06:59
Hi sorry for this, the select event is fired after a long press and I was not aware about this.
v2.7 is awesome

**Comment by arshaw** [comment] 2016-04-22 04:01
cool. fyi `longPressDelay` can control the delay
