### ISSUE TITLE
addEventSource/removeEventSource during jqui drag prevents event drop

### ISSUE THREAD

**Issue by kmukku** [fullcalendar/fullcalendar#3196] opened 2016-06-03 11:10 UTC
Hi!

I'm not sure if this is a bug or not supported feature, but at least it's something that needs documentation. 

I'm trying to highlight preferred time for dragged event using background event, but it seems to disable event drop.

See following jsfiddle as an example:
https://jsfiddle.net/kmukku/5Lonv2uw/

I already made SO question of this too but it hasn't got much attention. Anyone knows how to achieve this kind of behavior?

**Comment by arshaw** [comment] 2016-06-04 06:48
Hello!

this part of the code is essentially making a zero-duration event, because the start and end times are the same:
```
	        window.aim = [{
	          start: new Date(),
	          end: new Date(),
            rendering: 'background'
	        }];
```

**Comment by kmukku** [comment] 2016-06-05 11:38
Hi @arshaw!

And first of all thanks for fullcalendar. 

Bact to the issue. Zero duration event had nothing to do with issue. If you try out jsFiddle above you can see that you can't drag and drop events to calendar. That's the issue. 

Background event highlighting works just fine. Please consider re-opening the issue.

**Comment by arshaw** [comment] 2016-06-05 20:37
ok now i understand. strange that addEventSource/removeEventSource during a drag of a jquery-ui draggable cancels the drag.

i was able to reproduce this with my mouse, so i don't think it's touch-specific.

**Comment by arshaw** [comment] 2020-06-24 15:27
this is almost definitely fixed with v5. if not, please supply an updated [reduced test case](https://fullcalendar.io/reduced-test-cases)

**Closed by arshaw** 2020-06-24 15:27 UTC
Labels: Confirmed, Event DnD/Resize, Event Model
