### ISSUE TITLE
Drag and Drop iOS scrolling

### ISSUE THREAD

**Issue by grajan** [fullcalendar/fullcalendar#3403] opened 2016-11-02 13:53 UTC
When dragging and dropping on iOS the page scrolls along with the drag motion, making it impossible to drag an event from one week to another in the week view (in _fullcalendar.io_)

The issue was opened previously under: [#3367](https://github.com/fullcalendar/fullcalendar/issues/3367)

**Note: The issue is visible only on iOS 10.1 (Tested on both simulator and device)**
It is functioning perfectly fine on 9.3.

![Uploading iOS9.3.gif…]()
![Uploading iOS10.1.gif…]()

**Comment by arshaw** [comment] 2016-11-09 00:59
@grajan if you post a video, could you please do it here?

**Comment by grajan** [comment] 2016-11-10 06:33
@arshaw For some reason, I can't attach the video (tried .zip and .gif) to either the issue or this comment. If you can provide me your email I can send it as an attachment.

**Comment by arshaw** [comment] 2016-11-17 08:35
@grajan if you could email me with the alias "arshaw" and then concatenate "at" "fullcalendar.io" as the domain, that is the email you can send a video to. thanks!

**Comment by grajan** [comment] 2016-11-17 12:41
@arshaw I hope you got my mail.

**Comment by arshaw** [comment] 2016-12-03 00:27
@grajan i did not receive it. my email is arshaw--attt---fullcalendar.io

what is your email?

**Comment by arshaw** [comment] 2017-01-03 05:12
I've successfully recreated this in iOS 10. thanks **leoenmirjam** for the video over email.

**Comment by meorfi** [comment] 2017-02-09 14:50
Hi @arshaw , I have a drag&drop issue on my iPad in safari browser.. Cannot drag&drop an event because the entire calendar is scrolling / moving.

According to the progress registered here, a fix was pushed [fix iOS 10 touch interaction via GlobalEmitter (#3403)](https://github.com/fullcalendar/fullcalendar/commit/488107744c78da76552f916daa2d18c78476f591)

The fix will available to use via npm  just after next-release (3.1.1 (right? )) will be published.
Is it a long path until next release ? :)

**Comment by arshaw** [comment] 2017-02-10 02:17
@meorfi yes, i will attempt to release this weekend

**Comment by meorfi** [comment] 2017-02-13 11:05
@arshaw Great! Thanks :)

**Comment by captain-planet** [comment] 2017-02-13 11:36
Wow....talk about timely!  I'm experiencing this issue too so this fix will be fantastic.  Congrats on a great plugin.

**Comment by arshaw** [comment] 2017-02-14 22:51
Fixed and released in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

**Closed by arshaw** 2017-02-14 22:51 UTC
Labels: Confirmed, Merged, Touch

**Comment by captain-planet** [comment] 2017-02-15 19:54
Thanks for this.  I can confirm it works.

A quick question though: when using in a lightbox, is there a way to stop the lightbox from scrolling vertically when you hold the finger down?  Thanks.

**Comment by arshaw** [comment] 2017-02-16 07:13
@captain-planet could you open up a new ticket for that, with a [Reduced Test Case](https://fullcalendar.io/wiki/Reduced-Test-Cases/) ?

**Comment by captain-planet** [comment] 2017-02-16 08:41
Thanks - have done.  Please see here: https://github.com/fullcalendar/fullcalendar/issues/3533
