### ISSUE TITLE
"More" shows on days with less events than dayMaxEvents

### ISSUE THREAD

**Issue by nvthuong11** [fullcalendar/fullcalendar#6187] opened 2021-03-08 10:13 UTC
### Reduced Test Case
https://codepen.io/thuonnv/pen/vYyVKXQ

### Bug Description
I've configured: dayMaxEvents: true and dayMaxEvents: 3
But some the day have total events less than 3, always show "more"

### Screenshots
http://prntscr.com/10g0c7r

**Comment by acerix** [comment] 2021-03-08 17:29
Thanks, confirmed.  I reduced the events and updated to newest but also get the same:

https://codepen.io/acerix/pen/NWbOaVZ?editors=001

**Comment by nvthuong11** [comment] 2021-03-09 02:17
Hi Acerix,

Thank you for confirmed,
Pls, help me fix it in the next version.

Thank you so much!

**Comment by arshaw** [comment] 2021-03-24 16:09
This is by design: if the event is put into the +more link on Mar 19th, it will remain that way for subsequent days. I understand this is usually not desired behavior.

We need to come up with a better API to control this. Or a better default behavior.

@acerix, haven't there been other tickets about this? I'm having trouble finding them.

**Comment by acerix** [comment] 2021-03-24 17:44
I think there was a similar issue but I couldn't find any either, may have been closed.

**Comment by nvthuong11** [comment] 2021-03-25 02:45
https://codepen.io/acerix/pen/NWbOaVZ?editors=0010
I think the 20th and 21st shouldn't show more because it has only one event. So this is an error that needs fixing.

**Comment by arshaw** [comment] 2021-05-12 02:37
This has fixed released in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

repro: https://codepen.io/arshaw/pen/YzZwKoE?editors=0010

**Closed by arshaw** 2021-05-12 02:37 UTC
Labels: Discussing, Event More/Popover
