### ISSUE TITLE
Typescript errors with CalendarListeners when building with "npx tsc"

### ISSUE THREAD

**Issue by berekuk** [fullcalendar/fullcalendar#5446] opened 2020-05-24 14:41 UTC
I'm getting these errors on a project with `"skipLibCheck": false` enabled.

Tracking down the error lead me to `RefinedOptionsFromRefiners` definition.
(I think the `never` branch of `extends` check in it leads to the value being optional, but I might be wrong here, and I don't understand the relevant code well enough to send the PR.)

```
node_modules/@fullcalendar/common/main.d.ts:531:66 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.
  Property 'datesDidUpdate' is incompatible with index signature.
    Type '((arg: { view: ViewApi; }) => void) | undefined' is not assignable to type '(...args: any[]) => any'.
      Type 'undefined' is not assignable to type '(...args: any[]) => any'.

531     constructor(execFunc: ScrollRequestHandler, emitter: Emitter<CalendarListeners>, scrollTime: Duration);
                                                                     ~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:860:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

860     emitter: Emitter<CalendarListeners>;
                         ~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:901:116 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>[ListenerName]' does not satisfy the constraint '(...args: any) => any'.
  Type '((arg: { view: ViewApi; }) => void) | ((arg: { view: ViewApi; }) => void) | ((arg: EventClickArg) => void) | ((arg: EventHoveringArg) => void) | ... 10 more ... | undefined' is not assignable to type '(...args: any) => any'.
    Type 'undefined' is not assignable to type '(...args: any) => any'.

901     protected trigger<ListenerName extends keyof CalendarListeners>(handlerName: ListenerName, ...args: Parameters<CalendarListeners[ListenerName]>): void;
                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:1075:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

1075     emitter: Emitter<RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>>;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:1488:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

1488     emitter: Emitter<CalendarListeners>;
                          ~~~~~~~~~~~~~~~~~


Found 5 errors.
```

**Comment by acerix** [comment] 2020-05-25 22:03
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue? Would really appreciate it because the time saved reproducing will be time spent fixing.

I tested the example typescript project, adding `"skipLibCheck": false` in the tsconfig.json compilerOptions and get no error.

https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/typescript-scheduler

**Comment by berekuk** [comment] 2020-05-26 01:14
Huh. That's weird, because I'm able to reproduce this issue with the example project too (even without `skipLibCheck`, which is false by default anyway).

```
$ git clone git@github.com:fullcalendar/fullcalendar-example-projects.git
$ cd fullcalendar-example-projects/typescript-scheduler
$ git checkout v5
$ npm i
$ npx tsc
```

Output:
```
node_modules/@fullcalendar/common/main.d.ts:531:66 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.
  Property 'datesDidUpdate' is incompatible with index signature.
    Type '((arg: { view: ViewApi; }) => void) | undefined' is not assignable to type '(...args: any[]) => any'.
      Type 'undefined' is not assignable to type '(...args: any[]) => any'.

531     constructor(execFunc: ScrollRequestHandler, emitter: Emitter<CalendarListeners>, scrollTime: Duration);
                                                                     ~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:860:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

860     emitter: Emitter<CalendarListeners>;
                         ~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:901:116 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>[ListenerName]' does not satisfy the constraint '(...args: any) => any'.
  Type '((arg: { view: ViewApi; }) => void) | ((isLoading: boolean) => void) | ((arg: DateSelectArg) => void) | ((arg: DropArg) => void) | ((arg: { view: ViewApi; }) => void) | ... 19 more ... | undefined' is not assignable to type '(...args: any) => any'.
    Type 'undefined' is not assignable to type '(...args: any) => any'.

901     protected trigger<ListenerName extends keyof CalendarListeners>(handlerName: ListenerName, ...args: Parameters<CalendarListeners[ListenerName]>): void;
                                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:1075:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

1075     emitter: Emitter<RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>>;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/common/main.d.ts:1488:22 - error TS2344: Type 'RefinedOptionsFromRefiners<Required<CalendarListenerRefiners>>' does not satisfy the constraint '{ [eventName: string]: (...args: any[]) => any; }'.

1488     emitter: Emitter<CalendarListeners>;
                          ~~~~~~~~~~~~~~~~~

node_modules/@fullcalendar/timeline/main.d.ts:3:23 - error TS2307: Cannot find module './vdom' or its corresponding type declarations.

3 import { VNode } from './vdom';
                        ~~~~~~~~


Found 6 errors.
```

I tried this on two different hosts, including a newly-installed Ubuntu 20.04.

**Comment by TheBigAleski** [comment] 2020-05-26 13:18
We just encountered the same issue as @berekuk 
We worked around it by editing `@fullcalendar\timeline\main.d.ts` :
* replaced `VNode$1` by `VNode` in the whole file
* removed line 3 `import { VNode } from './vdom';`

Everything seems to work fine since then.
B/R

**Comment by acerix** [comment] 2020-05-26 19:41
Thanks for the details, I also get that error by running `npx tsc` but it works fine with `npm run build`.

**Comment by arshaw** [comment] 2020-05-27 02:09
this is fixed in beta4. could you verify?

**Comment by TheBigAleski** [comment] 2020-05-27 14:10
The error below was fixed in beta.4
```
node_modules/@fullcalendar/timeline/main.d.ts:3:23 - error TS2307: Cannot find module './vdom' or its corresponding type declarations.
```
Thanks

**Closed** 2020-06-05 02:36 UTC
Labels: Discussing, TypeScript, Weird Environment
