### ISSUE TITLE
Integer Date object is treated an unix time in milliseconds but example in docs shows it in seconds

### ISSUE THREAD

**Issue by Novelz** [fullcalendar/fullcalendar#5162] opened 2019-11-28 17:53 UTC
Hi there, I think there is an issue with the date format in the events array.
If I create an array of events, with json feed or a simple array, and for some of them I use a Unix date format these events are not showing up in the calendar.

In the docs ([link](https://fullcalendar.io/docs/events-json-feed#dates)) it's stated that you can use both format but as you can see in [this CodePen](https://codepen.io/Novelz/pen/MWWNzKp?editors=0010) the last 2 elements of the array with a Unix date are not visible.

The pen it's a copy of your template for standard reporting.
I'm currently using Firefox with Fullcalendar V4.3.1

**Comment by acerix** [comment] 2019-11-28 22:08
Thanks, confirmed. 

It works if you specify it in milliseconds:

https://codepen.io/acerix/pen/YzzmgKR?editors=0010

I believe it's intended to be ms now, but in version 3 it was in seconds, so the docs you mentioned just need to be updated.

**Comment by Novelz** [comment] 2019-11-29 08:55
Oh great! Didn't even think to try ms, thank you for the clarification.

**Comment by arshaw** [comment] 2020-07-28 15:19
fixed in docs: https://fullcalendar.io/docs/events-json-feed

**Closed by arshaw** 2020-07-28 15:19 UTC
Labels: Confirmed, Docs, Event Model
