### ISSUE TITLE
Unable to correctly format title of week view according to Czech rules

### ISSUE THREAD

**Issue by tomasklima** [fullcalendar/fullcalendar#3486] opened 2017-01-16 22:21 UTC
Correct format of single date in Czech language is: `D. M. YYYY` (e.g. 15. 1. 2017). When a range needs to be written the correct format is `D. M. YYYY - D. M. YYYY` or `D. M. - D. M. YYYY` or `D. - D. M. YYYY`. The dot after day respectively month **must be typed** even if it is not followed by month respectively year. Examples: 15. 1. 2017 - 21. 1. 2017, 15. 1. - 21. 1. 2017, 15. - 21. 1. 2017.

In the Fullcalendar I tried to format title for week view:

```
views: {
  week: {
    titleFormat: 'D. M. YYYY'
  }
}
```

But I got this output: '15 - 21. 1. 2017', what is incorrect according to Czech language rules because missing '.' after '15'. Dot is not a separator (like '/' in English styled dates) but must be typed whenever month or date in month are mentioned.

JSBin: http://jsbin.com/kalicabepi/edit?js,output

**Comment by tomasklima** [comment] 2017-01-16 22:53
I figured out a workaround how to add missing dot - set `titleRangeSeparator`:

```
views: {
  week: {
    titleFormat: 'D. M. YYYY',
    titleRangeSeparator: '. - '
  }
}

```

**Comment by arshaw** [comment] 2017-01-17 00:45
confirmed. thanks. this is because range formatting is attempting to be clever.

**Comment by rhafner** [comment] 2017-01-31 13:53
Hi Adam, 
the same is valid for German. I need a "." after a day or month digit.
The workaround of @tomasklima works except when the range reaches across the end of a year.

Example: "26. 12. 2016. - 1. 1. 2017"
With the workaround I get a period after the year which is not correct.

Maybe you could add a property to set different separators. One when dates have chunks in common and one when they are completely different.

Thanks in advance,
Ralf

**Comment by tomasklima** [comment] 2017-01-31 14:14
Yes, you are right, @rhafner. I've figured it out last week.

Ralph's suggestion is appropriate. Hint for properties design: In fact, the slash is used as a separator but the dot as a suffix to date and month part. In the full form (with year) it doesn't matter - 31/1/2017 vs 31.1.2017. But when the year is omitted, the usage is clear - 31/1 vs 31.1.

**Comment by arshaw** [comment] 2017-02-14 22:52
Fixed in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

**Closed by arshaw** 2017-02-14 22:52 UTC
Labels: Confirmed, i18n, Merged

**Comment by rhafner** [comment] 2017-07-20 10:24
Unfortunately the changes only fix the issue partially. Now I get the following cases right:

04. – 10.12.2016
27.12.2015 – 02.01.2016

But when a there is a switch of months the '.' is missing:
27.11 – 03.12.2016

I expect this: 27.11. – 03.12.2016 

Am I missing something?

JS Bin: http://jsbin.com/dimisapete/1/edit?js,output

**Comment by arshaw** [comment] 2017-08-07 16:16
@rhafner i moved your bug report here: https://github.com/fullcalendar/fullcalendar/issues/3781
