### ISSUE TITLE
Event function delays can crash calendar during initial view switching

### ISSUE THREAD

**Issue by lesilent** [fullcalendar/fullcalendar#3778] opened 2017-08-03 06:31 UTC
It seems that error can result if the events function doesn't return the events array prior to the view being switched when the calendar is first initialized.  Firefox throws "TypeError: events is null" in the `renderEvents` function.  This can occur when (ajax) functions are specified through either the `events` or `eventSources` options.  In the following example, a events functions is used with a 5 second delay before it calls the callback function. If you toggle between the views prior to the 5 seconds, the error results because it's assuming there are events and trying them when none have been loaded yet:

[https://jsfiddle.net/y1a7s788/3/](https://jsfiddle.net/y1a7s788/3/)

However, when addEventSources is used instead and views are switched, no such error results:

[https://jsfiddle.net/y1a7s788/4/](https://jsfiddle.net/y1a7s788/4/)

**Comment by arshaw** [comment] 2017-08-10 03:06
thanks @lesilent. I think this is a duplicate of this issue:
https://github.com/fullcalendar/fullcalendar/issues/3689
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2017-08-10 03:06 UTC
