### ISSUE TITLE
refetching events should keep event popover open

### ISSUE THREAD

**Issue by drelfien** [fullcalendar/fullcalendar#3958] opened 2017-11-29 09:13 UTC
Default behavior: popover that appears from `eventLimitClick` button, let's call it `.fc-more-popover`, automatically closes when user clicks elsewhere. Would it be possible to control this? I noticed there's an `autoHide` option in the source.

Current use case: I'm adding event detail popovers displaying custom data / actions for each event, and I need to be able to close it. This works fine for non-hidden events, but those attached in the `.fc-more-popover` cannot close when the popover disappears.

I'm not 100% certain this is the solution to my issue, but I believe Bootstrap needs to attach a popover to a triggering element. So when `.fc-more-popover` disappears, the triggering element for the event detail popover located inside won't close.

**Comment by acerix** [comment] 2017-11-30 03:15
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't see a way to set `autoHide` besides editing the source, but disabling that would stop the popover from closing by clicking outside of it.  Are you asking to have that option exposed?

**Comment by drelfien** [comment] 2017-11-30 05:59
Here's a fiddle: https://jsfiddle.net/99mrk6pc/2/

Here's what I did:
1. For each event, define a popover that will be triggered on click.
2. Each popover contains a button that closes said popover when clicked.

What happens:
- When you click the "+2 more" button, then click on an event inside that `.fc-more-popover`, you can't close any custom popover using the close button.
- Opened popovers cannot close once `.fc-more-popover` disappears.
- The only way to close the custom popover generated by an event inside `.fc-more-popover` is to click on the triggering event again (if in the popover options `trigger` is set to `click`).

**Comment by acerix** [comment] 2017-11-30 16:42
Thanks for the demo, I see the issue now.

Looks like the issue is `.popover('hide')` getting called on the wrong element, I got it working by using the parents of the close button:

https://jsfiddle.net/99mrk6pc/3/

**Comment by drelfien** [comment] 2017-12-01 05:52
Thanks for that catch, though I'm still wondering if there's a way to not automatically hide that `.fc-more-popover` and close it only with its (x) button.

**Comment by freddyouellette** [comment] 2018-07-19 14:21
@acerix This is still an issue, though I might have it slightly differently - The 'refetchEvents' call will close the popover. It'd be nice if we even just had a customizable eventLimitClose event, or if the popover didn't close when refetching.

See fiddle: 

https://jsfiddle.net/px2zm4gc/

**Comment by alejocba04** [comment] 2018-12-19 16:18
Can someone makes this?
I cant make popover dont close when renderEvent happens

**Comment by fabrizzios** [comment] 2021-02-06 03:49
i am trying to refreshing events, and keep the eventlimit popover open, did someone can do this? thanks

**Comment by harsha8020** [comment] 2021-03-02 11:58
> Thanks for that catch, though I'm still wondering if there's a way to not automatically hide that `.fc-more-popover` and close it only with its (x) button.

is there any way to remove auto hide ?

**Comment by arshaw** [comment] 2021-05-12 03:30
The issue of the popover closing due to an event refetch has been solved in v5.7.0

blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

**Closed by arshaw** 2021-05-12 03:30 UTC
Labels: Accepted, Event More/Popover

**Comment by LouiZibdawi** [comment] 2021-05-18 15:11
I am still facing the issue that @drelfien outlined in his fiddle.

When I have a more event popover which launches popovers, the popover is not clickable because the clicks on it are caught by the more event popover and they trigger it to close.

See the example provided by @drelfien for a similar case

**Comment by casually-creative** [comment] 2022-10-18 16:18
@acerix @arshaw Not all use cases have been covered with above updates or workarounds. I made an implementation where I can drop external events on an existing event (and fire custom logic). However this is not possible on the events that are grouped in a popover and accessible through the moreLink action. As soon as I start dragging an external event, the popover closes because it's seen as an outside click.

I desperately need a setting like "autoHidePopover" which I could set to false. This is the piece of code that would need to be skipped:

```js
// Triggered when the user clicks *anywhere* in the document, for the autoHide feature
_this.handleDocumentMouseDown = function (ev) {
    // only hide the popover if the click happened outside the popover
    var target = getEventTargetViaRoot(ev);
    if (!_this.rootEl.contains(target)) {
        _this.handleCloseClick();
    }
};
```

Thanks in advance.
