### ISSUE TITLE
switching views before event fetch resolves, JS error

### ISSUE THREAD

**Issue by NashBridgesAT** [fullcalendar/fullcalendar#3689] opened 2017-05-25 00:52 UTC
I've tried to reproduce that behaviour in a codepen, but there it seems to work properly... 

[https://codepen.io/anon/pen/xdBOLx](https://codepen.io/anon/pen/xdBOLx)

This is my calendar code:

`
$(function() {    
	
	$('#calendar').fullCalendar({
        // put your options and callbacks here
		theme: true,
		header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,listWeek'
			},
		editable: false,
		eventLimit: true,
		selectable: true,
		 loading: function( isLoading, view ) {
            if(isLoading) {// isLoading gives boolean value
                //show your loader here 
            console.log("loader started");
				} else {
                //hide your loader here
             console.log("loader finished");
		 }
        },
		select: function(start, end) {

			var s = $.fullCalendar.moment(start);
			var e = $.fullCalendar.moment(end);
		
			s=s.format('DD.MM.YYYY');
			e=e.format('DD.MM.YYYY');
			
			$('#sperrestartdatum').val(s);
			$('#sperreenddatum').val(e);
			$('#add_sperre').modal('show');
		},
		
		 eventSources: [

        // your event source
        {
            url: './controls/json_test.php',
        type: "POST",    
            error: function() {
                alert('there was an error while fetching events!');
            },
            color: 'yellow',   // a non-ajax option
            textColor: 'black' // a non-ajax option
        }

        // any other sources...

    ]
			
    });       
	});	
`

As you can see it is the same as in the codepen, but it is loading the event data of a jsonfeed, created by a php-file. The problem is, that this works from time to time and sometimes it fails, producing an "TypeError: events is null" error message in the console. If that error occurs, the actual view (month) is not working, but the events are shown in the week and list view. 

![grafik](https://cloud.githubusercontent.com/assets/22543777/26431548/f07bb87a-40f5-11e7-89a6-a7f0b0d0f0cd.png)

It seems that the calendar tries to render before the feed is loaded properly and therefore tries to analyze an empty or at this point non-existing events object. 

i have found a possible solution as a workaround: i create the calendar without the eventSource option and call 

`$('#calendar').fullCalendar('addEventSource','./controls/json_test.php');`

explicitly. But i would prefer to get the feeds (there will be more than one from multiple sources) when initializing the calendar.

**Comment by arshaw** [comment] 2017-05-27 05:54
if it can't be recreated in your codepen recreation, then is must have something to do with your `./controls/json_test.php` script intermittently returning invalid event data. Or some other wonky theory involving a race condition. Either way, I can't fix if I can't reproduce.

**Comment by NashBridgesAT** [comment] 2017-05-27 11:10
hi
thanks for your reply. 
in fact it must be a "race condition" problem, because the workaround solution works perfectly and never produces that error. 

anyway, i know that it is hard or even impossible for you to fix it that way. 
i just wanted you to know that there is maybe a problem and offer the workaround solution for everybody facing similar problems. 

if i find the reason for that behaviour  i let you know...

best regards
christian

**Comment by lesilent** [comment] 2017-07-27 07:27
I stumbled across this same issue and managed to create a test case. In my test case, I have two day views and a function that simulates an ajax call by calling the events callback after 5 seconds. In the first test case, the events function is added as an option. When you toggle between the views prior to the callback being kicked off, a "TypeError: events is null" error occurs. In the second test case, the events function is added using the addEventSource method. Now, when you toggle between the views prior to the callback, the error does not occur.

Error: [https://jsfiddle.net/y1a7s788/1/](url)

Workaround: [https://jsfiddle.net/y1a7s788/2/](url)

**Comment by arshaw** [comment] 2017-08-10 00:59
thanks @lesilent , recreated.

synopsis: switching between views before the initial event fetch resolves results in a JS error.

**Comment by arshaw** [comment] 2018-01-29 01:06
looks like this was fixed at some point. 3.8.0 is good:
https://jsfiddle.net/js52nya4/1/

**Comment by MrRious** [comment] 2018-08-01 14:08
I don't know if my problem has something to do with the error described above but at least it's similar and I also reproduced this in an application with FC 3.9.0.
If you use the eventSources and switch to another view before the callback was called and then switch back after the time it needs to trigger the callback the view is completely destroyed.

Steps to reproduce in your jsfiddle [https://jsfiddle.net/js52nya4/1/](https://jsfiddle.net/js52nya4/1/):
1. Before the event is loaded in the actual view, switch to the basicDay view.
2. When the basicDay view rendered the event switch back to agendaDay view.
3. The view is broken (see error below) even if you switch again.

This is the error which occurs when you switch back to agendaDay view in step 2:
Uncaught TypeError: Cannot read property 'minTime' of null
    at SubClass.TimeGrid.computeTimeTop (fullcalendar.js:11961)
    at SubClass.TimeGrid.computeDateTop (fullcalendar.js:11955)
    at SubClass.TimeGrid.computeSegVerticals (fullcalendar.js:11994)
    at TimeGridEventRenderer.updateFgSegCoords (fullcalendar.js:13826)
    at TimeGridEventRenderer.renderFgSegsIntoContainers (fullcalendar.js:13734)
    at TimeGridEventRenderer.renderFgSegs (fullcalendar.js:13725)
    at TimeGridEventRenderer.EventRenderer.renderFgRanges (fullcalendar.js:4275)
    at TimeGridEventRenderer.EventRenderer.render (fullcalendar.js:4263)
    at SubClass.DateComponent.executeEventRender (fullcalendar.js:8831)
    at AgendaView.executeEventRender (fullcalendar.js:11507)

Somehow there is no dateProfile.

**Comment by acerix** [comment] 2018-08-01 19:09
Thanks for the report.  I get the same error following those steps so it seems the issue was never resolved.

**Comment by Maadtin** [comment] 2018-11-29 10:44
I alsohave this issue, is there any fix for this please?

**Comment by arshaw** [comment] 2019-01-01 23:31
@MrRious, I was able to re-recreate. the step i was missing was switching back to the first view after the events render in the second view

**Comment by arshaw** [comment] 2019-01-10 16:16
fixed with 13385f735f8e1c06805a5fe23b9e6549bdfe1cdc (not yet released)

**Closed by arshaw** 2019-01-10 16:16 UTC
Labels: Confirmed, Event Source

**Comment by arshaw** [comment] 2019-01-11 03:01
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)
