### ISSUE TITLE
All day background events rendered in time slots of timeGrid Views

### ISSUE THREAD

**Issue by kxl4126** [fullcalendar/fullcalendar#6130] opened 2021-01-30 22:45 UTC
### Reduced Test Case

According to documentation of Full Calendar v5, "background events that are all-day will only be rendered in month view or the all-day slots of TimeGrid view". I have the code sand box link below:

https://codesandbox.io/s/fullcalendar-v5-all-day-background-events-9k9r8

As you can see, the background event that is specified as all day covers all the time slots for that date, even in timeGridWeek view.

### Bug Description

The gist of the bug is that when you specify a background event as "allDay: true", it renders for all time slots in the timeGrid views, instead of JUST the all-day slot at the top of the time grid views. I am using the React Full Calendar library, but I believe that this visual inaccuracy affects the general library as well.

### Screenshots

Here is a screenshot:

<img width="543" alt="Screen Shot 2021-01-30 at 4 40 28 PM" src="https://user-images.githubusercontent.com/41594751/106369853-6f261b80-631a-11eb-8f52-8cd60bced3db.png">

As you can see, a single "all-day" background event actually spans the entire day in the time grid views, instead of just the all-day slot.

**Comment by alltonp** [comment] 2021-02-03 15:52
I desire the same behaviour as you.. just the all-day slot, but it looks like this was added as a [feature](https://github.com/fullcalendar/fullcalendar/issues/2691).

Would it be possible to make this configurable?

**Comment by kxl4126** [comment] 2021-02-03 16:00
> I desire the same behaviour as you.. just the all-day slot, but it looks spanning the entire day like this was added as a [feature](https://github.com/fullcalendar/fullcalendar/issues/2691).
> 
> Would it be possible to make this configurable?

Oh, I didn't know this was added as a feature, as per the docs it says the behaviour is just in the all-day slots. I would like this to be able to easily differentiate between all-day background events and other background events.

**Comment by alltonp** [comment] 2021-02-03 16:29
Yep, I would really like that too.

**Comment by acerix** [comment] 2021-02-04 22:26
Closing since it's a duplicate of a previous issue:
https://github.com/fullcalendar/fullcalendar/issues/6146
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2021-02-04 22:26 UTC
