### ISSUE TITLE
Recurrence - with Count and Timezone, is not displayed

### ISSUE THREAD

**Issue by marioruistomas** [fullcalendar/fullcalendar#6833] opened 2022-05-02 10:14 UTC
### Reduced Test Case

Here is the reduced Test case: https://codepen.io/mtomasrst/pen/YzeKjRB
I set it with 3 similar events, two work well, and the one with Count and timezone is not displayed:

WithUnWithTZ  (with until, with timezone), it's ok. 
rrule: 'DTSTART;TZID=Europe/Lisbon:20220425T110000\nRRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20220427T110000'

WithCountNoTZ (With count, no timezone) it's ok
rrule: 'DTSTART:20220425T123000Z\nRRULE:FREQ=DAILY;INTERVAL=1;COUNT=3'

WithCountWithTZ (With count and timezone), **it's not displayed, it's the issue.**
rrule: 'DTSTART;TZID=Europe/Lisbon:20220425T123000\nRRULE:FREQ=DAILY;INTERVAL=1;COUNT=3'

### Bug Description

Describe how to recreate the bug.
- By Creating an event with timezone and the rrule with count operator, like this:
    {   title: 'WithCountWithTZ',
        duration: {hours:1},
        rrule: 'DTSTART;TZID=Europe/Lisbon:20220425T123000\nRRULE:FREQ=DAILY;INTERVAL=1;COUNT=3'
     }

What do you expect to happen?
I Expected the event to be displayed in the calendar. Displayed as the other examples set, using the count operator without timezone, or the until with timezone.

### Screenshots

Only two events shown, instead of 3. The one with count and timezone is not displayed.
![image](https://user-images.githubusercontent.com/104762947/166219029-90e1f085-1653-4d5d-8356-c3e24702081c.png)

**Comment by acerix** [comment] 2022-05-03 18:15
It seems this is a duplicate of this issue:
https://github.com/fullcalendar/fullcalendar/issues/6833
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2022-05-03 18:15 UTC

**Comment by marioruistomas** [comment] 2022-05-03 23:56
Hi,

Did you type the issue number wrong?
6833 is this issue. I didn't found a duplicate. Please reopen the issue, or
show me the correct issue number,

Thanks
