### ISSUE TITLE
Is it possible to display events horizontally in calendar?

### ISSUE THREAD

**Issue by santoshyadu** [fullcalendar/fullcalendar#3738] opened 2017-07-11 12:15 UTC
Is it possible to display events horizontally in calendar (see attached image for your ref
![calendar_v](https://user-images.githubusercontent.com/29423856/28067874-b2fe0530-6660-11e7-8f08-73bf86eb5df0.png)
erence)?

**Comment by MartijnWelker** [comment] 2017-07-14 09:04
Duplicate of #2306 and #3579

**Closed** 2017-07-14 19:25 UTC
