### ISSUE TITLE
Select & DayClick seems offset in v4

### ISSUE THREAD

**Issue by PetterBronsta** [fullcalendar/fullcalendar#4221] opened 2018-06-19 07:50 UTC
In v4, the selecting and dayclicks seems offset. If you have a scrollbar on the page it self (not the calendar window). scroll down a notch or two, and select a cell. The day/month/etc is then offset so not the right one is clicked. 

Tried different views Month/agendaweek etc.
Also tried having the height set to specific (900px), 'auto' and 'parent', with same behavior.

I can provide more info if needed.
- Petter

**Comment by acerix** [comment] 2018-06-19 22:06
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by gmw-web** [comment] 2018-06-28 09:59
We're experiencing the same issue. The issue is not only present in the regular calendar views, but also in the scheduler.

Here's a working codepen: https://codepen.io/anon/pen/zaMwpN

**Comment by mvaljento** [comment] 2018-09-03 06:15
I just ran into this in weekAgenda view. Event clicks work, but after scrolling a tall calendar view, the day clicks are offset so much vertically that they are unusable. 

Is there any fix for this yet?

**Comment by jgadbois** [comment] 2018-09-12 19:52
I'm having the same issue in the alpha release

**Comment by arshaw** [comment] 2018-10-02 06:18
fixed in 4.0.0-alpha.2 (just released)

try it on this and you will see:
https://fullcalendar.io/docs/v4/date-clicking-selecting-demo

**Closed by arshaw** 2018-10-02 06:18 UTC
Labels: Confirmed, Scrolling, Selection, View Interaction

**Comment by arshaw** [comment] 2019-03-20 21:10
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
