### ISSUE TITLE
how to get resouces dynamicly

### ISSUE THREAD

**Issue by peon501** [fullcalendar/fullcalendar#4324] opened 2018-09-25 19:01 UTC
code like this:
  data: function () {
        return {
          action: 'view',
          search_text: search_text
        };
      },

inside resources do not work. it only works in events how can I change ajax parameters in resources after button click and so on so I could rerender resources list? or is this bug ?

**Comment by acerix** [comment] 2018-09-25 22:36
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by peon501** [comment] 2018-09-26 07:35
ok found out work around for the way to change parameters of ajax dynamicly using jquery ajax

    resources: function(callback) {
        var view = $("#calendar").fullCalendar("getView");
        $.ajax({
        url: "",
        type: 'POST',
        dataType: "json",
        cache: false,
        data: {
          start      : view.start.format(),
          end        : view.end.format(),
          timezone   : view.options.timezone,
          action     : 'projects_employees',
          search_text: search_text
        }
      }).then(function(resources) {
        callback(resources);
      })
    },

**Comment by peon501** [comment] 2018-09-26 07:42
Basically the problem was that I can't change data parameters after calendar initialization.
For events this worked:

```
    events: {
      url : '',
      type: 'POST',
      data: function () {
        return {
          action: 'view',
          search_text: search_text
        };
      },
      error: function() {
        alert('there was an error while fetching events!');
      },
      color:     '#31b0d5', // a non-ajax option
      textColor: '#fff;',   // a non-ajax option
    },

```
for resources it didnt so I had to make like that:

```
    resources: function(callback) {
        var view = $("#calendar").fullCalendar("getView");
        $.ajax({
        url: "",
        type: 'POST',
        dataType: "json",
        cache: false,
        data: {
          start      : view.start.format(),
          end        : view.end.format(),
          timezone   : view.options.timezone,
          action     : 'projects_employees',
          search_text: search_text
        }
      }).then(function(resources) {
        callback(resources);
      })
    },
```

Simple ways like that do not work cuz are static and couldn't be changed after init:

```
      url: '',
      type: 'POST',
      data: {
          action: 'projects_employees',
          search_text: search_text
      }

```
So yeah I had to do some stuff, but it will help others as me wandering around and thinking wtf :),

Your welcome community.

**Comment by peon501** [comment] 2018-09-26 07:47
I don't have time for runnable, stripped-down demonstration of the bug, but be aware that this bug exists and at last give alternative solutions in docs :).

**Comment by ravid007** [comment] 2019-03-21 22:05
Does anyone know if the bug of the dynamic parameters in the resources has been fixed in version 4.0.01?
```
resources: {
      url: '',
      type: 'POST',
      data: {
          action: 'projects_employees',
          search_text: search_text
      }
}
```

**Comment by arshaw** [comment] 2019-03-21 22:36
it has been renamed to `extraParams`: https://fullcalendar.io/docs/resources-json-feed

**Closed by arshaw** 2019-03-21 22:36 UTC
Labels: Reproducing, View Rendering

**Comment by Aldo-f** [comment] 2020-12-17 16:54
Look, this is still an issue...
Thanks @peon501 for a working result:

```
## Setting some random data
function getExtraEventParams() {
	return {
		'random': Math.random()
	}
}

## Results in always having the same "random"-number...
events: {
	url: base_url + 'Json/getTimeline',
	method: 'POST',
	extraParams: getExtraEventParams(),
},

## The solution:
events: function (callback) {
	$.ajax({
		url: base_url + 'Json/getTimeline',
		type: 'POST',
		dataType: "json",
		cache: false,
		data: getExtraEventParams()
	}).then(function (events) {
		callback(events);
	})
},

```

Please update the readme... 
https://fullcalendar.io/docs/events-json-feed#dynamic-extraparams-parameter
