### ISSUE TITLE
Page does not scroll when an event is dragged and height is set to auto

### ISSUE THREAD

**Issue by jaflo** [fullcalendar/fullcalendar#3273] opened 2016-07-14 12:40 UTC
[Test case](http://output.jsbin.com/xaruruxonu/)

A calendar showing the `agendaDay`-view and having its height set to `"auto"` will break the [dragScroll](http://fullcalendar.io/docs/event_ui/dragScroll/) functionality. To reproduce, drag an event near the top or bottom of the screen.

Expected behavior: dragging an event will scroll the window/body.

Current behavior: the dragged event simply moves off-screen.

**Comment by arshaw** [comment] 2016-07-15 06:10
hi @jaflo, I believe this is a duplicate of:
https://github.com/fullcalendar/fullcalendar/issues/2761
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2016-07-15 06:10 UTC
