### ISSUE TITLE
Add ac Class to data-date attribute if a date has an event

### ISSUE THREAD

**Issue by amitabhaghosh197** [fullcalendar/fullcalendar#2876] opened 2015-09-23 10:13 UTC
I am using your plugin. I want to add a class to the data-date attribute if any day has an event exist. Can anyone please help me how to do that?
Thanks in advance.

**Comment by espen** [comment] 2015-09-23 10:23
Please see http://fullcalendar.io/support/ for questions.

**Comment by amitabhaghosh197** [comment] 2015-09-23 10:27
Thanks espen

**Comment by arshaw** [comment] 2015-10-11 16:49
duplicate of #345

**Closed by arshaw** 2015-10-11 16:49 UTC
