### ISSUE TITLE
Event content flickers when dropping an event because `eventContent` fires twice

### ISSUE THREAD

**Issue by Berger1994** [fullcalendar/fullcalendar#7165] opened 2023-01-25 15:40 UTC
### Reduced Test Case

https://codesandbox.io/s/busy-faraday-fnlbfr?file=/src/App.js

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

The eventContent function is executed twice on dragging. The first execution is with the initial time and the second one is the current dragging time. This causes small but ugly ui flickering.

In the example, you can check the log in the console. If you drag or resize the event, you can see 2 lines of logging.
I started with an event at 3:00 and resize the start to 2:30, then to 2:00. The logging is the following:

render 3:00 
render 2:30 
render 3:00 
render 2:30 
render 3:00 
render 2:00 
render 3:00 
render 2:00 

In my opinion, the logging should be something like this:

render 3:00 
render 3:00 
render 2:30 
render 2:30 
render 2:00 
render 2:00 

Maybe only once, but this is not the problem of the flickering. 
![report](https://user-images.githubusercontent.com/2832534/214607143-ff9c53eb-453f-4d24-b57e-950028d6d2df.gif)

**Comment by mohux** [comment] 2023-02-02 10:37
https://user-images.githubusercontent.com/57658626/216302111-437c0994-6b7c-4922-8ce3-bb77d29fd460.mov

it happens on select mirror as well, not sure if it happens on editable 

only when you pass eventContent

**Comment by nandorojo** [comment] 2023-04-05 02:36
I’m getting similar issues, it always flickers when I use eventContent with JSX

**Comment by frankhock** [comment] 2023-04-06 13:41
Somewhat related, I'm experiencing a similar flicker when updating `eventSources` prop asynchronously.

**Comment by semyonn-7pace** [comment] 2023-04-11 08:22
Also with JSX in eventContent blinking happens with whole event, not only with content inside it

![chrome_BgSLSDqWfw](https://user-images.githubusercontent.com/69300040/231099931-c221e082-59b1-4605-870c-84e17671b4e2.gif)

**Comment by marcoancona** [comment] 2023-04-25 16:02
Experiencing the same, and not only with `eventContent` but also with other components. For example, passing a `dayHeaderContent` seems to cause the header to flicker every time the view is moved forward/backwards. This seems to happen only with the combination React 18 + FullCalendar v6. The same is not happening with FullCalendar v5.

**Comment by arshaw** [comment] 2023-05-08 22:48
This should be significantly improved in [v6.1.7](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.7)

The flicker during dragging/resizing/selecting should no longer exist. There still might be a slight flicker right at the end of the interaction, but it probably won't be very noticeable. This can only possibly be fixed in the next major version.

Please let me know if things look better.

Additionally, `eventContent` and the other content-injection hooks are called less often during drag. @Berger1994, this is the problem you pointed out. Please see this updated repro: https://stackblitz.com/edit/github-na3gnr?file=src%2FDemoApp.jsx,src%2Findex.css,package.json

**Closed by arshaw** 2023-05-08 22:48 UTC
Labels: Confirmed, Event Rendering, Event DnD/Resize, React Only

**Comment by nandorojo** [comment] 2023-05-09 08:45
Thanks so much @arshaw. I downgraded to v5 due to flickers and #7284, but I’ll definitely upgrade again to try it out once that one is fixed. If I manage to make a reproduction outside of my app for the Next.js issue, I’ll send it there. Appreciate your quick help here.

**Comment by Warziik** [comment] 2023-05-09 09:45
Thank you, much appreciated, great work!

**Comment by Warziik** [comment] 2023-05-17 19:08
> Did this get fixed for you guys?

Yes, no problem anymore with the blinking issue when selecting on the calendar

**Comment by marcoancona** [comment] 2024-05-31 15:17
Unfortunately, this issue does not seem to be fixed for us. We have previously downgraded to v5 because of this issue and we have now tested it again with 6.1.13.

Here you can see a comparison: on the window at the bottom (v5) you can see how smooth is switching across weeks, while on the window at the top (v6) you see an evident flickering as if events were removed from the view for too long.
