### ISSUE TITLE
Single day - allDay event not showing when time is specified

### ISSUE THREAD

**Issue by criluc** [fullcalendar/fullcalendar#3854] opened 2017-10-02 16:43 UTC
I was wondering why fullcalendar (actually v. 3.5.1) doesn't show an event on the calendar if you set 'allDay:true' and the start and end attributes to the same day but with different time.

For example an event like this isn't shown:

{
  title: 'All Day with time',
  allDay: true,
  start: new Date(2017, 10, 1, 10, 0, 0),
  end: new Date(2017, 10, 1, 18, 0, 0)
}

I think fullcalendar should show the event even those I'm setting the event as an all day event but the difference beetwen the start and end time is less than 1 day.

Is it correct or is it a bug?

If I left out the time and I leave only the date with the same day it works correctly.

I've preparared a Reduced Test case on jsfiddle https://jsfiddle.net/yqs0jnhq/4/

Thanks!

**Comment by arshaw** [comment] 2017-10-23 14:10
it must be discarding the event as invalid because it must be stripping the time before doing validation, and if the start === end, it must be considering it invalid.

i tested to see if this is a regression from 3.5.* -> 3.6.* and it's not:
https://codepen.io/arshaw/pen/JrqbJv?editors=0010
https://codepen.io/arshaw/pen/qPGqjK?editors=0010

Will look into this more.

**Comment by anoblg333** [comment] 2017-11-29 16:20
I experienced the same issue. The regression was from 3.4.0 -> anything afterwards. In 3.4.0, I was able to specify allDay=true and specify an end date (now I have to make sure end is not specified for it show properly).

**Comment by fr0z3nfyr** [comment] 2018-08-01 13:34
Still facing this with latest release (stable)

**Comment by sukhjindersingh** [comment] 2018-11-29 16:13
> Still facing this with latest release (stable).
> 
> **EDIT:** Sorry, it was my bad. I had mistakenly used `allday` property instead of `allDay`. It works fine for me at least in the three cases tested below (with `allDay: true`):
> 
>     1. Same start and end dates
> 
>     2. Different start and end dates
> 
>     3. Only start date but no end date

Did you test it with time like below?

`Start: 2018-10-29T12:00:00`
`End: 2018-10-29T13:00:00`

**Comment by arshaw** [comment] 2019-01-01 23:22
still exists in v4: https://codepen.io/arshaw/pen/QzawmM?&editable=true&editors=001

**Comment by arshaw** [comment] 2019-01-10 16:13
fixed with 021af57777f6a256edc4a18a791b6d6355d9f611. not yet released

**Closed by arshaw** 2019-01-10 16:13 UTC
Labels: Confirmed, Event Model

**Comment by arshaw** [comment] 2019-01-11 03:01
released in [3.10.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.10.0)

**Comment by fr0z3nfyr** [comment] 2019-06-03 05:17
Thanks for the update

**Comment by goosehub** [comment] 2019-07-12 19:17
In case anybody finds their way to this issue for the same reason as I, it appears if you're using vue and fullcalendar 3.10.0, it will not be an issue on dev mode, but production mode causes the issue above.

**Comment by denism300** [comment] 2023-10-09 16:37
I have a similar problem
Sample of event item:
`{
    id: 'some_id',
    title: 'some_title',
    start: startDate.toISOString().split('T')[0],
    end: endDate.toISOString().split('T')[0],
    editable: true,
    display: 'background',
    allDay: true
}`
and the last day of the event is not displayed on the calendar. How can this be fixed?
