### ISSUE TITLE
Recurring Events don't show up on Weekly/Daily Time Grid when endTime is before startTime

### ISSUE THREAD

**Issue by alex-osman** [fullcalendar/fullcalendar#4786] opened 2019-07-19 20:23 UTC
### Bug Report
Recurring events are showing in the monthly views but not on weekly or daily.  I'm having this problem with v4.2.0

JSFiddle: https://jsfiddle.net/a0qx2udf/10/

```
events: [{
    title: 'Test',
    daysOfWeek: ['1', '2', '3'],
    startTime: "08:30",
    endTime: "00:30",
}]
```

**Comment by acerix** [comment] 2019-07-19 21:26
This happens if `endTime` is before `startTime`, it works as expected if the `endTime` is "24:30" which means "00:30 on the next day".

https://jsfiddle.net/t8dfxeLc/1/

**Comment by arshaw** [comment] 2019-07-25 21:35
duplicate of:
#4440
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2019-07-25 21:35 UTC
Labels: Discussing, Docs, Event Rendering
