### ISSUE TITLE
"More events" popover falls behind the sticky dates header

### ISSUE THREAD

**Issue by lllopo** [fullcalendar/fullcalendar#5782] opened 2020-09-04 07:29 UTC
### Reduced Test Case

It is for a different issue, but also easily shows this one. Just click the "+more" link and scroll to make it go under the days header.

[https://codesandbox.io/s/fc-5-month-view-height-fails-7efst](https://codesandbox.io/s/fc-5-month-view-height-fails-7efst)

### Bug Description

When a "more events" popover contains a lot of events or gets scrolled in a way it intersects with the dates header (and it is sticky) - it falls behind it instead of going over it.

### Screenshots

![Annotation 2020-09-04 102634](https://user-images.githubusercontent.com/5485902/92211703-865efb00-ee99-11ea-9beb-4cd1dde9a7f4.png)

**Comment by acerix** [comment] 2020-09-04 21:53
Thanks, confirmed.

**Comment by arshaw** [comment] 2020-09-05 14:08
dup of:
https://github.com/fullcalendar/fullcalendar/issues/5596
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

(thought I used your screenshot, thanks)

**Comment by arshaw** [comment] 2020-09-05 14:09
actually, nevermind. it looks like a different issue than the one I just linked

**Comment by lllopo** [comment] 2020-09-05 14:09
> actually, nevermind. it looks like a different issue than the one I just linked

@arshaw Yup, I think it is different.

**Comment by Marionovello** [comment] 2020-09-10 20:02
https://codepen.io/marionovello/pen/RwaMEXq?editors=0010
Ran into this as well. Changing the _height_ option to anything other than "auto" helped (or just remove the height option) but obviously this isn't a permanent solution.

**Comment by albert-estradera** [comment] 2021-03-12 12:22
+1

**Comment by arshaw** [comment] 2021-05-12 03:07
This has been fixed in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

fixed repro: https://codepen.io/arshaw/pen/gOmPOwB?editors=0010

**Closed by arshaw** 2021-05-12 03:07 UTC
Labels: Confirmed, Event More/Popover

**Comment by Kepro** [comment] 2021-05-19 14:18
z-index: 9999; really? @arshaw make som normal number please... this is non sense to use 9999.... I will expect that from junior developer not serious library...
