### ISSUE TITLE
Drag and drop of events only available on first visible rows of calendar

### ISSUE THREAD

**Issue by fabio-a-beretta** [fullcalendar/fullcalendar#3821] opened 2017-09-05 19:15 UTC
When css statement overflow-x: hidden is set in the stylesheet I am experiencing the impossibility to drag/drop and resize events below the first few fullcalendar table lines:

This is the reduced test case: https://codepen.io/fberetta/pen/vJPprZ?editors=0100

To reproduce the bug:
- Open the codepen
- Try to drag/drop one of the external events below the few calendar visible lines: should be impossible
- Try to drag and resize events in the cells below the visible part of the calendar: it should be impossible

The bug occurs from library ver. 2.5.0 (versions <=2.4 do not show this issue).

I believe this is also connected to this bug previously reported 
 https://github.com/fullcalendar/fullcalendar/issues/3554

Any fix available?

ty
f

**Comment by arshaw** [comment] 2017-09-25 07:05
@fabio-a-beretta , this is a duplicate of this ticket:
https://github.com/fullcalendar/fullcalendar/issues/3615
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2017-09-25 07:05 UTC
