### ISSUE TITLE
filterResourcesWithEvents shouldn't refresh the header (updated with codepen)

### ISSUE THREAD

**Issue by AssassinLV** [fullcalendar/fullcalendar#3782] opened 2017-08-09 05:57 UTC
As the title says.

Because of the current implementation of the filterResourcesWithEvents I have currently 2 issues:
1) The Toggle Switch (for showing hiding the empty resources) does not show the animation
2) After each "on Change" I have to reinsert the toggle switch back to the calendar - as otherwise the toggle switch disappears. And this makes the "toggling" empty resources much more complex as it should have been

![image](https://user-images.githubusercontent.com/30855600/29107007-c15c0a00-7ce0-11e7-9fea-3ed284e156eb.png)

P.S. on toggle.change I am runing this code:
`.fullCalendar('option', "filterResourcesWithEvents", value)`

**Comment by arshaw** [comment] 2017-08-10 03:21
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by AssassinLV** [comment] 2017-08-10 03:53
I can try... Will try right now...

**Comment by arshaw** [comment] 2017-08-10 14:28
thanks for the recreation. that's really strange. must be a bug with the dynamic options-changing system.

**Comment by AssassinLV** [comment] 2017-11-29 05:39
@arshaw Is there a plan on when the work on fixing it could start (or alternatively supporting toggle buttons by default)?

**Comment by arshaw** [comment] 2020-06-25 17:10
this is almost definitely fixed in v5

**Closed by arshaw** 2020-06-25 17:10 UTC
Labels: Confirmed, Toolbar
