### ISSUE TITLE
Events not sorted by eventOrder

### ISSUE THREAD

**Issue by cchlam** [fullcalendar/fullcalendar#5766] opened 2020-08-31 02:47 UTC
### Reduced Test Case
https://codepen.io/lch0/pen/WNwjPjq

### Bug Description
eventOrder has been set to "title". However, between Aug 24-Aug 28, it does not sort correctly by "title".
`var calendar = new FullCalendar.Calendar(calendarEl, {eventOrder: "title".......`

For example, on Aug 24, I expect it is sorted in the order of "Ca-->Cl-->Ev-->Ma-->Wi".

However, it is in fact sorted in the order of "Ca-->Wi-->Cl-->Ev-->Ma".

### Screenshots
![image](https://imagizer.imageshack.com/img922/79/9ElL98.png)

**Comment by TomJLynch** [comment] 2020-09-08 15:50
I was just going to post an issue about this same problem.  In my case, I'm using numbers in an extended property field to sort.  When I use eventOrder to sort events in a single day, it works fine. However, if I put events on a second day, the order of the 2nd day's events alter the order of the first day's events.

https://codepen.io/tramplerine/pen/gOrXPON?editable=true&editors=001%3Dhttps%3A%2F%2Ffullcalendar.io%2Freduced-test-cases

Check out the codepen link for my example on the date July 26. Day 1 has four events. Three are multi-day events and one is a single-day event. I use eventOrder to sort the events, putting the single-day event last. That works fine if I only display data for Day 1. However, I added a second day. Day 2 also has four events (the same three multi-day events and it's own single-day event). I use eventOrder to sort the events, ordering Day 2's single-day event to be the second event to display on Day 2.

The result: Day 1's single-day event (which is supposed to be ordered last on Day 1) floats up to be the second event on Day 1. The calendar needs to render extra space under the first multi-day event to render Day 2's single day event, which is correct. However, instead of leaving empty space on Day 1, the calendar fills in the space by bringing up the Day 1 single-day event to the second row instead of keeping it last where it belongs.

**Comment by acerix** [comment] 2020-09-08 20:00
Thanks, confirmed.  I simplified the events and it seems the event on the following day is causing the order to change.

https://codepen.io/acerix/pen/YzqeLRR?editors=0010

**Comment by arshaw** [comment] 2020-09-21 02:27
the issue is still in latest. https://codepen.io/arshaw/pen/YzqRqBV?editors=0010

i'll look into this for the next release

**Comment by arshaw** [comment] 2020-10-26 22:31
corrected latest-version repro: https://codepen.io/arshaw/pen/YzqRqBV?editors=0010

After thinking about this a bit more, I realized the current behavior is not actually "buggy", it's the designed behavior. Please look at this screenshot:

![Screen Shot 2020-10-26 at 6 24 33 PM](https://user-images.githubusercontent.com/56520/97235281-ea76af00-17b8-11eb-9f23-26741c288dac.png)

All events are in correct alphabetical order except for "Wi" event. It is a "feature" that is is put in the available space between the 1st and 3rd event, even though it is the 6th event. The goal is to save as much vertical space as possible.

In this scenario, would you prefer it to be at the very bottom?

If enough people want this modified behavior, I might introduce a new flag.

**Comment by 21Junipers** [comment] 2020-10-26 22:36
New flag please.....

**Comment by endelwar** [comment] 2020-11-05 18:27
I'd like to use a new flag for forcing order in case like this.

**Comment by gurramswadeep** [comment] 2021-03-04 22:27
@arshaw I do have the same issue for rending events as per sortOrder. Is the new flag already introduced or do we have any date that is planned to release the new flag.

**Comment by arshaw** [comment] 2021-05-12 02:43
This has been released in v5.7.0!
blog post: https://fullcalendar.io/blog/2021/05/new-features-in-v570

output with `eventOrderStrict: true`
https://codepen.io/arshaw/pen/YzqRqBV?editors=0010

**Closed by arshaw** 2021-05-12 02:43 UTC
Labels: Confirmed, DayGrid View, Event Rendering
