### ISSUE TITLE
Ability to scroll horizontally to a day in vertical resource view (like scrollToTime)

### ISSUE THREAD

**Issue by TornadoLi** [fullcalendar/fullcalendar#7280] opened 2023-04-07 09:56 UTC
### Checklist

- [X] I've already searched through [existing tickets](https://github.com/fullcalendar/fullcalendar/issues)
- [X] Other people will find this feature useful

### Is this feature for a specific connector (React/Angular/etc)?

No connector in particular

### Feature Description

resourceTimeGridWeek view horizontal scrolling is not supported using the scrollGrid plugin.
For example：I click a "Today" button that I need to scroll horizontally to today automatically.
So I used two apis(scrollTime, scrollToTime ) and I couldn't do it, It only supports vertical scrolling.
```
{
    initialView: 'resourceTimeGridWeek',
    plugins: [resourceTimeGridPlugin, listPlugin, interactionPlugin, momentPlugin, scrollGridPlugin],
    dayMinWidth: 300,
    datesAboveResources: true,
    allDaySlot: false,
    events: [
      { resourceId: "a", title: "event 1", start: new Date().setHours(10), end: new Date().setHours(12)},
      { resourceId: "a", title: "event 2", start: new Date().setHours(11), end: new Date().setHours(13) },
    ],
resources: [
      {
        id: 'a',
        title: 'Room A',
        businessHours: [
          {
            startTime: '12:00',
            endTime: '14:00',
            daysOfWeek: [0]
          },
          {
            startTime: '08:00',
            endTime: '18:00',
            daysOfWeek: [1, 2, 3]
          },
        ],
        extendedProps: { test: 'Room A extendedProps' }
      },
      { id: 'b', title: 'Room B' },
      { id: 'c', title: 'Room C' },
      { id: 'd', title: 'Room D' }
    ]
}
```

**Comment by acerix** [comment] 2023-08-17 22:41
I just realised this is a duplicate of an earlier issue:
https://github.com/fullcalendar/fullcalendar/issues/4806
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by acerix** 2023-08-17 22:41 UTC
Labels: Discussing, Scrolling, TimeGrid View
