### ISSUE TITLE
[alpha2] gotoDate doesn't update currentDate anymore

### ISSUE THREAD

**Issue by aitboudad** [fullcalendar/fullcalendar#4333] opened 2018-10-04 11:02 UTC
### Bug Reports

see the following example, when clicking on `goToDate` btn the current date should change:
 
https://stackblitz.com/edit/typescript-zzark7

**Comment by aitboudad** [comment] 2018-10-04 11:03
I'm using the following workaround until it get fixed:
```
calendar.state.dateProfile.currentDate = date;
```

**Comment by acerix** [comment] 2018-10-04 22:30
It seems the problem is that your "dates" also include a time of day.  It works with only the date:

**Comment by aitboudad** [comment] 2018-10-04 22:44
the issue is still present when nav during the activated view dates, in your edited example change `add(33, 'days')` into `add(3, 'days')` and you'll notice the issue it was working in `v3`.

**Comment by acerix** [comment] 2018-10-10 22:33
Thanks, I missed that. Although, the docs for `getDate` says in "month view, it will always be sometime between the first and last day of the month", so it sounds like it's still working according to how it is defined.

**Comment by arshaw** [comment] 2018-12-25 06:56
at first i thought your demo has some utc/local inconsistencies that were causing the bug, so i fixed them: https://stackblitz.com/edit/typescript-yf1rbm

...but the "bug" remains. this is happening because the calendar is already in the date-range that it needs to be in upon gotoDate being called, so it short-circuits and does nothing.

I do feel that the current date should update and that this is a bug. I'll try to get it fixed before the official v4 release.

**Comment by arshaw** [comment] 2018-12-28 05:01
this is now fixed in the v4 branch in ecb0e92c250a365517b6dd4bfa43e818a7681f39

i'll comment again when it's released

**Closed by arshaw** 2018-12-28 05:01 UTC
Labels: Confirmed, View Dates

**Comment by arshaw** [comment] 2019-01-11 17:15
this has been addressed and released in [4.0.0-alpha.4](https://github.com/fullcalendar/fullcalendar/releases/tag/v4.0.0-alpha.4)

**Comment by arshaw** [comment] 2019-03-20 21:27
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)

**Comment by leehinde** [comment] 2019-12-30 23:29
What's the expected behavior then? I'm editing an event and then try this to refresh the current view:
                var currentDate = calendaring.calendar.getDate();
                calendaring.calendar.gotoDate(currentDate.toISOString());
And nothing happens.
