### ISSUE TITLE
SyntaxError: Unexpected token 'export' when running jest tests

### ISSUE THREAD

**Issue by pimmee** [fullcalendar/fullcalendar#7113] opened 2022-12-28 00:58 UTC
### Reduced Test Case

https://stackblitz.com/edit/github-sgjd3r?file=src/demo.test.jsx&view=editor

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

Since upgrading to FullCalendar v6, all my react test in jest are failing with the following error:

SyntaxError: Unexpected token 'export'

<img width="518" alt="image" src="https://user-images.githubusercontent.com/33460567/209741050-86c3f820-9fe7-4239-9b92-2da38c19f18a.png">

Here's the error when I run 'npm run test' in StackBlitz
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/33460567/209741277-a117e0ea-374f-4e67-8aab-9845eb05326c.png">

Edit: 
Here's a [StackBlitz](https://stackblitz.com/edit/github-sgjd3r-bytvco?file=package.json&view=editor) with v5.11.3 where the test is working. The following release (v6.0.0-beta.2) is not working.

**Comment by acerix** [comment] 2022-12-28 21:01
Thanks, confirmed. I get the same error when running `yarn test` on the example project.

https://github.com/fullcalendar/fullcalendar-examples/tree/main/jest-react

**Comment by adampana** [comment] 2023-01-11 12:13
I am facing the same issue when I moved to `6.0.2` from `5.11.3`

**Comment by arshaw** [comment] 2023-01-11 21:53
queued for release https://github.com/fullcalendar/fullcalendar/commit/8b0eb873326eb9fb4306f5fae07c230690146e00

**Comment by arshaw** [comment] 2023-01-11 22:23
released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

**Comment by pimmee** [comment] 2023-01-14 11:03
> released in [v6.0.3](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.3)

@arshaw I'm still experiencing the issue in 6.0.3. [See repro with 6.0.3 dependencies](https://stackblitz.com/edit/github-sgjd3r?file=src/demo.test.jsx&view=editor)

**Comment by arshaw** [comment] 2023-01-17 00:16
I was using jest 27, which works fine now. I see the problem in jest 28 and above. 

The problem is happening because [jest now looks at the "browser" field in package.json](https://jestjs.io/blog/2022/04/25/jest-28#packagejson-exports) for jsdom. Internally, preact provides a "browser" field, but the file is ESM, which jest [does not natively support without a babel transform](https://github.com/facebook/jest/issues/9430).

I'll look into this more. But a workaround would be ensuring an ESM babel transform is applied to node_modules packages (specifically preact).

**Comment by arshaw** [comment] 2023-01-17 00:28
here's a nicer workaround. in your `jest.config.js`:

```js
module.exports = {
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: [] // don't load "browser" field
  }
};
```

**Comment by pimmee** [comment] 2023-01-20 19:16
That workaround works, thanks!

**Closed** 2023-01-30 23:24 UTC
Labels: Docs, Confirmed, Distribution

**Comment by rjdestigter** [comment] 2023-09-06 20:47
I had to modify `transformIgnorePatterns` to not match `node_modules/preact` so that it would be included in the transformation: `node_modules\/(?!preact)`. Additionally I had to provide a custom transformation option as my setup (_preset ts-jest_) was only targeting TypeScript files:

```
transform: {
  "node_modules/preact": "babel-jest",
},
```

**Comment by edukisto** [comment] 2024-03-26 18:37
`tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "noEmit": true
  }
}
```

`jest.config.ts`:

```typescript
import type { JestConfigWithTsJest } from 'ts-jest';
import { defaultsESM } from 'ts-jest/presets';

const config: JestConfigWithTsJest = {
  ...defaultsESM,
  moduleNameMapper: {
    '^(.+)\\.js$': '$1',
  },
  preset: 'ts-jest/presets/js-with-ts-esm',
};

export default config;
```
