### ISSUE TITLE
OptionsInput type is not exported and some of jquery hooks definitions are incorrect

### ISSUE THREAD

**Issue by bendykowski** [fullcalendar/fullcalendar#4041] opened 2018-01-31 18:11 UTC
`OptionsInput` type is not exported from the main module. Exposing it will ease typing fullcalendar options building externally.
Also a few jquery hooks are typed incorrectly because some optional parameters are typed as required.

Made a PR to fix that: #4040

**Comment by acerix** [comment] 2018-02-06 21:27
Duplicate of https://github.com/fullcalendar/fullcalendar/issues/4006

**Closed by acerix** 2018-02-06 21:27 UTC
Labels: Core, Discussing
