### ISSUE TITLE
Timeline view unable to shrink some events

### ISSUE THREAD

**Issue by koen20** [fullcalendar/fullcalendar#7099] opened 2022-12-21 13:33 UTC
### Reduced Test Case

https://fullcalendar.io/docs/debug-scheduler

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

No connector (vanilla JS)

### Bug Description

**Recreate bug**
- Make event longer by dragging the end of the event
- Shrink event by dragging the end of the event
- The event snaps back to the original position instead of shrinking

The event snaps back to the original postion when I try to shrink it. I expect the event to resize to the correct position. I was sometimes able to fix this by moving the event to a different resource. I did not get this bug when I tried it with 5.11.3.

Fullcalendar version: 6.0.1
Browser: Chrome 108.0.5359.124 and Safari

I added a video where you can see the event snapping back to the original postion.

![full-calendar](https://user-images.githubusercontent.com/6172623/208914476-011ed8f9-f6d2-4021-9ea0-906d1d5575a8.gif)

**Comment by arshaw** [comment] 2022-12-21 16:20
Confirmed. This seems to be a v6 regression ([v5 example](https://fullcalendar.io/docs/v5/debug-scheduler)). I'll fix

**Comment by vlebeau** [comment] 2022-12-21 17:12
Is it the same problem in the timeGridWeek view? You can reproduce the problem with the Drag-n-drop demo : https://fullcalendar.io/demos

**Comment by koen20** [comment] 2022-12-22 13:53
@vlebeau It seems that all view types have the same problem. I was able to reproduce the problem with all examples from the demo page

**Comment by arshaw** [comment] 2022-12-27 23:14
Fixed in [v6.0.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.2)

See the demo page that has been updated with the latest version:
https://fullcalendar.io/docs/debug-scheduler

**Closed by arshaw** 2022-12-27 23:14 UTC
Labels: Confirmed, Timeline View, Event DnD/Resize
