### ISSUE TITLE
Ability to choose the extra space in slots when an event is available in resource timeline view.

### ISSUE THREAD

**Issue by Sawan1994** [fullcalendar/fullcalendar#7360] opened 2023-06-05 04:02 UTC
### Reduced Test Case

https://codepen.io/pen?&editors=001

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

In FullCalendar resource timeline view, when a slot has event the height of the resource lane or the slot increases leaving some space between event and slot height.

We don't want the event to fill the entire height of the slot. If there is some way to achieve this, kindly share the details.

Current implementation:
<img width="1019" alt="Screenshot 2023-06-05 at 9 17 51 AM" src="https://github.com/fullcalendar/fullcalendar/assets/16359272/670db8a0-c865-4070-b7ea-5f6020d376a3">

**Comment by acerix** [comment] 2023-06-08 01:42
Duplicate of #https://github.com/fullcalendar/fullcalendar/issues/7359

**Closed by acerix** 2023-06-08 01:42 UTC
