### ISSUE TITLE
Content flickers when calendar component is reinitialized via useState

### ISSUE THREAD

**Issue by Azaryan-A** [fullcalendar/fullcalendar#7234] opened 2023-03-06 14:30 UTC
### Reduced Test Case

https://stackblitz.com/edit/github-urj6el-oghacn?file=src%2FDemoApp.jsx

### Do you understand that if a reduced test case is not provided, we will intentionally delay triaging of your ticket?

- [X] I understand

### Which connector are you using (React/Angular/etc)?

React

### Bug Description

It's like custom view content unmounts and mounts again when fullcalendar props change, it causes content flickering when I want to update events or the header toolbar.

**Comment by acerix** [comment] 2023-03-08 03:55
I believe it's not intended to initialize the calendar after `useState` in this way since that causes the calendar component to reinitialize when the state is changed, which would hurt performance.  You can instead update events using the API, for example providing them "as a function", to avoid that:

https://fullcalendar.io/docs/events-function

Related issue here:
https://github.com/fullcalendar/fullcalendar/issues/7230

**Comment by Azaryan-A** [comment] 2023-03-14 11:49
Custom view content 'flickers' even if updating some props via API. for example "customButtons". This problem occurred after updating the version of fullcalendar from v5 to v6. Please check this example - [https://stackblitz.com/edit/github-urj6el-oghacn?file=src%2FDemoApp.jsx](url)

**Comment by nandorojo** [comment] 2023-04-03 03:35
I have the same issue. Whenever I use `eventContent`'s content injection with JSX, the calendar has very noticeable flickers.

I can provide a reproduction tomorrow if it's useful. I'm also willing to sponsor a solution @acerix for what that's worth!

**Comment by austintackaberry** [comment] 2023-04-09 19:01
I am experiencing the same issue as @nandorojo. Whenever I use eventContent's content injection with JSX and I issue a refetchEvents call, all of the events flicker. If I remove eventContent, the flicker goes away. On version 6.1.4

**Comment by nandorojo** [comment] 2023-04-09 19:56
I wonder if there is any potential fix. Or if I could get pointed to the code in charge of this that I could
play with and try to patch.

**Comment by nandorojo** [comment] 2023-04-10 17:58
It's especially noticeable if the max dates isn't true and the order of events changes. Here's a video: https://www.loom.com/share/5626f7eac906400ba46819db73e1590a

**Comment by arshaw** [comment] 2023-05-08 22:50
This should be fixed in [v6.1.7](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.1.7)

Please see my comment on a related issue:
https://github.com/fullcalendar/fullcalendar/issues/7165#issuecomment-1539159874

Please post here on this ticket if you're still experiencing problems after upgrading.

**Closed by arshaw** 2023-05-08 22:50 UTC
Labels: Confirmed, Date/Time Rendering, React Only
