### ISSUE TITLE
TypeError error "second argument to Function.prototype.apply must be an array" when event's className is changed to a string

### ISSUE THREAD

**Issue by urmamb** [fullcalendar/fullcalendar#4141] opened 2018-04-10 15:40 UTC
Until v3.5.1 there is no issue with it but with latar version if i use `updateEvents` it accepts single event while `updateEvent` accept an array of event. Below is the pin to create this bug.

https://codepen.io/urmamb/pen/vRbVYe

or

jsfiddle.net/sbxpv25p/489

its also discussed in here 
https://stackoverflow.com/questions/49677979/fullcalendar-eventmouseover-change-color-of-events-with-same-id

In Detail: 
I am working on eventMouseOve where i face this issue
        
    eventMouseOver:function( event, jsEvent, view ) {
		var newColor = "#000";
                     var sameEvents = $("#calendar").fullCalendar('clientEvents', function(e) { 
			return e.id=== event.id
		});
		$.each(sameEvents, function(x){
			if (event.id== sameEvents[x].id) {
				sameEvents[x].eventColor = newColor;
				sameEvents[x].className = 'sameevent';
				eventCount += 1;
				// console.log(sameEvents);
				calendar.fullCalendar( 'updateEvent', sameEvents);
			}
		});
	},

if use `updateEvents`  for the `sameevent` array it throw this error 
`TypeError: second argument to Function.prototype.apply must be an array fullcalendar.min.js:7:30665`

but if is use `updateEvent` it doesn't show any error.

**Comment by acerix** [comment] 2018-04-11 21:08
Thanks for the detailed report.  I made this simplified test based on yours which shows the problem is only when setting `className` to be a string; works fine if it is an array instead.

https://codepen.io/anon/pen/yKrNry?editors=0010

The documentation says `className` can be a string, so it should be working.

**Comment by arshaw** [comment] 2019-01-01 23:07
this will not be fixed in v3, but it has been fixed in v4 (not yet officially released): https://github.com/fullcalendar/fullcalendar/issues/4189

closing this because wontfix

**Closed by arshaw** 2019-01-01 23:07 UTC
Labels: Confirmed, Event Model, TypeScript
