### ISSUE TITLE
[alpha2] Events not in order by start time in print version

### ISSUE THREAD

**Issue by bbalet** [fullcalendar/fullcalendar#4432] opened 2018-12-31 09:16 UTC
If you compare the behavior of the **print feature** (CTRL+P):

- Codepen for alpha1: https://codepen.io/bbalet/pen/EGbwaY
- Codepen for alpha3: https://codepen.io/bbalet/pen/BvmwaJ

You will notice that since alpha2, the order of events is not correct into the printed preview/page. Indeed, the first event being printed is:
 
    1:00 PM - 2:50 PM
    Microsoft Office ,
    B12-Lab, Rady

Although the first event of the day is:

    7:30 AM - 9:20 AM
    Typing, B12-Lab,
    SopheakROS

I suspect that we loose something by removing Momentjs and that the dates are now sorted out by alpha instead of date or their timestamp.

**Comment by acerix** [comment] 2018-12-31 20:54
It seems the problem is that you event times include a timezone, it works if I remove that:

https://codepen.io/anon/pen/Kbyxgv?editors=0010

The event times should be in the same timezone as the calendar and not include the timezone in the start/end.

**Comment by bbalet** [comment] 2019-01-01 01:31
Ok for the workaround I can convert everything to the local TMZ.

However, it did work with a TMZ in alpha1 (and with previous versions of full calendar). And I must miss something because the docs don't mention the TMZ, just that dates are JS native dates starting from alpha2.

**Comment by bbalet** [comment] 2019-01-02 01:59
I've tried your CodePen with Google chrome, but it doesn'twork:

![fullcalendar_wrong_order](https://user-images.githubusercontent.com/1221546/50578426-89a41700-0e6c-11e9-8813-7c3dc4622e2b.png)

**Comment by acerix** [comment] 2019-01-02 19:18
Thanks for the clarification, I was having trouble seeing the print preview but see the issue now and made a simplified test case:

https://codepen.io/anon/pen/aPEjdB?editors=0010

It seems the events are now printed in the order they are defined instead of when they start.

**Comment by bbalet** [comment] 2019-01-04 03:01
In order to avoid any confusion, I'd like to add that adding timezone to dates has nothing to do with this issue. I've forked your last pen and:

- Add timezone to events.
- Sort the events by dates.

And it is working fine: https://codepen.io/bbalet/pen/yGvqde?editors=0010

So the workaround while waiting for the patch is to sort the events with a simple code such as:

    data.sort(function(a, b) {
      return  new Date(a.start) - new Date(b.start);
    });

**Comment by acerix** [comment] 2019-01-04 23:55
Thanks for the workaround.  

Regarding the timezone, the issue that I get is that the events are not in the correct place in your alpha3 example so the calendar looks mostly empty.  I'm guessing you are in the same timezone (+7) which is why you don't see that issue.

**Comment by bbalet** [comment] 2019-02-12 03:16
Bug still present in beta
Workaround still working in beta

**Comment by arshaw** [comment] 2019-03-08 22:51
fixed in master

**Closed** 2019-03-08 22:51 UTC
Labels: Confirmed, Event Rendering

**Comment by arshaw** [comment] 2019-03-20 21:33
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released) This is fixed.

**Comment by tanoabeleyra** [comment] 2019-07-13 17:43
Is this really fixed?

I'm using v4.2.0 and this is the output of `success: events => console.log(events.map(e => e.start))`:
![image](https://user-images.githubusercontent.com/6851095/61174816-f61a7400-a57b-11e9-9290-93c36f2f4e05.png)

I'm using `.sort()` as a workaround but would like to avoid it.
