### ISSUE TITLE
dayClick event triggered when swiping on Touch devices

### ISSUE THREAD

**Issue by Rouche** [fullcalendar/fullcalendar#3332] opened 2016-09-06 18:45 UTC
### Bug Reports

Hi,

Upgrading from 2.6.1 to 2.9.1, we now get dayClick trigger when swiping.
Is there a way to detect that someone actually swiped? 
->touch on a day and untouched on another day

We use this to change months, but also to switch on day view when the touch and untouch is on the same day slot.

Very simple:
Just use the window version F12 in chrome and select any mobile device.
Swipe from a day to another.
http://jsbin.com/xoputep/edit?html,js,output

Thanks.

**Comment by Rouche** [comment] 2016-09-06 19:41
Additional Note: We are using fullcalendar with Angular. For the swipe, we register ng-swipeleft/right. And adjust the visible  month accordingly.

I can patch by flagging a variable to ```swiping = true``` but its a bit ugly.

**Comment by LilBiggs** [comment] 2016-09-08 15:47
I ran across an issue similar to this. Here are my finding below on the jsbin from an above comment.

Set longPressDelay: 0, 

- No longer can reproduce

Set longPressDelay: (default, 1000ms): 

- Click on 11/4 -> drag to 11/6 and release. Day Click is raised and the date is 11/4
- Click on 11/4 -> hold down for at least 1 second, then drag to 11/6. Day click is not raised
- Click on 11/4 -> drag to 11/6. Continue to hold down on 11/6 for at least 1 second. Day Click is raised and the date is 11/4

It seems like it has to do with the longPressDelay setting.

**Comment by strokyl** [comment] 2016-10-27 09:38
I have the same issue on chrome mobile on my wiko ride 4G (Android 5.0.2). I can't reproduce it on desktop with chrome dev.

**Comment by arshaw** [comment] 2016-11-01 05:47
Ah ok, I thought this issue was something else. I was able to easily reproduce.

The solution will entail enforcing a certain pixel threshold that the touch+drag must not exceed in order to qualify for a day click.

Must also ensure that the "swipe" event (is it native or specific to Angular?) gets fired.

**Comment by Rouche** [comment] 2016-11-01 12:29
Dwipe event is specific to Angular module ngTouch. The module already compute a threshold before triggering swipe.
ngTouch uses 
-touchstart / mousedown 
-touchmove / mouse move (in between)
-touchend / mouse up (then computes)

ngTouch is a bit buggy tough there are a lot better modules, just the dayClick needs to be sorted out, clients can take care of the rest.

**Comment by Doc999tor** [comment] 2017-01-30 17:47
Anybody has found a solution?  
I'm trying to bring HammerJS for swiping detection.  
HammerJS events don't fire, dayClick touchend event fires.  
longPressDelay set to 0 helps but I need it for correct mobile functionality.  
Can I simulate longPressDelay?

**Comment by Rouche** [comment] 2017-01-30 18:17
For us, we intercept the swipe start with mobileangularui ```$swipe``` service. (ng-swipe-left / right)

Flagging a variable ```swiping```

Ugly, but no real other choice.

**Comment by Doc999tor** [comment] 2017-01-30 20:31
How do you intercept the event handling? I see the fullcalendar blocks event "bubbling", other event listeners don't get the event.  
I don't care whether `dayClick` will fire or not, I do care other libraries don't get the event.  
Thanks

**Comment by Rouche** [comment] 2017-01-30 20:46
Oh this is different. I had no solution for this one. Except modifying fullcalendar to not call ```stopPropagation()``` I did not need to fix this one luckylly.

**Comment by Doc999tor** [comment] 2017-01-31 18:27
Nice idea, it works when I add a transparent layer above the calendar. But I lose all the interactions with the calendar.

**Comment by arshaw** [comment] 2017-02-14 22:50
Fixed in [v3.2.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.2.0)

If the user begins a touch interaction, and anything begins to scroll OR if they move their touch outside of the day where the touchstart happened, `dayClick` won't be fired.

**Closed by arshaw** 2017-02-14 22:50 UTC
Labels: Confirmed, Merged, Touch

**Comment by hsuanweifu** [comment] 2018-05-09 01:27
Angular 4.4.4
ionic-angular: 3.8.0
Full Calendar: 3.5.2

The first swipe will work as expected but the second swipe will still trigger day click.
You will have to click somewhere else and then swipe to avoid triggering day click.
