### ISSUE TITLE
Google private calendar

### ISSUE THREAD

**Issue by ItaloQualisoni** [fullcalendar/fullcalendar#2868] opened 2015-09-16 14:27 UTC
Hello,

I've been searching about this topic, is it possible to use fullcalendar with a private google calendar using OAuth 2.0 or similar?

It worked using a public calendar, but we are building an intranet and the information must be private...

Also is there any available workaround until this feature stay available?

**Comment by arshaw** [comment] 2015-10-11 16:37
duplicate of #2642

**Closed by arshaw** 2015-10-11 16:37 UTC
