### ISSUE TITLE
dateClick with named timeZone returns incorrect getDate()

### ISSUE THREAD

**Issue by larsinsd** [fullcalendar/fullcalendar#4685] opened 2019-05-15 01:14 UTC
When using a named timeZone parameter, the dateClick date object returns the wrong date. It does work with the default "local" timeZone, but if you use another (e.g., America/Los_Angeles), the info.date.getDate() returns one day prior (if you click on the 9th, it will return a value of 8).

The CodePen should make it easy to see:

https://codepen.io/larsinsd/pen/LoxRLV

And thank you for all you do. Your calendar program is great!

**Comment by acerix** [comment] 2019-05-15 19:56
The days start at midnight UTC but the date object is in localtime so it will be the day before when the timezone is before UTC. You can use dateStr to get the correct date without any timezone.

Duplicate of #4392

**Closed** 2019-07-25 15:50 UTC
Labels: Discussing, View Interaction
