### ISSUE TITLE
Vertical Resource View in agendaDay hide empty resources

### ISSUE THREAD

**Issue by tufanayd** [fullcalendar/fullcalendar#3247] opened 2016-06-26 07:26 UTC
Hi,

How can I hide the resources which doesn't have any events based on the day change?

**Comment by arshaw** [comment] 2016-06-27 23:27
duplicate of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/98
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2016-06-27 23:27 UTC
