### ISSUE TITLE
FullCalendar getEventSources after removeEventSources is not updated properly

### ISSUE THREAD

**Issue by Valkhan** [fullcalendar/fullcalendar#3641] opened 2017-04-24 12:44 UTC
Hi, first of all my congratulations for this masterpiece!

Fiddle: https://jsfiddle.net/Valkhan/4pLp5qym/

The title pretty much says it all, after using: removeEventSources, the first element that you try to add by using: addEventSource will shown on calendar but won't be accessible by getEventSources, I did a quick workaround but surely this should be fixed on the core files.

```javascript //-- Workaround: 
$cal.fullCalendar('removeEventSources');
//-- add a blank array
$cal.fullCalendar('addEventSource',[]);
//-- Now just everything works as it should
$cal.fullCalendar('addEventSource',options.eventSources[0]);
$cal.fullCalendar('addEventSource',options.eventSources[1]);

**Comment by arshaw** [comment] 2017-04-27 22:05
Confirmed, thanks!

It's because `removeEventsSources` will completely clear out the sources array:
https://github.com/fullcalendar/fullcalendar/blob/v3.4.0/src/EventManager.js#L434

But it forgets that we reserve the first event source as the "sticky" event source:
https://github.com/fullcalendar/fullcalendar/blob/v3.4.0/src/EventManager.js#L43

**Comment by arshaw** [comment] 2019-07-30 20:06
it'd be great if we could repro this in v4

**Comment by arshaw** [comment] 2020-06-25 16:43
probably fixed in v5

**Closed by arshaw** 2020-06-25 16:43 UTC
Labels: Event Model, Reproducing
