### ISSUE TITLE
Please add OptionsInput to the fullcalendar.d.ts exports

### ISSUE THREAD

**Issue by elebetsamer** [fullcalendar/fullcalendar#4006] opened 2018-01-10 07:53 UTC
I just moved from using fullcalendar v3.6.2 along side `@types/fullcalendar` v3.5.0 to fullcalendar v3.8.0.

The conversion has gone fine with the exception of not having a type exported in the 3.8.0 type definitions file for the options to pass through to the jquery fullcalendar method. It looks like the method expects an object of type `OptionsInput`, but that interface isn't exported in the main fullcalendar type definition.

For now I've had to pass my options with type `any`. It works for now, but isn't ideal.

![image](https://user-images.githubusercontent.com/75610/34760334-54a1ed3a-f594-11e7-84da-b482d3b16712.png)

![image](https://user-images.githubusercontent.com/75610/34760376-7db4cc9c-f594-11e7-8bc8-fd7711579ddc.png)

Thanks.

**Comment by acerix** [comment] 2018-01-10 21:01
`fullcalendar.d.ts` is automatically generated, maybe your just need to build the new version? I don't get that error and my `fullcalendar.d.ts` has the `export interface OptionsInput` which is defined here:

https://github.com/fullcalendar/fullcalendar/blob/92208844819bd1638b5c6eda0daf93ffddde0b26/src/types/input-types.ts#L247

**Comment by elebetsamer** [comment] 2018-01-10 21:27
The `fullcalendar.d.ts` does contain the `OptionsInput`, but it isn't exported at part of the main `fullcalendar` module. So when you are just trying to import members from the `fullcalendar` module, that interface isn't part of it.

You can see from the `fullcalendar/src/exports` module below, that `OptionsInput` isn't part of the `export`.

https://github.com/fullcalendar/fullcalendar/blob/2765b9fded569c5861d28251569e1e642723210b/dist/fullcalendar.d.ts#L2608-L2611

https://github.com/fullcalendar/fullcalendar/blob/2765b9fded569c5861d28251569e1e642723210b/dist/fullcalendar.d.ts#L2566-L2577

https://github.com/fullcalendar/fullcalendar/blob/2765b9fded569c5861d28251569e1e642723210b/dist/fullcalendar.d.ts#L2455-L2511

**Comment by bendykowski** [comment] 2018-02-06 10:31
I've created a PR for the same thing here #4040 a few days ago. It seems my issue which I've created for that PR here #4041 can be closed due to being a duplicate of this issue. The only difference between them is that I've fixed two functions' definitions to be compliant with the documentation.

**Comment by acerix** [comment] 2018-02-06 21:26
Thanks, didn't notice the duplicate.

**Comment by arshaw** [comment] 2018-03-04 22:27
i've queued #4040 for release

**Closed by arshaw** 2018-03-04 22:27 UTC
Labels: Discussing, TypeScript

**Comment by arshaw** [comment] 2018-03-05 03:46
released in [v3.9.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.9.0)
