### ISSUE TITLE
Background Events do not fire when with dayGridMonth uses single day Dates

### ISSUE THREAD

**Issue by LaetisLEH** [fullcalendar/fullcalendar#4785] opened 2019-07-19 16:04 UTC
Hi, 
Using Fullcalendar V4, I am loading single day events only and using dayGridMonth default view. When i load consecutive days (like in my code), the background click event does not work on the first grid cells of the calendar row (as well as classes are not rendered. The last item works).
this problem does not appear by using Event ranges. 

[Codepen link](https://codepen.io/Leo12/pen/gVawLB)

```
new FullCalendar.Calendar(ElementId, {
	plugins: ['dayGrid','dayGrid'],
	eventClick: function(props) {
	  console.log(data);
	},
	locale: 'fr',
	defaultView:'dayGridMonth',
	events:  [
        {
          className: 'yellow',
          start: '2019-09-16',
          end: '2019-09-16',
          rendering: 'background'
        },
        {
          className: 'red',
          start: '2019-09-17',
          end: '2019-09-17',
          rendering: 'background'
        },
        {
          className: 'blue',
          start: '2019-09-18',
          end: '2019-09-18',
          rendering: 'background'
        },
        {
          className: 'black',
          start: '2019-09-18',
          end: '2019-09-19',
          rendering: 'background'
        }
      ],
	]
});
```

**Comment by acerix** [comment] 2019-07-19 21:19
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

It sounds like it might be the same as this issue:

https://github.com/fullcalendar/fullcalendar/issues/4750
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by LaetisLEH** [comment] 2019-07-22 07:58
Thanx for your reply. i have added a [codepen link](https://codepen.io/Leo12/pen/gVawLB)
It may be related with #4750

**Comment by arshaw** [comment] 2019-07-25 21:32
thanks for the report.

I'll treat 4750 and this issue as the same. i'll close this issue
#4750
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2019-07-25 21:32 UTC
Labels: Confirmed, Event Interaction
