### ISSUE TITLE
eventOrder, precedence over date/duration

### ISSUE THREAD

**Issue by pedromendesws** [fullcalendar/fullcalendar#2907] opened 2015-10-21 10:53 UTC
Hi,

I'd like to request a feature that is kind of what has been requested here https://code.google.com/p/fullcalendar/issues/detail?id=364, but not exactly.

eventOrder allows a custom sort when the start dates and durations are equal. What I wanted was to override the sort event in any situation.

For example if I have an event that has a duration of 2 days, but starts at 10AM I want it to appear before my 1 hour duration event that starts at 9AM. Example image in the attachs.

Actually I only see this being usefull in the month view. Is this possible?

![fullcalendarcustomsort](https://cloud.githubusercontent.com/assets/15229856/10634510/3d67d1ea-77ea-11e5-8e36-3ed619372111.png)

Thank you!

**Comment by arshaw** [comment] 2016-01-12 07:28
same request from @sboele:
> The current eventOrder funcionality: "Determines the vertical ordering events that have the same dates / times." according to the docs. It would be nice if you could change the order of the events by sorting by other properties first before sorting date/time. Now it only uses this option when events have the same date/time and duration. This way you can 'group' events together in a day view. For example: open and closing timewindows that are on the same day but you want them grouped together.

**Comment by matiaslarsson** [comment] 2016-04-27 08:37
Yes, please! Of course one can monkey patch compareEventSegs to, for example, remove the duration check but setting eventOrder specifically should really do what is says on the box. ;)
```
// A cmp function for determining which segments should take visual priority
compareEventSegs: function(seg1, seg2) {
	return seg1.eventStartMS - seg2.eventStartMS || // earlier events go first
		//seg2.eventDurationMS - seg1.eventDurationMS || // tie? longer events go first
		seg2.event.allDay - seg1.event.allDay || // tie? put all-day events first (booleans cast to 0/1)
		compareByFieldSpecs(seg1.event, seg2.event, this.view.eventOrderSpecs);
}
```

**Comment by nafg** [comment] 2016-05-29 08:40
Any chance of this being implemented soon?

**Comment by rahulthewall** [comment] 2016-08-18 13:40
Any updates on this?

**Comment by rodogir** [comment] 2016-08-18 13:45
Would really like to see this implemented as well.

**Comment by harohl** [comment] 2016-10-06 15:26
I would like to control the event stacking on the Scheduler timeline view.  Our schedule has standby and superseded schedules that I would like to display below the active/primary schedule.

**Comment by Huzefa-lms** [comment] 2017-01-20 12:37
To achieve sorting with custom event object parameter in existing code please replace **compareEventSegs** with the below function. I have used **eventOrder** as custom parameter in event object

compareEventSegs: function(t, e) {
        return sortEventByCustomParam(t.event, e.event);
}

and add the below function in fullcalendar.js, this function fill sort the event in ascending order using **eventOrder** field

function sortEventByCustomParam(prevEventObj, nextEventObj) {
        if(prevEventObj.eventOrder < nextEventObj.eventOrder){
            return -1; 
        }
        else{
            return 1; 
        }
    }

**Comment by mitgninnug** [comment] 2017-02-09 13:40
cheers @Huzefa-lms , that sort of worked for me, but not quite what I needed but pointed me in the right direction.
I changed the existing compareEventSegs function to the following:
`	compareEventSegs: function(seg1, seg2) {
		return seg1.eventOrder - seg2.eventOrder || // earlier events go first
			seg2.eventDurationMS - seg1.eventDurationMS || // tie? longer events go first
			seg2.event.allDay - seg1.event.allDay || // tie? put all-day events first (booleans cast to 0/1)
			compareByFieldSpecs(seg1.event, seg2.event, this.view.eventOrderSpecs);
	}`

which got rid of the times comparison and replaced it with the eventOrder
cheers

**Comment by arshaw** [comment] 2017-07-14 22:17
I agree with the general sentiment. I think `eventOrder` should be responsible for specifying the order BEFORE date/duration. I think eventOrder should be repurposed, and have the following default:

```js
[ "date", "duration", "allDay" ]
```

That would make it consistent with the current default behavior.

Then you could add your own sorting props:

```js
eventOrder: [ "myprop", "date", "duration", "allDay", "anotherprop" ]
```

**Comment by aqil-tariq-confiz** [comment] 2017-09-11 11:35
Hello, guys!
I am uploading a fiddle [example](http://jsfiddle.net/aqiltariq65/jso51pm6/126/).
I want to override the duration feature in this example.
I required this sorting in my fiddle example:
1. 3 Meeting 
2. 1 Meeting 
3. 2 Meeting
Any help in overriding the property of duration.

**Comment by CapDev** [comment] 2017-10-27 17:17
The eventOrder option was working as intended for me up to and including the 3.4.0 release.

[3.4.0 example](https://codepen.io/CapDev/pen/rYBver)

[3.6.2 example](https://codepen.io/CapDev/pen/MOgVPv)

In the latest version above you can see that using an Event Object standard field for the eventOrder property will sort the events. Also removing the eventOrder option will sort by events by 'title' as default.

If the eventOrder property is changed to the non-standard field it breaks and sorts the events in the order of provided data and does not fall back to the default sort of the 'title' field.

The compareEventSegs function has changed after 3.4.0 and i have been unable to modify it to produce the same order as before.

Thanks for taking a look when you can.

**Comment by Charoday** [comment] 2017-11-01 08:34
Hello!
I want to implement the order of events as in the screenshot. To purple events are always located on the bottom edge, despite the time of the beginning of the event. I tried to specify the sort order in the form of an array, as a function, but the order does not change.

![image](https://user-images.githubusercontent.com/17511259/32266119-bf9ad7d0-bf18-11e7-832b-b40688cb8e7b.png)

**Comment by archemedia** [comment] 2017-11-01 10:16
would it be possible also to 'stick' events vertically, so that all events from the same source have their own horizontal 'lane'. I posted an example here: https://stackoverflow.com/questions/46684181/fullcalendar-timeline-vertical-stacking

**Comment by Huzefa-lms** [comment] 2017-11-01 10:47
Hello,

I suggest FusionChart Gantt Chart over fullcalendar because it will fulfill
your need.

Check the demo by clicking the below link
https://www.fusioncharts.com/charts/gantt-charts/

Regards,

*Huzefa Ratlamwala.*

*Sr. Software Engineer.*
*LMS Solution India Pvt. Ltd.*

**Comment by Huzefa-lms** [comment] 2017-11-01 10:49
Please contact fullcalendar support for this because they will give you a
proper solution for this problem.

*Huzefa Ratlamwala.*

*Sr. Software Engineer.*
*LMS Solution India Pvt. Ltd.*

**Comment by Charoday** [comment] 2017-11-01 13:42
Thanks a lot! But I will look for a solution to the problem with this library.

**Comment by fabio-a-beretta** [comment] 2018-05-21 22:51
Hello,

any news on this ordering feature? I would need it as well.

Thanks,
Fabio

**Comment by arshaw** [comment] 2018-10-02 06:40
This issue has been addressed in the latest alpha release (4.0.0-alpha.2)
[See the blog post &raquo;](https://fullcalendar.io/blog/2018/10/release-v4-alpha2)

https://fullcalendar.io/docs/v4/eventOrder

**Comment by arshaw** [comment] 2018-12-26 04:59
I'm closing this issue to signify that it's implemented (since v4-alpha2). I'll comment on this thread again when v4 is officially released.

**Closed by arshaw** 2018-12-26 04:59 UTC
Labels: Accepted, Breaking Change, Event Arrangement

**Comment by arshaw** [comment] 2019-03-20 21:16
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
