### ISSUE TITLE
ERROR in node_modules/@fullcalendar/core/main.d.ts: error TS1110: Type Expected

### ISSUE THREAD

**Issue by kellehbeans10** [fullcalendar/fullcalendar#4762] opened 2019-07-05 15:18 UTC
I have a problem with @fullcalendar/core/main.d.ts module in a React project. The error is:

` Error - node_modules/@fullcalendar/core/main.d.ts: error TS1110: Type Expected. `

It is also throws the same error for daygrid. Is this a known problem?

**Comment by acerix** [comment] 2019-07-05 21:46
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If the error is specific to the React component, please post in this repo:

https://github.com/fullcalendar/fullcalendar-react

**Comment by kellehbeans10** [comment] 2019-07-06 13:17
@acerix thanks for replying. I've created a stackblitz but I'm not sure I've added enough details: https://react-8mrkyf.stackblitz.io please let me know if you need anything else. 

As for being React related, it probably is. Is there a possibility that you can move the topic? 

Sorry again.

**Comment by acerix** [comment] 2019-07-09 21:20
The stackblitz demo isn't working for me, I just get an error "Preset not sepcified in configuration".

You could try the same code in the Standard template to see if it works outside of React:

https://fullcalendar.io/reduced-test-cases

I can't move the issue but you can just close this issue and open a new one and include a link to this issue.

**Comment by arshaw** [comment] 2019-07-25 20:55
usually errors like this means you're running on old version of typescript. what version are you running @kellehbeans10

**Closed** 2020-06-29 15:25 UTC
Labels: Reproducing, TypeScript
