### ISSUE TITLE
Conflict with mootools-core js

### ISSUE THREAD

**Issue by skiran-vs** [fullcalendar/fullcalendar#5199] opened 2019-12-27 09:35 UTC
Hi,

Im trying to use the trial version of the scheduler add-on. I added the libraries from the file "fullcalendar-scheduler-4.3.1.zip" to the project with the "Script Tags" method but when i try to use it with mootools-core JS it gives an error in the browser console like this:
![jserror](https://user-images.githubusercontent.com/59280081/71511513-ef19c080-2892-11ea-89a4-3de101070ec6.png)

As you can see the schedular library tries to use to mootools-core-2.js library.
I tried it with the given "vertical-resource-view.html" example. It works good without the mootools-core js but when i add the mootools-core library it gives an error like on the picture.
Is there a solutions for this problem ?

thanks

**Comment by acerix** [comment] 2019-12-27 21:40
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by skiran-vs** [comment] 2019-12-30 10:48
Here can you find the reproduction scenario:
https://codepen.io/skiran-vlot/pen/vYEeBpq?&editable=true&editors=001

**Comment by acerix** [comment] 2019-12-30 19:43
Thanks, I can see including mootools 1.4.5 causes type errors in the calendar code.  It seems to be fixed with mootools 1.6.0:

https://codepen.io/acerix/pen/zYxEqGE?editors=0010

**Comment by arshaw** [comment] 2020-06-29 21:22
mootools is probably monkeypatching. wontfix

**Closed by arshaw** 2020-06-29 21:22 UTC
Labels: Confirmed, Weird Environment
