### ISSUE TITLE
Import error with snowpack and typescript

### ISSUE THREAD

**Issue by abumalick** [fullcalendar/fullcalendar#5881] opened 2020-10-04 12:05 UTC
### Reduced Test Case

https://github.com/abumalick/snowpack-fullcalendar

### Bug Description

Using snowpack with typescript as a bundler, when I try the example React implementation of the library. I got an error:
```
Uncaught Error: Please import the top-level fullcalendar lib before attempting to import a plugin.
```

### Screenshots
![image](https://user-images.githubusercontent.com/8377185/95014938-3911ad00-0642-11eb-869f-1a2ca48857e1.png)

**Comment by abumalick** [comment] 2020-10-04 12:05
https://github.com/fullcalendar/fullcalendar/blob/5187127f72b66dab67913f65f4fe2a64bbc98d46/packages/common/src/vdom.ts#L6

**Comment by abumalick** [comment] 2020-10-04 12:19
I tested with create react app and typescript, it works normally. It must be related to the way snowpack works

**Comment by abumalick** [comment] 2020-10-04 12:26
Opened a discussion at snowpack: https://github.com/pikapkg/snowpack/discussions/1207

**Comment by mlarue** [comment] 2020-10-06 13:46
I noticed the same problem with snowpack and LitElement

**Comment by arshaw** [comment] 2020-12-15 16:09
The snowpack discussion you link provides a workaround.

To fix the root problem, the fullcalendar packages shouldn't rely on import execution order. This will be something I implement in v6

**Comment by charkour** [comment] 2021-03-01 00:10
The workout is not very clear, any suggestions? I have made a repo that reproduces the error here: [link](https://github.com/charkour/course-schedulizer-snowpack). The snowpack react app is in `client-course-schedulizer`. Clone the repo, navigate to the snowpack client app, `npm i && npm start`

**Comment by charkour** [comment] 2021-03-01 02:26
I was able to resolve it by importing from `@fullcalendar/react/dist/vdom.js` rather than from the `core` package. 

```tsx
import React from "react";
import "@fullcalendar/react/dist/vdom.js";
import FullCalendar from "@fullcalendar/react";
import type { CalendarOptions } from "@fullcalendar/common";
import interactionPlugin from "@fullcalendar/interaction"; // needed for dayClick
import timeGridPlugin from "@fullcalendar/timegrid"

export const Calendar = (props: CalendarOptions) => {
  return (
    <>
      <FullCalendar {...props} />
    </>
  );
};
```

**Comment by mylastore** [comment] 2021-05-04 16:27
> I was able to resolve it by importing from `@fullcalendar/react/dist/vdom.js` rather than from the `core` package.
> 
> ```tsx
> import React from "react";
> import "@fullcalendar/react/dist/vdom.js"; // KEY CHANGE
> import FullCalendar from "@fullcalendar/react";
> import type { CalendarOptions } from "@fullcalendar/common";
> import interactionPlugin from "@fullcalendar/interaction"; 
> import timeGridPlugin from "@fullcalendar/timegrid"
> 
> export const Calendar = (props: CalendarOptions) => {
>   return (
>     <>
>       <FullCalendar {...props} />
>     </>
>   );
> };
> ```

this work for me also with `@sveltejs/kit`

**Comment by marcoroth** [comment] 2022-11-14 11:09
> `import '@fullcalendar/core/vdom.js'`

Thanks @mylastore! This also solved it for me for vanilla JS!

**Comment by arshaw** [comment] 2022-12-15 21:17
Fixed in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0). The workaround is no longer necessary

**Closed by arshaw** 2022-12-15 21:17 UTC
Labels: Confirmed, Alt Environment

**Comment by marcoroth** [comment] 2022-12-20 23:14
I can confirm, this seems to be fixed in `v6.0.0`. Thanks @arshaw!
