### ISSUE TITLE
Modifying the event in eventMouseEnter breaks eventClick and the event URL

### ISSUE THREAD

**Issue by timlassiter11** [fullcalendar/fullcalendar#5153] opened 2019-11-26 19:33 UTC
eventClick and event URLs not working when calling setProp inside the eventMouseEnter event.
Commenting out `info.event.setProp()` fixes the issue.

Tested against version 4.3.1.

# Reduced Test Case ([Codepen](https://codepen.io/exypnos/pen/PoorRgm))
```javascript
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'dayGrid' ],
        events: [
            {
                title  : 'event',
                start  : new Date(),
                url : 'www.google.com'
            }
        ],
        eventClick: function (info) {
            alert("Clicked!!");
        },
        eventMouseEnter: function (info) {
            info.event.setProp('backgroundColor', '#00CCFF');
        }
    });

    calendar.render();
});
```

**Comment by acerix** [comment] 2019-11-26 22:58
Thanks, confirmed.

The issue is that `setProp` causes the event to rerender with a new element, and clicking on that new element triggers another `mouseenter` on it, which replaces the element again before the click callback.

I couldn't find a good workaround, but for this specific example you could change the background with CSS to avoid replacing the event element.

Otherwise you could put the "onclick" code in eventMouseEnter and keep track of whether the mouse is over the event to know which code to run.

**Comment by timlassiter11** [comment] 2019-11-27 11:54
@acerix - Is there any way to get all elements involved in a FullCalendar event (not JS event)? For example, if I have an event that lasts a week, the elements are split between the two different weeks. The element passed to the event handler is just the one involved in the event. Changing the background with CSS will only change one part of the entire event. I updated the [Codepen](https://codepen.io/exypnos/pen/PoorRgm?editors=0010) to show this. 

If there is no way to do this I will just go with options number two. 

Thanks for the help!

**Comment by acerix** [comment] 2019-11-28 18:48
There is no built-in way but it can be done if you add a unique class to each event since that can be used to select all it's elements:

https://codepen.io/acerix/pen/RwwXqzW?editors=0010

**Comment by timlassiter11** [comment] 2019-12-09 12:08
Thanks for this. It makes perfect sense and works as expected.

**Comment by arshaw** [comment] 2020-06-29 20:44
I can't repro this in the original codepen link (and yes I'm uncommenting the `setProp` call), but anyway, this is almost definitely fixed in v5

**Closed by arshaw** 2020-06-29 20:44 UTC
Labels: Confirmed, Event Point/Select
