### ISSUE TITLE
EventLimit More event dialog not appearing in the last date / corner side events 

### ISSUE THREAD

**Issue by sudheeshv** [fullcalendar/fullcalendar#3282] opened 2016-07-22 03:24 UTC
More events popup not appearing correctly if the event coming the right border or corner. 
[screenshot attached and jsbin demo also added]

### Bug Reports
http://jsbin.com/xaxuge/edit?html,console

![image](https://cloud.githubusercontent.com/assets/2003489/17045721/b1598db4-4fe9-11e6-8426-3ee8943ac4c1.png)

![image](https://cloud.githubusercontent.com/assets/2003489/17047054/60999b9a-4ff7-11e6-80f1-8900aa6c2a4c.png)

**Comment by arshaw** [comment] 2016-07-26 06:52
duplicate of
https://github.com/fullcalendar/fullcalendar/issues/3232
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2016-07-26 06:52 UTC

**Comment by sudheeshv** [comment] 2016-07-26 07:09
@arshaw yes i have modified the same for my solution its f=working fine for me also. Thank You :)
