### ISSUE TITLE
allDayText with localization

### ISSUE THREAD

**Issue by phillylovepark** [fullcalendar/fullcalendar#3265] opened 2016-07-07 09:05 UTC
When trying to set the allDayText property with a localized calendar, it seems that the translated string overwrites the property.

[Here is the jsbin for testing](http://jsbin.com/soxeramewa/edit?html,js,output). If you remove the translation script file, the custom text is displayed.

**Comment by arshaw** [comment] 2016-07-09 07:43
reproduced.

the bug is caused by the language defining the text with allDayHtml (an undocumented option) and allDayText does not have the power to override it. if you set `allDayHtml` instead you can probably make it work

**Comment by phillylovepark** [comment] 2016-07-12 07:46
Yes, setting `allDayHtml` makes it work. Many thanks!

**Comment by arshaw** [comment] 2020-06-24 15:40
fixed in v5 (and maybe even v4)

**Closed by arshaw** 2020-06-24 15:40 UTC
Labels: Confirmed, i18n
