### ISSUE TITLE
Event(as a json feed) and Agenda View GET params for start and end issue

### ISSUE THREAD

**Issue by jjjy** [fullcalendar/fullcalendar#4219] opened 2018-06-18 09:45 UTC
In one of the documents for events, it stated that 

"FullCalendar will determine the date-range it needs events for and will pass that information along in GET parameters.
The GET parameter names will be determined by the startParam and endParam options. ("start" and "end" by default).
The values of these parameters will be ISO8601 date strings (like 2013-12-01). For precise behavior, see the timezone docs."

One of the example is 
/myfeed.php?start=2013-12-01&end=2014-01-12&_=1386054751381

However, while in agenda view (agendaWeek or agendaDay), the start and end params would be passed along with timestamp as well when I exceeded the cached time period of the month.

eg. the calendar is first loaded in month view with the following url
/myfeed.php?start=2014-12-01&end=2014-12-31&_=1386054751381

Then when we switch to agendaWeek view, this would be the url and it load properly.
/myfeed.php?start=2014-12-01&end=2014-12-07&_=1386054751382.

However, when we shift previous week in agendaWeek beyond 2014-12-01, the params passed to back end would consist of 
/myfeed.php?start=2014-11-24T00:00:00&end=2014-11-30T00:00:00&_=1386054751383.
instead of 
/myfeed.php?start=2014-11-24&end=2014-11-30&_=1386054751383.

Is there any inconsistency of the date and datetime in the method to GET parameters?
or is there any missing setting like timezone:false to call only the date in the URL?

Thanks,
jy

**Comment by acerix** [comment] 2018-06-19 22:03
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by jjjy** [comment] 2018-06-20 01:40
[](https://codepen.io/anon/pen/KeQvQy)

I tried to produce a sample. It is not a really a bug per se. 
But more of an inconsistency of webservice call.

So in the codepen example.
When you turn on developer tool, in the **Network** segment,
In Month and List view,  when we click on prev/next, this would result in a webservice call of
**_First Example:_** 
https://codepen.io/anon/pen/aKqyWR.js?start=2018-07-01&end=2018-08-12&_=1529457887208

However in Agenda view (agendaWeek/agendaDay), this would result in a webservice call of
**_Second Example:_** 
https://codepen.io/anon/pen/aKqyWR.js?start=2018-06-10T00%3A00%3A00&end=2018-06-17T00%3A00%3A00&_=1529457887215

Could the web service call in the GET parameter be such that it would call in the same service, resulting in the first example? So that there is consistency, rather than having difference service.

Thanks,
Junyi

**Comment by acerix** [comment] 2018-06-20 18:35
Thanks for the demo and additional info. 

The difference is that in month/list view it's only possible for the range to be entire days, but agenda view allows for the range to start/end at a specific time of day.  So, the time can be excluded in month view since it would always be 00:00:00, and the date is still valid ISO8601 without the time.  

The server should just assume the time is midnight when it gets a range without times.

**Comment by Sublime1** [comment] 2019-02-27 13:00
I can confirm this issue too - when you switch to "Week" mode the next/prev buttons send the values of "start" and "end" in YYYY-MM-DDT00:00:00 format, instead of the expected YYYY-MM-DD.

**Comment by acerix** [comment] 2019-02-27 21:06
It doesn't seem like a bug, but should be documented that it can be either a date or a date witha time:

https://fullcalendar.io/docs/startParam

**Comment by arshaw** [comment] 2019-03-06 23:03
dup of https://github.com/fullcalendar/fullcalendar/issues/3593 i believe

i won't fix this in v3, but it's already fixed in v4beta

**Closed by arshaw** 2019-03-06 23:03 UTC
Labels: Discussing, Docs, Event Source
