### ISSUE TITLE
always show more-events-popover with eventLimit 0

### ISSUE THREAD

**Issue by pauldemian** [fullcalendar/fullcalendar#2978] opened 2015-12-22 13:52 UTC
Hey,

I am looking for a way to show the "show more" box (which can be triggered by setting the eventLimit property to a positive number) for all dates, which have events.

I assumed that this could be done by setting the eventLimit to 0, but this is interpreted as "false".
See: http://jsbin.com/cubedi/edit?js,output

Right now I create the missing elements manually, which might cause some problems now or then.

Thanks!

**Comment by mrhaw** [comment] 2016-04-29 23:59
This would be awesome!

**Comment by froasiooneloop** [comment] 2016-06-02 14:36
This would be great. It is very common in a month view to have a yes/no event indicator, no matter how many of them you have.

**Comment by evgeniynickolaev** [comment] 2016-11-02 16:05
Maybe someone knows a workaround for this to make a dirty solution until the issue is closed?

**Comment by acontreras89** [comment] 2018-04-19 09:40
Indeed there are unnecessary tests for truthiness. See `BasicView` [for an example.](https://github.com/fullcalendar/fullcalendar/blob/5af235874b3fd95b57ec9f632e2e8b9e8c26f6c3/src/basic/BasicView.ts#L179-L181)

Simply using `typeof eventLimit === 'number'` would already be a test for definition. This seems pretty much unintended.

@arshaw would you take a PR on this?

**Comment by lbrevity** [comment] 2018-05-22 13:01
Any update on this "More available" ?

**Comment by arshaw** [comment] 2020-04-14 05:49
this is fixed in [the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

**Comment by acontreras89** [comment] 2020-04-14 09:30
@arshaw should we close #4169 then?

**Comment by arshaw** [comment] 2020-06-22 22:14
works in v5 with `dayMaxEvents:0`, which has [just been officially released](https://codepen.io/arshaw/pen/PoZmPjV?editable=true&editors=001).

https://codepen.io/arshaw/pen/PoZmPjV?editable=true&editors=001

**Closed by arshaw** 2020-06-22 22:14 UTC
Labels: Accepted, Event More/Popover
