### ISSUE TITLE
Clicking a selectable date then changing an option right after the calendar is displayed can result in "component.context is undefined" error 

### ISSUE THREAD

**Issue by Phibedy** [fullcalendar/fullcalendar#5270] opened 2020-02-23 13:59 UTC
### Bug Reports
This one is quite hard to reproduce (not just a small code snippet).
Version: 4.4.0

How to reproduce it:
* click a day in the dayGrid view -> (select) while the Fullcalendar is rerendered  by react (useMemo).
This happens in our tests as the day is clicked as soon as it exists. In parallel some other data changes causes a rerender.
I guess that the click happens in the old calendar while it is removed from the dom and replaced by the new one.
```
TypeError: component.context is undefined
../node_modules/@fullcalendar/core/main.esm.js/Slicer</Slicer.prototype._sliceDateSpan
node_modules/@fullcalendar/core/main.esm.js:8519

  8516 | if (!dateSpan) {
  8517 |     return [];
  8518 | }
> 8519 | var eventRange = fabricateEventRange(dateSpan, eventUiBases, component.context.calendar);
       | ^  8520 | var segs = this.sliceRange.apply(this, [dateSpan.range].concat(extraArgs));
  8521 | for (var _a = 0, segs_1 = segs; _a < segs_1.length; _a++) {
  8522 |     var seg = segs_1[_a];

memoize/<
node_modules/@fullcalendar/core/main.esm.js:1552

  1549 | return function () {
  1550 |     if (!args || !isArraysEqual(args, arguments)) {
  1551 |         args = arguments;
> 1552 |         res = workerFunc.apply(this, arguments);
       | ^  1553 |     }
  1554 |     return res;
  1555 | };

../node_modules/@fullcalendar/core/main.esm.js/Slicer</Slicer.prototype.sliceProps
node_modules/@fullcalendar/core/main.esm.js:8446

  8443 | var eventUiBases = props.eventUiBases;
  8444 | var eventSegs = this.sliceEventStore.apply(this, [props.eventStore, eventUiBases, dateProfile, nextDayThreshold, component].concat(extraArgs));
  8445 | return {
> 8446 |     dateSelectionSegs: this.sliceDateSelection.apply(this, [props.dateSelection, eventUiBases, component].concat(extraArgs)),
       | ^  8447 |     businessHourSegs: this.sliceBusinessHours.apply(this, [props.businessHours, dateProfile, nextDayThreshold, calendar, component].concat(extraArgs)),
  8448 |     fgEventSegs: eventSegs.fg,
  8449 |     bgEventSegs: eventSegs.bg,

./node_modules/@fullcalendar/daygrid/main.esm.js/SimpleDayGrid</SimpleDayGrid.prototype.render
node_modules/@fullcalendar/daygrid/main.esm.js:1542

  1539 | SimpleDayGrid.prototype.render = function (props, context) {
  1540 |     var dayGrid = this.dayGrid;
  1541 |     var dateProfile = props.dateProfile, dayTable = props.dayTable;
> 1542 |     dayGrid.receiveProps(__assign({}, this.slicer.sliceProps(props, dateProfile, props.nextDayThreshold, context.calendar, dayGrid, dayTable), { dateProfile: dateProfile, cells: dayTable.cells, isRigid: props.isRigid }), context);
       | ^  1543 | };
  1544 | SimpleDayGrid.prototype.buildPositionCaches = function () {
  1545 |     this.dayGrid.buildPositionCaches();

../node_modules/@fullcalendar/core/main.esm.js/Component</Component.prototype.receiveProps
node_modules/@fullcalendar/core/main.esm.js:3951

  3948 | if (oldContext) {
  3949 |     this.beforeUpdate();
  3950 | }
> 3951 | this.render(comboProps, context);
       | ^  3952 | if (oldContext) {
  3953 |     this.afterUpdate();
  3954 | }

./node_modules/@fullcalendar/daygrid/main.esm.js/DayGridView</DayGridView.prototype.render
node_modules/@fullcalendar/daygrid/main.esm.js:1597

  1594 |         renderIntroHtml: this.renderHeadIntroHtml
  1595 |     }, context);
  1596 | }
> 1597 | this.simpleDayGrid.receiveProps({
       | ^  1598 |     dateProfile: dateProfile,
  1599 |     dayTable: dayTable,
  1600 |     businessHours: props.businessHours,

../node_modules/@fullcalendar/core/main.esm.js/Component</Component.prototype.receiveProps
node_modules/@fullcalendar/core/main.esm.js:3951

  3948 | if (oldContext) {
  3949 |     this.beforeUpdate();
  3950 | }
> 3951 | this.render(comboProps, context);
       | ^  3952 | if (oldContext) {
  3953 |     this.afterUpdate();
  3954 | }

../node_modules/@fullcalendar/core/main.esm.js/CalendarComponent</CalendarComponent.prototype.renderView
node_modules/@fullcalendar/core/main.esm.js:6298

  6295 |         var transformer = transformers_1[_i];
  6296 |         __assign(viewProps, transformer.transform(viewProps, viewSpec, props, options));
  6297 |     }
> 6298 |     view.receiveProps(viewProps, this.buildComponentContext(this.context, viewSpec, view));
       | ^  6299 | };
  6300 | // Sizing
  6301 | // -----------------------------------------------------------------------------------------------------------------

../node_modules/@fullcalendar/core/main.esm.js/CalendarComponent</CalendarComponent.prototype.render
node_modules/@fullcalendar/core/main.esm.js:6162

  6159 |     var title = this.computeTitle(props.dateProfile, props.viewSpec.options);
  6160 |     this.renderSkeleton(context);
  6161 |     this.renderToolbars(props.viewSpec, props.dateProfile, props.currentDate, title);
> 6162 |     this.renderView(props, title);
       | ^  6163 |     this.updateSize();
  6164 |     this.thawHeight();
  6165 | };

../node_modules/@fullcalendar/core/main.esm.js/Component</Component.prototype.receiveProps
node_modules/@fullcalendar/core/main.esm.js:3951

  3948 | if (oldContext) {
  3949 |     this.beforeUpdate();
  3950 | }
> 3951 | this.render(comboProps, context);
       | ^  3952 | if (oldContext) {
  3953 |     this.afterUpdate();
  3954 | }

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.renderComponent
node_modules/@fullcalendar/core/main.esm.js:6825

  6822 | var eventUiSingleBase = this.buildEventUiSingleBase(viewSpec.options);
  6823 | var eventUiBySource = this.buildEventUiBySource(state.eventSources);
  6824 | var eventUiBases = this.eventUiBases = this.buildEventUiBases(renderableEventStore.defs, eventUiSingleBase, eventUiBySource);
> 6825 | component.receiveProps(__assign({}, state, { viewSpec: viewSpec, dateProfileGenerator: this.dateProfileGenerators[viewType], dateProfile: state.dateProfile, eventStore: renderableEventStore, eventUiBases: eventUiBases, dateSelection: state.dateSelection, eventSelection: state.eventSelection, eventDrag: state.eventDrag, eventResize: state.eventResize }), this.buildComponentContext(this.theme, this.dateEnv, this.optionsManager.computed));
       | ^  6826 | if (this.isViewUpdated) {
  6827 |     this.isViewUpdated = false;
  6828 |     this.publiclyTrigger('viewSkeletonRender', [

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.executeRender
node_modules/@fullcalendar/core/main.esm.js:6799

  6796 | // clear these BEFORE the render so that new values will accumulate during render
  6797 | this.needsRerender = false;
  6798 | this.isRendering = true;
> 6799 | this.renderComponent();
       | ^  6800 | this.isRendering = false;
  6801 | // received a rerender request while rendering
  6802 | if (this.needsRerender) {

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.tryRerender
node_modules/@fullcalendar/core/main.esm.js:6782

  6779 |         !this.renderingPauseDepth && // not paused
  6780 |         !this.isRendering // not currently in the render loop
  6781 |     ) {
> 6782 |         this.executeRender();
       | ^  6783 |     }
  6784 | };
  6785 | Calendar.prototype.batchRendering = function (func) {

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.requestRerender
node_modules/@fullcalendar/core/main.esm.js:6774

  6771 | // -----------------------------------------------------------------------------------------------------------------
  6772 | Calendar.prototype.requestRerender = function () {
  6773 |     this.needsRerender = true;
> 6774 |     this.delayedRerender(); // will call a debounced-version of tryRerender
       | ^  6775 | };
  6776 | Calendar.prototype.tryRerender = function () {
  6777 |     if (this.component && // must be accepting renders

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.batchRendering
node_modules/@fullcalendar/core/main.esm.js:6790

  6787 |     func();
  6788 |     this.renderingPauseDepth--;
  6789 |     if (this.needsRerender) {
> 6790 |         this.requestRerender();
       | ^  6791 |     }
  6792 | };
  6793 | // Rendering

../node_modules/@fullcalendar/core/main.esm.js/Calendar</Calendar.prototype.mutateOptions
node_modules/@fullcalendar/core/main.esm.js:6903

  6900 | if (anyDifficultOptions) {
  6901 |     this.handleOptions(this.optionsManager.computed);
  6902 | }
> 6903 | this.batchRendering(function () {
       | ^  6904 |     if (anyDifficultOptions) {
  6905 |         if (isTimeZoneDirty) {
  6906 |             _this.dispatch({

./node_modules/@fullcalendar/react/main.esm.js/FullCalendar</FullCalendar.prototype.componentDidUpdate
node_modules/@fullcalendar/react/main.esm.js:74

  71 |             updates[propName] = props[propName];
  72 |         }
  73 |     }
> 74 |     this.calendar.mutateOptions(updates, removals, false, deepEqual);
     | ^  75 | };
  76 | FullCalendar.prototype.componentWillUnmount = function () {
  77 |     this.calendar.destroy();

commitLifeCycles
node_modules/react-dom/cjs/react-dom.development.js:22117

  22114 |       }
  22115 |     }
  22116 | 
> 22117 |     instance.componentDidUpdate(prevProps, prevState, instance.__reactInternalSnapshotBeforeUpdate);
        | ^  22118 |     stopPhaseTimer();
  22119 |   }
  22120 | }

commitLayoutEffects
node_modules/react-dom/cjs/react-dom.development.js:25344

  25341 | if (effectTag & (Update | Callback)) {
  25342 |   recordEffect();
  25343 |   var current$$1 = nextEffect.alternate;
> 25344 |   commitLifeCycles(root, current$$1, nextEffect, committedExpirationTime);
        | ^  25345 | }
  25346 | 
  25347 | if (effectTag & Ref) {

callCallback
node_modules/react-dom/cjs/react-dom.development.js:336

  333 |     window.event = windowEvent;
  334 |   }
  335 | 
> 336 |   func.apply(context, funcArgs);
      | ^  337 |   didError = false;
  338 | } // Create a global error event handler. We use this to capture the value
  339 | // that was thrown. It's possible that this error handler will fire more

invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:385

  382 | // errors, it will trigger our global error handler.
  383 | 
  384 | evt.initEvent(evtType, false, false);
> 385 | fakeNode.dispatchEvent(evt);
      | ^  386 | 
  387 | if (windowEventDescriptor) {
  388 |   Object.defineProperty(window, 'event', windowEventDescriptor);

invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:440

  437 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  438 |   hasError = false;
  439 |   caughtError = null;
> 440 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  441 | }
  442 | /**
  443 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores

commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js:25082

  25079 | 
  25080 | do {
  25081 |   {
> 25082 |     invokeGuardedCallback(null, commitLayoutEffects, null, root, expirationTime);
        | ^  25083 | 
  25084 |     if (hasCaughtError()) {
  25085 |       if (!(nextEffect !== null)) {

unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:697

  694 | currentPriorityLevel = priorityLevel;
  695 | 
  696 | try {
> 697 |   return eventHandler();
      | ^  698 | } finally {
  699 |   currentPriorityLevel = previousPriorityLevel;
  700 | }

runWithPriority$2
node_modules/react-dom/cjs/react-dom.development.js:12149

  12146 | 
  12147 | function runWithPriority$2(reactPriorityLevel, fn) {
  12148 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 12149 |   return Scheduler_runWithPriority(priorityLevel, fn);
  12150 | }
  12151 | function scheduleCallback(reactPriorityLevel, callback, options) {
  12152 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);

commitRoot
node_modules/react-dom/cjs/react-dom.development.js:24922

  24919 | 
  24920 | function commitRoot(root) {
  24921 |   var renderPriorityLevel = getCurrentPriorityLevel();
> 24922 |   runWithPriority$2(ImmediatePriority, commitRootImpl.bind(null, root, renderPriorityLevel));
  24923 |   return null;
  24924 | }
  24925 | 

finishSyncRender
node_modules/react-dom/cjs/react-dom.development.js:24329

  24326 |     }
  24327 |   }
  24328 | 
> 24329 |   commitRoot(root);
  24330 | }
  24331 | 
  24332 | function flushRoot(root, expirationTime) {

performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:24307

  24304 |   stopFinishedWorkLoopTimer();
  24305 |   root.finishedWork = root.current.alternate;
  24306 |   root.finishedExpirationTime = expirationTime;
> 24307 |   finishSyncRender(root, workInProgressRootExitStatus, expirationTime);
        | ^  24308 | } // Before exiting, make sure there's a callback scheduled for the next
  24309 | // pending level.
  24310 | 

flushSyncCallbackQueueImpl/<
node_modules/react-dom/cjs/react-dom.development.js:12199

  12196 |     var callback = queue[i];
  12197 | 
  12198 |     do {
> 12199 |       callback = callback(_isSync);
        | ^  12200 |     } while (callback !== null);
  12201 |   }
  12202 | });

unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:697

  694 | currentPriorityLevel = priorityLevel;
  695 | 
  696 | try {
> 697 |   return eventHandler();
      | ^  698 | } finally {
  699 |   currentPriorityLevel = previousPriorityLevel;
  700 | }

runWithPriority$2
node_modules/react-dom/cjs/react-dom.development.js:12149

  12146 | 
  12147 | function runWithPriority$2(reactPriorityLevel, fn) {
  12148 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 12149 |   return Scheduler_runWithPriority(priorityLevel, fn);
  12150 | }
  12151 | function scheduleCallback(reactPriorityLevel, callback, options) {
  12152 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);

flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:12194

  12191 | try {
  12192 |   var _isSync = true;
  12193 |   var queue = syncQueue;
> 12194 |   runWithPriority$2(ImmediatePriority, function () {
        | ^  12195 |     for (; i < queue.length; i++) {
  12196 |       var callback = queue[i];
  12197 | 

flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:12182

  12179 |     Scheduler_cancelCallback(node);
  12180 |   }
  12181 | 
> 12182 |   flushSyncCallbackQueueImpl();
  12183 | }
  12184 | 
  12185 | function flushSyncCallbackQueueImpl() {

scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:23709

  23706 |       // scheduleCallbackForFiber to preserve the ability to schedule a callback
  23707 |       // without immediately flushing it. We only do this for user-initiated
  23708 |       // updates, to preserve historical behavior of legacy mode.
> 23709 |       flushSyncCallbackQueue();
        | ^  23710 |     }
  23711 |   }
  23712 | } else {

dispatchAction
node_modules/react-dom/cjs/react-dom.development.js:17076

  17073 |       }
  17074 |     }
  17075 | 
> 17076 |     scheduleWork(fiber, expirationTime);
  17077 |   }
  17078 | }
  17079 | 
```

There are some dirty hacks to cope with this problem but it would be great if some safety-checks would be done. Of course "normally" this would not happen (it can if you spam-click a page). Therefore it would be great if you could check if it is null (maybe already in some top-level function)

I don't mind if you want to finish version 5 first, it would just be great if Fullcalendar does not crash because of some weird timed clicks

Thank you for your support and keep up the good work :+1:

**Comment by mistakenot** [comment] 2020-02-23 18:36
+1 I'm also having a similar issue.

I've got a simple, React based app with FullCalendar using the React component.

This issue is happening whenever you try to call "setState" in React from inside certain callbacks such as `dateClick`

```
./node_modules/@fullcalendar/core/main.esm.js/Slicer</Slicer.prototype._sliceDateSpan
src/charliescalander/node_modules/@fullcalendar/core/main.esm.js:8519

  8516 | if (!dateSpan) {
  8517 |     return [];
  8518 | }
> 8519 | var eventRange = fabricateEventRange(dateSpan, eventUiBases, component.context.calendar);
       | ^  8520 | var segs = this.sliceRange.apply(this, [dateSpan.range].concat(extraArgs));
  8521 | for (var _a = 0, segs_1 = segs; _a < segs_1.length; _a++) {
  8522 |     var seg = segs_1[_a];
```

**Comment by mistakenot** [comment] 2020-02-23 18:37
Should add, I too am on 4.4.0 of fullcalendar.

**Comment by mistakenot** [comment] 2020-02-23 18:40
Rolling back to 4.3.0 has removed the issue.

**Comment by Phibedy** [comment] 2020-02-23 19:19
Oh I see, this is quite easy to reproduce, if you hold the events in a react component and use `events=function` you can just press the next month button and select some days -> crash

**Comment by Phibedy** [comment] 2020-02-23 19:43
@mistakenot what versions did you use for what packages? I tried all different versions and it still fails

**Comment by acerix** [comment] 2020-02-25 20:58
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't get the error in debug template but it's not using "useMemo":

https://codesandbox.io/s/fullcalendar-react-8hk99

**Comment by Phibedy** [comment] 2020-02-25 22:14
Got it:
```
import React, { useState, useEffect } from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import "@fullcalendar/core/main.css";
import "@fullcalendar/daygrid/main.css";
import "@fullcalendar/timegrid/main.css";

export default function AppCalendar(props) {
  const [activeBound, setActiveBound] = useState({});
  const [wasd, setWasd] = useState(null);

  const updateEvents = () => {
    if (activeBound.start && activeBound.end) {
      fetch(`google.com`, {
        credentials: "include"
      }).then(() => {
        setWasd(`${wasd} 1`);
      });
    }
  };
  useEffect(updateEvents, [activeBound.start, activeBound.end]);

  const datesRender = info => {
    //change the dates which we want to show in the calendar and update the bounds to fetch events
    setActiveBound({
      start: info.view.activeStart,
      end: info.view.activeEnd
    });
  };

  const renderCalendar = () => {
    return (
      <FullCalendar
        datesRender={datesRender}
        defaultView="dayGridMonth"
        header={{
          left: "prev,next today",
          center: "title",
          right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek"
        }}
        plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
        selectable={true}
      />
    );
  };
  return <div>{renderCalendar()}</div>;
}
```
Just press the F5 key to reload the page and spam-click one day: https://codesandbox.io/s/fullcalendar-react-ikht8

**Comment by acerix** [comment] 2020-02-26 19:35
Thanks for the demo.  Since the error only happens with `select` enable, I believe it may be the same as this issue:
https://github.com/fullcalendar/fullcalendar/issues/5266
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

I am not sure how to access the calendar API in your demo but calling `calendarApi.unselect()` before `setWasd` might work as a workaround.

**Comment by Justinohallo** [comment] 2020-03-02 20:43
This is still an issue. #5266 does not truly reflect the issue at hand. 
I tried rolling back to 4.3 and I still have issues. 

Has anyone been able to create a codepen where this works? 

I want to be able to initiate a drawer action once the user selects a range.

**Comment by djredhand** [comment] 2020-03-03 15:47
> Thanks for the demo. Since the error only happens with `select` enable, I believe it may be the same as this issue:
> #5266
> ↑
> Please visit the above issue, **give a**  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the **Subscribe** button to receive updates.
> 
> I am not sure how to access the calendar API in your demo but calling `calendarApi.unselect()` before `setWasd` might work as a workaround.

In my case calendarApi.unselect() worked! While downgrading back to 4.3.1 also worked I was not happy with that solution. Can you tell us why `calendarApi.unselect()` works?

**Comment by Justinohallo** [comment] 2020-03-03 16:07
@djredhand How did you access calendarAPI.unselect()? 

Was it through the react ref?  

const calendarComponentRef = useRef<FullCalendar>();

Or was it through the event handler? 

const handleDateClick = arg => {
   arg.view.unselect()? 
  };

**Comment by djredhand** [comment] 2020-03-03 16:44
@Justinohallo, I used the ref. Like so:
`.then(resData => {
        const calendarApi = this.calendarComponentRef.current.getApi();
        // workaround from https://github.com/fullcalendar/fullcalendar/issues/5270
        calendarApi.unselect();
        dispatch({
          type:'ADD_EVENT',
          payload: resData
        });
      });`

**Comment by Justinohallo** [comment] 2020-03-03 17:23
@djredhand thank you. This is the correct answer.

**Comment by arshaw** [comment] 2020-06-29 22:56
i believe this was fixed in the last v4 release, but if not, it is definitely fixed in v5

**Closed by arshaw** 2020-06-29 22:56 UTC
Labels: Confirmed, Date Point/Select
