### ISSUE TITLE
Error composing FullCalendar

### ISSUE THREAD

**Issue by KirkOlson** [fullcalendar/fullcalendar#3632] opened 2017-04-11 15:36 UTC
I get an error when I try to add FullCalendar to my composer.json
or when I try : composer require bower-asset/fullcalendar

[UnexpectedValueException] Could not parse version constraint >=~2: Invalid version string "~2"

 I've also tried using "3.3.1" instead of "dev-master". When I remove the FullCalendar from my require section everything works fine. I'm not exactly a composer wizard so any help would be useful. My composer is up-to-date (1.4.1).

 
```
"require": {
  "php": ">=5.5.9",
  "laravel/framework": "5.3.*",
  "laravelcollective/html": "5.*",

  "symfony/finder": "^3.0",
  "symfony/yaml": "^3.0",

  "firephp/firephp-core": "^0.4.0",
  "wpb/string-blade-compiler": "3.3.0",
  "mpdf/mpdf": "^6.1",
  "PHPOffice/PHPExcel": "^1.8",
  "mgargano/simplehtmldom": "^1.5",

  "components/font-awesome": "dev-master",
  "components/modernizr": "2.8.3",

  "barryvdh/laravel-debugbar": "^2.3",

  "bower-asset/animate.css": "dev-master",
  "bower-asset/autosize": "dev-master",
  "bower-asset/autogrow": "1.0.2",
  "bower-asset/chartjs": "dev-master",
  "bower-asset/eventemitter": "dev-master",
  "bower-asset/framework7": "dev-master",
  "bower-asset/fullcalendar": "dev-master"
  "bower-asset/jsanimatedmodal": "dev-master",
  "bower-asset/jquery": "3.1.1",
  "bower-asset/jquery-idletimer": "dev-master",
  "bower-asset/jquery-ui": "dev-master",
  "bower-asset/jquery.transit": "dev-master",
  "bower-asset/magnific-popup": "dev-master",
  "bower-asset/moment": "^2.1",
  "bower-asset/OwlCarouselBower": "dev-master",
  "bower-asset/photoswipe": "dev-master",
  "bower-asset/platform": "dev-master",
  "bower-asset/select2": "dev-master",
  "bower-asset/selectize": "dev-master",
  "bower-asset/spin.js": "dev-master",
  "bower-asset/spinkit": "dev-master",
  "bower-asset/underscore": "dev-master",
  "bower-asset/vue": "1.0.28",
  "bower-asset/jquery-file-download": "^1.4",
  "bower-asset/tooltipster": "^4.1",
  "bower-asset/vue-multiselect": "^1.1",
  "nnnick/chartjs": "^2.2",
  "phpoffice/phpword": "^0.13.0",
  "peekmo/jsonpath": "dev-master",
  "guzzlehttp/guzzle": "dev-master",
  "bower-asset/jquery-simple-slideshow": "^1.0"
},
```

**Comment by DennisNikolay** [comment] 2017-04-19 14:46
Probably related to: https://github.com/fullcalendar/fullcalendar/issues/3526

**Comment by arshaw** [comment] 2017-04-25 17:20
yes, this problem is a duplicate of #3526. The problem was with `composer-asset-plugin`  which seems to have been fixed+released.

**Closed by arshaw** 2017-04-25 17:20 UTC
Labels: Distribution, Reproducing
