### ISSUE TITLE
Events displayed on wrong date when pushed down by previous events that span multiple days

### ISSUE THREAD

**Issue by SelectSystemsInternational** [fullcalendar/fullcalendar#5408] opened 2020-05-10 23:58 UTC
You might want to have a look at this one. When a lot of events are displayed a couple are displayed on the wrong date. If you click on the events displayed on the 18th May they are actually for the 11th May. A temporary fix is setting dayMaxEvents: 6
See https://codepen.io/SelectSystemsInternational/pen/MWavWxz

**Comment by acerix** [comment] 2020-05-11 22:18
I tested in the debug template with many events and don't have the issue:

https://codepen.io/acerix/pen/LYprzVJ

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/), ie. removing any code not related to the bug? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by SelectSystemsInternational** [comment] 2020-05-12 05:39
I added my events list to your pen 
https://codepen.io/SelectSystemsInternational/pen/zYvajzK

**Comment by acerix** [comment] 2020-05-13 22:49
Thanks, confirmed.  

https://codepen.io/acerix/pen/ExVpMZG?editors=0010

**Comment by arshaw** [comment] 2020-05-20 09:37
fixed in beta3. more info on the release: https://fullcalendar.io/blog/2020/05/react-ts-v5-beta

proof: https://codepen.io/arshaw/pen/LYpMQNG?editors=0010

**Closed by arshaw** 2020-05-20 09:37 UTC
Labels: Confirmed, DayGrid View

**Comment by SelectSystemsInternational** [comment] 2020-05-20 10:14
This is fixed but I am checking on  the rending of the events that go over two days. They are rendered differently to the one day events See https://codepen.io/SelectSystemsInternational/pen/zYvajzK

**Comment by arshaw** [comment] 2020-05-20 20:11
yup that is the intended *default* behavior. you're supposed to be able to control that behavior with the `eventDisplay` setting but I see that it doesn't work in beta3. i'll file another issue and fix
