### ISSUE TITLE
Missing min.js, automatically googles hotlinking

### ISSUE THREAD

**Issue by anteAdamovic** [fullcalendar/fullcalendar#3772] opened 2017-07-31 06:08 UTC
### Bug Reports
https://fullcalendar.io/js/fullcalendar-3.4.0/fullcalendar.min.js needs a check,

it automatically googles `hotlinking` since the only line in the file is 

`window.location.href = "https://www.google.com/search?q=hotlinking";`

Had to revert to older version (3.3.1) to fix the problem.

**Comment by ben-pelletier** [comment] 2017-07-31 13:37
experiencing same issue

**Comment by lesilent** [comment] 2017-07-31 21:22
Why are you guys hotlinking to that url instead of this url?

[https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js](https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js)

**Comment by espen** [comment] 2017-07-31 21:40
Download or use the CDN as @lesilent says. See https://fullcalendar.io/download/

In general you shouldn't trust third party sites with serving your javascript. While FullCalendar is indeed the source it is not meant to be a production grade service for your javascript files. It's a security and stability issue as well potentially problematic for the host (bandwidth costs).

Please close this issue.

**Comment by ben-pelletier** [comment] 2017-08-01 16:46
the issue is affecting the project website.

**Comment by arshaw** [comment] 2017-08-01 17:56
@ben-pelletier it is affecting fullcalendar.io only because your response for the JS file is now cached. If you clear your cache, will be fixed. I will devise a better solution for this. I will also provide a more informative wrist-slapping when hotlinking occurs.

**Comment by ben-pelletier** [comment] 2017-08-01 18:29
@arshaw I do apologize. I've corrected the linking on or end. And yea, to force a redirect to a google search really isn't the most appropriate solution...😛

**Comment by arshaw** [comment] 2017-08-04 16:44
To explain *why* this is now happening: some sites were using serious bandwidth requesting JS/CSS files from fullcalendar.io. I am now forbidding hotlinking to cut this down.

**Solution:** just use the CDN (see "CDNJS" on https://fullcalendar.io/download/)

Now, when a non-fullcalendar.io referrer requests a static file fullcalendar.io, they will get a **403 bidden** page with instructions to the CDN. Unfortunately, Chrome inspector does not show the contents of request. I'm spending too much time on this issue however, so will leave as-is. Simply don't hotlink!

**Closed by arshaw** 2017-08-04 16:44 UTC
